### ISSUE TITLE
Clear cookes not on the Whitelist when exiting Firefox.

### ISSUE THREAD

**Issue by streetwolf** [mrdokenny/Cookie-AutoDelete#14] opened 2017-05-14 17:49 UTC
There always seem to be a few non whitelisted cookies that never get deleted for some reason.  An option to clear all non whitelisted cookies when exiting Fx would probably handle this.

**Comment by mrdokenny** [comment] 2017-05-14 18:28
It's probably cause you had a site or a subdomain still open relating to that cookie. You can try going into the popup -> Cookie cleanup (Ignore open tabs) and see if that helps.

**Comment by mrdokenny** [comment] 2017-05-15 03:51
Also, currently there's no way to set an extension to do something on exit with current WebExtension APIs, so it would have to be on browser start up.

**Comment by labors89** [comment] 2017-05-15 06:32
Failling to clear github cookies with the addon.
1. open github page and log in
2. click "clean all cookies: ignore open tabs"
3. reload
Still logged.
4. try closing all tabs github related
Still logged
:(

**Comment by mrdokenny** [comment] 2017-05-15 14:39
@labors89 Have you used any other Cookie Extension before by any chance?

Try these troubleshooting steps:
1. Clear all your cookies (start with a clean slate)
2. Reset settings other cookie extensions might have made in about:config -> restore default of all network.cookie.* preferences

**Comment by labors89** [comment] 2017-05-15 16:04
> Try these troubleshooting steps:

    Clear all your cookies (start with a clean slate)
    Reset settings other cookie extensions might have made in about:config -> restore default of all network.cookie.* preferences

Did the above but github cookies still present, same problem happens in chrome, even with a new profile with only ublock origin and cookie-autodelete enable..

**Comment by mrdokenny** [comment] 2017-05-15 16:11
@labors89 That's weird cause I don't have this issue. Can you go into your developer tools and click Browser Console (Contol + Shift + J) on Firefox and see what appears when you click Cookie Cleanup in the options.

**Comment by labors89** [comment] 2017-05-15 18:01
Hmm, for some weird reason it didn't worked with firefox , chrome or chrome + new profile. Just tried to create a new profile with firefox and now everything is gold.
I really have no clue about how to analyse the console output, sorry I cannot pinpoint the cause. But thank you anyway :)

**Comment by mrdokenny** [comment] 2017-05-15 18:12
@labors89 Yeah I figured a new profile would help since legacy extensions like to leave a lot of crud that doesn't get cleared until you make a new profile.

**Closed** 2017-05-20 02:35 UTC
Labels: enhancement
