### ISSUE TITLE
[FEATURE REQUEST] Block Cookies

### ISSUE THREAD

**Issue by jputting** [mrdokenny/Cookie-AutoDelete#1538] opened 2023-05-05 19:33 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

Simply erasing cookies not used is not good enough, many websites abuse cookies to time the appearance of high intrusive popup, redirects and ads.

Blocking cookies from being set by a website is a must have feature.

### Describe the solution that you'd like

Add the option to block cookies being set by individual websites.

**Comment by gitgrub** [comment] 2023-05-08 18:35
I guess that is a feature your browser has built in already.
I.e.: `chrome://settings/cookies`

**Comment by kennethtran93** [comment] 2023-05-10 01:59
Duplicate of #134 and #711.

Keep in mind that we cannot prevent browsers from setting cookies.  All we can do is monitor for cookie changes and remove them after it has been created.  This is already noted in those referenced requests.

**Closed as not planned by kennethtran93** 2023-05-10 01:59 UTC
Labels: Feature Request

**Comment by jputting** [comment] 2023-05-10 09:14
That is not correct there are numerous other Chrome Extensions which do in fact have the ability to block cookies built into their design. Forget Me Not, CookieMaster and CookieBro have the ability to Blacklist website cookies and CookieBro and other extensions can be configured to block all cookies via adding "*.*" to it, or cookies can be blocked via CookieBro's logs.

I find it to be much simpler and quicker to use an extension to block cookies via a toolbar button than going into the browser menus which takes more mouse clicks and more effort.

If CookieBro can achieve this degree of functionality there is NO reason why Cookie-AutoDelete should be missing this useful function.
