### ISSUE TITLE
Strange error message "e.settings(t) is undefined"

### ISSUE THREAD

**Issue by cookie-user** [mrdokenny/Cookie-AutoDelete#484] opened 2019-01-14 06:15 UTC
### Describe the Bug/Feature
Error message saying "e.settings(t) is undefined" keeps popping up. Noticed it when started Firefox and started typing to "network search" bar in home page, perhaps not the reason though. 

Also, "Settings"-page becomes full of only some kind of error text, after clicking a panel title on the left side.  

### Screenshot in which the bug can be seen

![errormessage](https://user-images.githubusercontent.com/46665953/51098420-e25fa200-17d2-11e9-8b1f-93cd1c712bea.png)

![settings - page](https://user-images.githubusercontent.com/46665953/51098391-a4627e00-17d2-11e9-9449-1c4fbb50b9c6.png)

### Steps for anyone to reproduce the bug

Error message:
- Start Firefox
- Start a new Firefox window (Ctrl-N)
- Close it. 

Settings-issue:
- Open Settings
- Click a panel title on the leftside bar

### Your settings 

- OS/version:  Windows 8.1 
- Browser/version: Firefox Quantum 64.0.2 32-bit
- Cookie AutoDelete version: 3.0.0, updated Jan 1, 2019

**Comment by ke-d** [comment] 2019-01-14 06:25
It looks like your settings is corrupted. Have you tried resetting settings?

Also, can't reproduce this but can probably reproduce it by corrupting the settings manually.

**Comment by rugk** [comment] 2019-01-14 07:05
Also something similarly broken:
> can't convert undefined to object t.default</</n<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3219 t.default</<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3191 t.default<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3169 di@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:61969 qi@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:78334 Ki@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:78711 Ao@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:85134 Oo@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:84514 Do@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:90725 Sn@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:30438 at line 20 

After pressing the button to restore the default options, it just changes from:
> can't convert undefined to object t.default</</n<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3219 t.default</<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3191 t.default<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3169 di@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:61969 qi@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:78334 Ki@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:78711 Ao@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:85134 Oo@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:84514 Co@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:83535 Zi@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:82438 enqueueSetState@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:47366 w.prototype.setState@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:28:1652 componentDidMount/<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/setting.bundle.js:14:2565 a@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-background-popup-setting.bundle.js:30:1363 at line 20 

to:
> can't convert undefined to object t.default</</n<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3219 t.default</<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3191 t.default<@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:20:3169 di@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:61969 qi@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:78334 Ki@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:78711 Ao@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:85134 Oo@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:84514 Do@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:90725 Sn@moz-extension://e0f0292e-e7d6-4d86-b8ac-d9da2ef04052/bundles/common-popup-setting.bundle.js:36:30438 at line 20 

After a reload, the old error message is there again.

And the options are not actually reset, i.e. it seems the reset button does not work either.

I think some update may have destroyed something here.

**Comment by ke-d** [comment] 2019-01-14 07:42
@rugk That looks highly busted. Hmm..

What I could do is add more options to the Error message like a button to delete the extension storage (this would be different to the current `Restore Default Setting`). This way the extension can start from a clean slate. Maybe another button to export the lists as well.

**Comment by crtxcr** [comment] 2019-01-14 18:39
I confirm this strange error message, started today. Coincidence?

**Comment by cookie-user** [comment] 2019-01-14 19:18
Tried resetting settings to defaults. It didn't seem to work at first, 
there was a different text appearing,  but after I closed them and 
re-opened, everything seemed fine. Also, error message seems to be gone.

Jukka

Kenny Do kirjoitti 14.1.2019 klo 8:25:

**Comment by cookie-user** [comment] 2019-01-14 19:27
I haven't made any previous modifications to the settings on my own. For 
me it looks like the latest update did something to cause this.

**Comment by ke-d** [comment] 2019-01-14 20:47
It's possible you went from version 1 to version 3 without the migration from 1 to 2 first. 

![image](https://user-images.githubusercontent.com/17077613/51139988-32059400-17fa-11e9-8b01-3c658755512a.png)


Either way this fix should solve extension data corruptions by allowing exporting of lists and then deleting/resetting of all data. At this point, I would recommend you to restart the browser as well.

**Comment by cookie-user** [comment] 2019-01-14 21:39
For me just restoring settings to default using the existing "Restore default settings" - button seems to be working. Settings are still ok and error message hasn't showed up since.

**Comment by lgbaldoni** [comment] 2019-01-15 17:06
Clicking the restore default buttons enabled some of the settings submenus, allowing me at least to back up the settings, but it's a short-lived solution. The drop-down menu hasn't reappeared and updating to 3.0.1 hasn't made any difference.

Using Firefox 60.4.0esr on openSUSE Leap 15.0.

How can I cleanly purge the extension and start from scratch?

EDIT: nevermind, removing the extension, deleting its data folder and reinstalling did the trick for me.

**Comment by ke-d** [comment] 2019-01-15 17:13
@luigino 
![image](https://user-images.githubusercontent.com/17077613/51197130-874aaf80-18a5-11e9-8936-8256f4c6b4c1.png)

Open up the console in the settings of CAD and use these commands to clear and reload the extension.
`await browser.storage.local.clear(); await browser.runtime.reload();`

The new `Reset Extension Data` button also does these commands.

**Comment by rugk** [comment] 2019-01-16 14:57
BTW, now I also remember how this happened. Before that error, CAD showed me this:

![grafik](https://user-images.githubusercontent.com/11966684/51257117-3d49f280-19a7-11e9-8f1d-dbf6c95cb48d.png)

...every time it tried to clear cookies.

But the worst thing is: After resetting the options with the workaround (button) you've added, it actually does show it again. It did not show this bug red error message yet, but I am not convinced it won't happen again.

**Comment by ke-d** [comment] 2019-02-16 04:29
Marking as resolved since there's now a workaround that works for most people.

**Closed as completed by ke-d** 2019-02-16 04:29 UTC
Labels: bug
