### ISSUE TITLE
[BUG]  Error after closing a tab

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#702] opened 2020-04-27 09:55 UTC
**Describe the bug**

Whenever I close a tab I get an error message
Screenshot attached

**To Reproduce**

1. Go to any website
2. Close the tab again
3. Error message appears

**Expected behavior**

No Error message

**Screenshots**

https://imgur.com/a/eOxPcjW

**Your System Info (please complete the following information):**

 - OS: Windows 10
 - Browser Info: Firefox Nightly 77.0a1
 - CookieAutoDelete Version 3.2.0

**Additional context**
/

**Comment by kennethtran93** [comment] 2020-04-27 16:37
Duplicate of #699.  Please search for open issues before posting a new one.

**Closed as completed by kennethtran93** 2020-04-27 16:37 UTC
Labels: duplicate
