### ISSUE TITLE
Upgrade to 2.1.0 removed whitelist (and cleared all cookies)

### ISSUE THREAD

**Issue by fichtennadel** [mrdokenny/Cookie-AutoDelete#320] opened 2018-01-11 09:45 UTC
### Describe the Bug/Feature
Upgrade to 2.1.0 removed whitelist and cleared all cookies

### Screenshot in which the bug can be seen
![image](https://user-images.githubusercontent.com/2324670/34818887-7a55e5ee-f6bc-11e7-9439-a492518fb3c4.png)

### Steps for anyone to reproduce the bug
Upgrade to 2.1.0

### Your settings 
- OS/version: Win7x64
- Browser/version: FF 57.0.4
- Cookie AutoDelete version: 2.1.0

**Comment by planet0** [comment] 2018-01-11 11:13
Didn't happen to me, 2.1.0 kept my whitelist. macOS 10.13.2, Firefox 58.0b15

**Comment by GWuk** [comment] 2018-01-11 12:31
Couldn't reproduce it with backup of FF profile, but it did definitely happen.

**Comment by ke-d** [comment] 2018-01-11 16:24
I haven't touched the expressions code in 2.1.0 and I haven't noticed this. So I can't move forward without a reliable STR.

**Comment by kennethtran93** [comment] 2018-01-11 20:07
The only thing that I modified that was in v2.1.0, in relation to the expression settings page, was the input focus on edit, and the export button for dynamic timestamp.  Neither should've caused this issue.

**Comment by ke-d** [comment] 2018-01-16 06:46
I guess the only possible explanation is that if the extension data gets corrupted somehow and has to start fresh.

**Comment by kennethtran93** [comment] 2019-02-14 06:18
As we are now in V3.X, this should probably be closed now.

**Comment by kennethtran93** [comment] 2019-06-11 19:28
Closing due to outdated extension version used.

**Closed as completed by kennethtran93** 2019-06-11 19:28 UTC
Labels: cannot reproduce
