### ISSUE TITLE
Is it possible to whitelist certain cookies instead of the website?

### ISSUE THREAD

**Issue by Colon-D** [mrdokenny/Cookie-AutoDelete#393] opened 2018-05-09 02:43 UTC
I would like to whitelist the cookie that keeps YouTube on it's dark theme, but I can not find a way to do so without whitelisting all of YouTube. (specifically the PREF cookie on YouTube, as I believe it controls whether or not the dark theme is used).

**Comment by ke-d** [comment] 2018-05-09 05:05
Duplicate of #68

**Closed as completed by ke-d** 2018-05-09 05:05 UTC
Labels: duplicate
