### ISSUE TITLE
Non-whitelisted sites showing up in Firefox's "Manage Site Cookies and Site Data"

### ISSUE THREAD

**Issue by avekifes** [mrdokenny/Cookie-AutoDelete#585] opened 2019-11-11 22:12 UTC
### Describe the Bug/Feature

I'm noticing a handful of non-whitelisted sites showing up in Firefox's "Manage Site Cookies and Site Data" box. Is this merely a quirk of the browser? Many of these are showing "0 cookies," although there is some amount of storage being used, which has me concerned.

### Your settings 

- OS/version: Windows 10 1903
- Browser/version: Firefox 70.0.1
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment] 2019-11-11 22:19
This issue is a duplicate of #512 and others.
You'll find the reason while reading that issue's thread.

Please remember to search up your issue to see if others have similar issues.

**Closed as completed by kennethtran93** 2019-11-11 22:19 UTC
Labels: duplicate, browserbug/limitation
