### ISSUE TITLE
[FEATURE REQUEST] Policies support

### ISSUE THREAD

**Issue by anatoli26** [mrdokenny/Cookie-AutoDelete#1394] opened 2022-05-24 06:10 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

Not sure if it's implemented, but I can't find documentation about Firefox policies support, i.e. https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/

### Describe the solution that you'd like

To implement FF policies support so it would be possible to configure the extension via `policies.json`, like e.g. uBlock Origin: https://github.com/mozilla/policy-templates#3rdparty?

**Comment by kennethtran93** [comment] 2022-05-24 06:30
Most likely duplicate of #534.  Currently no plans for this in the near future.

**Closed as not planned** 2022-05-24 06:31 UTC
Labels: Feature Request

**Comment by anatoli26** [comment] 2022-05-25 18:20
@kennethtran93, may I ask why you have no plans for this feature? Is there any other way to specify the default values for your extension?

AFAIK, you can configure FF with the policies almost completely, but the configuration for the extensions is unavailable if they don't support policies (like uBlock Origin), so one can't deploy FF with your preconfigured extension in a organization.

**Comment by anatoli26** [comment] 2022-05-26 04:28
And the code itself is rather trivial:

A manifest file should be defined:
```
{
  "name": "favorite-color-examples@mozilla.org",
  "description": "ignored",
  "type": "storage",
  "data":
  {
    "color": "management thinks it should be blue!"
  }
}
```

Then in the code the property could be accessed this way for the policy-defined value:
```
let storageItem = browser.storage.managed.get('color');
storageItem.then((res) => {
  console.log(`Managed color is: ${res.color}`);
});
```

And the `policies.json` file would look like this:

```
{
  "policies": {
    "3rdparty": {
      "Extensions": {
        "favorite-color-examples@mozilla.org": {
          "color": "blue"
        }
      }
    }
  }
}
```

**Comment by kennethtran93** [comment] 2022-05-26 07:02
There's much more work needed than just that.

Just off the top of my head, here's a list of stuff to plan for/discuss: Validation and global settings check, how to handle multiple exception/expressions and their individual configurations, should initial/default expressions be read only or just stored as a local copy that is changeable, what happens on an import/export, which should take precedence (import or managed), how about the (future) browser sync stuff, as well as the change events that it also has, etc. 
- Chrome also handle it slightly differently so we need to account for that as well.
-Firefox Android doesn't have support yet (but this is a check we can perform so that we don't run into this)


However if you are willing to spend some time into developing this for us and it works cross-browser platform, feel free to submit a Pull Request with your code and we can include it if it is all good.

**Comment by kennethtran93** [comment] 2022-05-26 07:07
There's much more work needed than just that.

Just off the top of my head, here's a list of stuff to plan for/discuss: Validation and global settings check, how to handle multiple exception/expressions and their individual configurations, should initial/default expressions be read only or just stored as a local copy that is changeable, what happens on an import/export, which should take precedence (import or managed), how about the (future) browser sync stuff, as well as the change events that it also has, etc, how do we warn users that their existing data may be removed if this extension was installed later on (especially when the other site data types are enabled as it will empty out those that are enabled on first enable/load) 

Chrome also handle it slightly differently so we need to account for that as well... 

Firefox Android doesn't have support yet (but this is a check we can perform so that we don't run into this)... 


However if you are willing to spend some time into developing this for us and it works cross-browser platform, feel free to submit a Pull Request with your code and we can include it if it is all good.

**Comment by anatoli26** [comment] 2022-05-26 07:20
I believe the way uBlock Origin does it is the most adequate: https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin.

Basically, in case of policy parsing errors just assume that no policy was defined and proceed as normal (as now).

For precedence and read-only: uBlock has 2 ways of configuring the settings (https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin:-configuration): forced values and initial default values (same settings could be defined under different branches: `toOverwrite` (forced) and `toAdd` (default list, user is free to add new items)).

I.e. if forced, they overwrite any user settings on each FF restart. The default ones just alter the default values of the extension and the user is free to change them later. For the default ones if the policy is defined AFTER the extension was initialized and a user made some changes, then unchanged default extension values could be altered and those that the user explicitly changed would be preserved.

Sync is implemented using the same functionality (i.e. they just expose the settings for Firefox Sync to process them): https://github.com/gorhill/uBlock/wiki/Cloud-storage.

Maybe it's not perfect, but it's better than not having any option at all for massive deployment.

I won't be able to contribute a PR, but maybe I could sponsor the development.

**Comment by mkaply** [comment] 2022-06-02 12:48
We do have documentation on how to do this,

https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/

**Comment by kennethtran93** [comment] 2022-06-11 02:53
> We do have documentation on how to do this,
> 
> https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/

This link was already noted on the first post.

**Comment by ruckerzerg** [comment] 2025-06-11 19:35
Why is this not planned? Here is a PR already implementing it: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/1605
