### ISSUE TITLE
[BUG]  Since Version 3.5.0 in Firefox CAD Icon dont change color an dont show number of cookies 

### ISSUE THREAD

**Issue by Mautzimann** [mrdokenny/Cookie-AutoDelete#852] opened 2020-08-22 14:31 UTC
Since CAD Version 3.5.0 behaviour of CAD icon in Firefox has changed in 2 ways:

1.) at tab change the color of icon dont change anymore, it shows always a blue icon (according to list: expected behaviour: blue = white list, red = no list, yellow: gray list). But the hover-info of icon shows the list correctly. 

Sometimes the correct icon appears for a short time, but then it changes back to the blue icon.

2.) the number of cookies of the associated domain of the current tab is never shown 
2.1.) as "badge" at the CAD Icon
2.2.) in the hower info alway is displayed "0" as count of cookies

The behaviour 
1. is the same in all current FF versions (ESR V.68.11, Current V. 79, Developer Edition 80.0.b8), 
2. is the same, if I use my "productive" FF or a FF without changed settings and without other addons.
3. is the same, if I use Containers or dont use it.

!! But if I install CAD 3.5.0 in the current Chrome Version 84.0.4147.135, all works fine !!

Steps to Reproduce:

- Have a whitelisted Site open in Tab A --> Icon is blue
- Open a Site (from Bookmark) of a non-listed site in a new tab B --> Icon dont change color to red
- Open a link from this Site in new Tab C --> Icon dont change color to red
- close Tab C --> Tab B is active --> Icon for a short time changes to red or stays red; but when I activate Tab A and the activate Tab B again, icon dont re-change to red

**Expected behavior**

- At change to Tab B Icon should be change to red.
- the FF Settings --> Privacy --> Edit data shows, Domain of Tab B has 3 Cookies, the number should be shown at the Icon and in the hover info of icon

**Your System Info (please complete the following information):**

 - OS: Windows 10 Home, Version 2004
 - Browser Info: see above
 - CookieAutoDelete Version: 3.5.0

Please let me know if you need console infos in activated CAD-debug-mode!

Greets from Germany!

Console output from Ctrl-shift-K:
----------------------------------------

<EDIT:  Removed console output as it is not relevant>

**Comment by kennethtran93** [comment] 2020-08-22 21:01
Duplicate of #839.

Fixed in #844.  Will push out 3.5.1 once other surfaced bugs gets fixed.

P.S:  Those console logs are not relevant at all. Those only lists messages from the site itself.  The extensions have a separate console log to which you can find instructions on if you enable debug mode.

**Closed as completed by kennethtran93** 2020-08-22 21:01 UTC
Labels: duplicate

**Comment by Mautzimann** [comment] 2020-08-23 08:03
Thank you, I didnt find the duplicating #839, maybe because it was closed too at this time!
