### ISSUE TITLE
Blacklisting sites to force cleanup

### ISSUE THREAD

**Issue by salva-maiorano** [mrdokenny/Cookie-AutoDelete#580] opened 2019-10-22 21:33 UTC
the current cleanup logic is focus on cleaning all sites, with the exception of sites that are whitelisted
it would be nice to have a domain whitelisted (not cleaning it up), and have only include a subdomain where you want to perform the clean up
eg
```
*.google.com      -> whitelist
*.mail.google.com -> blacklist
```
another particular case is to handle the cleanup of only the sites you select, leaving all the other sites untouched 
```
*             -> whitelist
*.badsite.com -> blacklist
```
ps: great app!

**Comment by kennethtran93** [comment] 2019-10-27 04:51
This duplicates other issues relating to blacklisting.  I suggest you search up the github issues for features and comment/react to those before creating a new issue/feature..

Closing due to duplicate of #134.  If any of the above details aren't already in that issue, feel free to add additional comments to it.

**Closed as completed by kennethtran93** 2019-10-27 04:51 UTC
Labels: duplicate, Feature Request
