### ISSUE TITLE
Greylist cookies not deleted on browser exit

### ISSUE THREAD

**Issue by qwence** [mrdokenny/Cookie-AutoDelete#268] opened 2017-11-23 05:50 UTC
The only rule I've added is a greylist rule for *, so I expect all cookies to be deleted on browser exit. But when I restart firefox (by Ctrl-Q and re-open the browser), I find cookies have not been deleted. The dropdown menu on the cookie auto-delete icon shows that the site is matched by the rule, but I see no cookie deletion notifications and, after restarting the browser, I'm still logged into all sites (github, gmail, etc.) that I was before.

Details:
* I can reproduce this on a clean profile with no other add-ons (actually, for a new user account with no settings for firefox or anything else). In particular, everything in about:config is default.
* privacy.firstparty.isolate = false
* Without the "*" greylist rule, I can see that the extension works as advertised (cookies are cleared on tab close).
* If I disable and then enable the extension (from the about:addons page), cookies are deleted.

Settings:
[X] Enable Automatic Cleaning? Delay Before Cleaning: 0 Minute(s) [bug also observed with 1 minute here]
[X] Log Total Number Of Cookies Deleted?
[X] Show Number of Cookies for that Domain?
[X] Show Notification After Cookie Cleanup?
[X] Clean Cookies from Open Tabs on Startup?
[ ] Enable Support for Firefox's Container Tabs?

- OS/version: Arch linux
- Browser/version: Firefox 57.0
- Cookie AutoDelete version: 2.0.1

**Comment by bhrgunatha** [comment] 2017-11-25 11:56
Same issue with Firefox Nightly (59.0a1 (2017-11-14) (64-bit)) but I'm using Cookie AutoDelete version: 2.0.0. It's a shame because I desperately need an extension like this.

**Comment by realityexists** [comment] 2017-12-03 15:06
I have the same problem in Firefox 57.0.1 (x65) on Windows 7. Cookie AutoDelete version 2.0.1. I have "*" in the greylist, Automatic Cleaning disabled. Cookies are not deleted on exit at all.

**Comment by realityexists** [comment] 2017-12-03 15:09
Actually, if I click the Cookie AutoDelete toolar button and click "Clean" there, cookies are not deleted either!

**Comment by wincak** [comment] 2017-12-19 09:19
This also happens on my Firefox 57.0.1, Ubuntu 14.04 with Cookie AutoDelete 2.0.1
I have greylisted "*.google.com" and "*google.com" to get rid of the consent cookie (from consent.google.com).
This cookie (and others also) does not get deleted neither on tab close, browser close nor system restart.
Automatic cleaning is disabled
Clean Cookies from Open Tabs on Startup is disabled
Enable Support for Firefox's Container Tabs is disabled
I have to clean cookies manually every time by "Clean cookies for this domain" or "Clean, include open tabs" button.

**Comment by ke-d** [comment] 2017-12-28 21:01
>The only rule I've added is a greylist rule for *, so I expect all cookies to be deleted on browser exit. 

WebExtensions can't do actions on browser exit reliability so CAD does a cleanup at browser start instead.

**Comment by realityexists** [comment] 2017-12-28 21:05
They're not cleaned on start, either, nor even when I click "Clean".

**Comment by ke-d** [comment] 2017-12-28 21:16
@realityexists 
>I have the same problem in Firefox 57.0.1 (x65) on Windows 7. Cookie AutoDelete version 2.0.1. I have "*" in the greylist, Automatic Cleaning disabled.

You need to enable automatic cleaning cause it is an "automatic clean" on browser start.

>nor even when I click "Clean"

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-do-all-the-cleanup-options-mean

That does a "normal cleanup" which by default doesn't clear greylisted cookies so when you have a "*" in the whitelist, it doesn't do anything as expected.

**Comment by realityexists** [comment] 2017-12-28 21:28
> You need to enable automatic cleaning cause it is an "automatic clean" on browser start.

Then it's a documentation issue, because https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enable-automatic-cleaning says "https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enable-automatic-cleaning" It does not say that greylisted cookies won't be deleted without this. I don't want them to be deleted when a tab is closed anyway, only when the whole browser is closed (or open).

Anyway, I just enabled Automatic Cleaning, restarted FF and Cookie-AutoDelete showed a notification that it deleted over 500 cookies, but I still have many cookies left from many sites. So I'm not sure what it actually deleted.

> That does a "normal cleanup" which by default doesn't clear greylisted cookies

That's really confusing, too. Not at all what I expected.

**Comment by ke-d** [comment] 2017-12-28 21:39
>It does not say that greylisted cookies won't be deleted without this. I don't want them to be deleted when a tab is closed anyway, only when the whole browser is closed (or open).

Yeah that's why you added a "*" in the expression list. The Automatic clean setting is there if you want to use CAD in manual mode.

The "clean" in the popup is the same that runs when a tab is closed.

>That's really confusing, too. Not at all what I expected.

Yeah, considering that there's 4 states that a cookie can be in CAD (horizontal bar of the table) and 4 cleanup configurations (vertical bar of the table), it can get pretty confusing.

**Comment by realityexists** [comment] 2017-12-28 21:41
The original problem remains: greylisted cookies are not automatically deleted, even with "automatic cleaning", even after restarting FF.

**Comment by ke-d** [comment] 2017-12-28 21:45
Steps to reproduce? Like what are you greylisting?

**Comment by realityexists** [comment] 2017-12-28 21:46
I have * greylisted and a few domains whitelisted (all in the form "*.domain.tld"). Automatic Cleaning with 1 minute delay. Cookies for many sites, e.g. en.wikipedia.org, just aren't deleted no matter what I do! Close tabs, close FF, click clean.

**Comment by ke-d** [comment] 2017-12-28 21:54
- Do you have wikipedia.org open in a tab? 
- Use `wikipedia.org` rather than `*.wikipedia.org` if you have it whitelisted.
- Have you ever turned on First party isolation? If so, you need to delete all cookies after disabling FPI.

**Comment by realityexists** [comment] 2017-12-28 21:58
No, I don't have wikipedia open in a tab and it's not whitelisted. It was just one example - I have cookies from hundreds of sites that are not whitelisted.

I don't know what "First part isolation" is, so probably not.

**Comment by ke-d** [comment] 2017-12-28 23:55
What happens in a new profile?

**Comment by realityexists** [comment] 2017-12-30 14:32
No cookies are deleted in a new profile. I even tried removing everything from the expression list, except for greylisting "*". In the existing profile Cookie-AutoDelete did delete *some* cookies on start-up (it popped up a notification about it, at least) - but I'm not sure how it decided which to delete. In the new profile nothing seemed to be deleted. I've since manually deleted all cookies in my existing profile and now it doesn't seem to delete anything there, either.

**Comment by ke-d** [comment] 2018-02-09 02:32
Unfortunately at this point, I have no idea sorry. I'm likely to close this issue if there are no further replies.

**Comment by realityexists** [comment] 2018-02-09 19:01
Do you have some kind of diagnostic logging that would say why it decides to delete or not delete a cookie? If not, it might be useful in general - not just for this issue.

**Comment by qwence** [comment] 2018-02-10 18:48
@mrdokenny Can you reproduce this issue? If not, maybe we can find out what is different about our setup vs. yours.

**Comment by Grossdm** [comment] 2018-02-11 02:19
@mrdokenny,
I'm confused about the advice you gave in [this post](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/268#issuecomment-354363815).

The [wiki description](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enter-expression) for expressions looks like the expression `*.example.com` should match both `cdn.example.com` and `example.com`, but the expression `example.com` should match `example.com` **only**.

Have I misunderstood something? I am just beginning to use CAD, so I have very little experience with its behavior.

TIA

**Comment by ke-d** [comment] 2018-02-11 16:11
@realityexists 

> Do you have some kind of diagnostic logging that would say why it decides to delete or not delete a cookie? If not, it might be useful in general - not just for this issue.

That would be #209 

@qwence 
>Can you reproduce this issue? If not, maybe we can find out what is different about our setup vs. yours.

No I can't.

Do you guys know how to build the extension? If you do then feel free to add `console.log()` diagnostics in this function call and then use `about:debugging`. Use the `load temporary add-on` and click the `Reload` button to simulate a browser restart in CAD.

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/2.X.X-Branch/src/services/CleanupService.js#L17

@Grossdm

I only suggested that since Wikipedia adds cookies for `en.wikipedia.org` as well as `wikipedia.org`

**Comment by Grossdm** [comment] 2018-02-23 23:30
@mrdokenny 
Please clarify this for me.

If I want to clean all cookies from `/https?://(.*\.)?example\.com/` and I may have gotten a cookie while viewing `http://example.com`, will `*.example.com` delete all the cookies, or will it leave cookies without a third level domain name?

I.E., do I need to (basically always) add both `*.example.com` and `example.com` to the greylist?

**Comment by Grossdm** [comment] 2018-03-06 22:41
@mrdokenny,
I have happened upon the answer to my (I think straightforward) question in another issue.

@stoically gives the answer by [reference to the Wiki](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/364#issuecomment-368586521).

So cheers to @stoically!

**Comment by ke-d** [comment] 2018-05-09 06:03
@qwence @realityexists There's a diagnostic log that you can try in the latest 2.2.0 beta. I'll write up some guides on how to debug why a site's cookies are/are not being deleted soon.

**Comment by ke-d** [comment] 2018-05-13 23:34
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-are-examplecoms-cookies-being-keptcleaned

Hopefully version 2.2.0 and the cleanup log helps! However, I'm closing this issue for inactivity.

**Closed as completed by ke-d** 2018-05-13 23:34 UTC
Labels: support
