### ISSUE TITLE
[Bug]  Type error when cleaning after closing a Tab

### ISSUE THREAD

**Issue by thomedes** [mrdokenny/Cookie-AutoDelete#1581] opened 2023-06-22 09:42 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

I'm getting repeatedly the following mesage:

> Type error for parameter options (Error processing hostnames.7: Error: Invalid hostname . [fe80::8669::xxxx::xxxx]) for browsingData.remove.

### To Reproduce

Close any tab and wait for autoclean to trigger.

### Expected Behavior

No error message.

### Screenshots

![imatge](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/assets/1986656/2ecbf31d-ba0d-413d-9747-6ece3eca5410)

### System Info - Operating System (OS)

Windows 10 Home 22H2

### System Info - Browser Info

Browser Info: Firefox 114 (20230619081400)

### System Info - CookieAutoDelete Version

3.8.2

#### System Info

- OS: x86-64 Windows 10 Home 22H2 (64 bits)
- Browser Info: Firefox 114 (20230619081400)
- CookieAutoDelete Version: 3.8.2

#### Current Settings

- activeMode: true
- delayBeforeClean: 15
- discardedCleanup: false
- domainChangeCleanup: false
- enableGreyListCleanup: true
- cleanCookiesFromOpenTabsOnStartup: false
- cleanExpiredCookies: true
- siteDataEmptyOnEnable: true
- cacheCleanup: true
- indexedDBCleanup: true
- localStorageCleanup: true
- pluginDataCleanup: true
- serviceWorkersCleanup: true
- contextualIdentities: false
- contextualIdentitiesAutoRemove: true
- statLogging: true
- showNumOfCookiesInIcon: true
- keepDefaultIcon: false
- showNotificationAfterCleanup: true
- manualNotifications: true
- notificationOnScreen: 3
- enableNewVersionPopup: false
- sizePopup: 16
- sizeSetting: 16
- contextMenus: true
- debugMode: false

**Comment by kennethtran93** [comment] 2023-06-27 05:48
Duplicate of #983

**Closed as not planned by kennethtran93** 2023-06-27 05:48 UTC
Labels: duplicate
