### ISSUE TITLE
Container Tabs can't be disabled in FF63

### ISSUE THREAD

**Issue by githubuserlan** [mrdokenny/Cookie-AutoDelete#464] opened 2018-11-19 11:45 UTC
### Describe the Bug/Feature
Same as in issues #152, #245 and #334 Firefox automatically assigns this extension the rights to manage the container tabs option. I do not want to use container tabs, however the only way to avoid it currently is to disable or remove this extension. It would be great if you could work around 
this, as it really annoys me.

### Screenshot in which the bug can be seen
![autodelete](https://user-images.githubusercontent.com/16962079/48705117-a657f880-ebf8-11e8-81b7-734d067b54ae.jpg)
![options](https://user-images.githubusercontent.com/16962079/48705229-e61ee000-ebf8-11e8-8d08-acc36731bc80.jpg)

### Your settings 

- OS/version: Win 7 x64
- Browser/version: Firefox 63.0.3
- Cookie AutoDelete version: 2.2.0

**Comment by ke-d** [comment] 2018-12-30 02:06
Duplicate of #152.

Well I can't do anything until that underlying feature (https://bugzilla.mozilla.org/show_bug.cgi?id=1386673) is fixed in Firefox.

**Closed as completed by ke-d** 2018-12-30 02:06 UTC
Labels: duplicate
