### ISSUE TITLE
[Bug]  cache not clearing for youtube.com

### ISSUE THREAD

**Issue by garbb** [mrdokenny/Cookie-AutoDelete#1464] opened 2022-11-27 05:31 UTC
### Acknowledgements

- [x] I acknowledge that I have read the above items

### Describe the bug

Cache data for youtube.com is not removed when cache cleanup option is enabled and youtube.com is not in whitelist.

### To Reproduce

* Set Cookie-AutoDelete settings:
    * Enable automatic cleaning
    * Enable Cache Cleanup
    * No whitelist/greylist expressions for youtube.com

- Goto to edge://settings/siteData to view current site data for all sites.
    - Verify no items for youtube.com

Go to youtube.com in new tab

- refresh edge://settings/siteData to view current site data for all sites.
    - Verify items for youtube.com now exists
![image](https://user-images.githubusercontent.com/4453789/204120575-59f64409-0d9a-4f2b-b76c-f823b9e96e81.png)
![image](https://user-images.githubusercontent.com/4453789/204120615-b5e4b0db-85d8-4c50-8fbc-be8aeb6a2100.png)
![image](https://user-images.githubusercontent.com/4453789/204120623-4687925c-badd-4fde-86bf-ed81defbd43b.png)

- close youtube.com tab
- refresh edge://settings/siteData to view current site data for all sites.
    - see that most items for youtube.com have been removed, however cache item still remains
![image](https://user-images.githubusercontent.com/4453789/204120676-69fb9019-3119-4abf-980c-9c4b812a8086.png)
![image](https://user-images.githubusercontent.com/4453789/204120689-af2aad9f-6654-40a6-8f6f-321faf83d65e.png)
- CAD cleanup log says that it has invoked cache cleanup, however the cache data seems to still remain
![image](https://user-images.githubusercontent.com/4453789/204120784-3be9100c-0575-4442-bcb6-eeff9e348bcc.png)

### Expected Behavior

Expected cache data for youtube.com to be removed when cache cleanup option is enabled and youtube.com is not in whitelist.

### Screenshots

My CAD settings
![image](https://user-images.githubusercontent.com/4453789/204120834-5e464881-e6fb-472b-97ce-4fc004a6af8a.png)

cache storage from dev tools for youtube.com
![image](https://user-images.githubusercontent.com/4453789/204120957-9e056572-b5b5-4e04-be08-691c54e55f0a.png)
![image](https://user-images.githubusercontent.com/4453789/204120966-953875fa-8ccd-4ccd-9f2e-eb5500cd32db.png)

### System Info - Operating System (OS)

windows 10

### System Info - Browser Info

Edge 105.0.1343.50 (Official build) (64-bit)

### System Info - CookieAutoDelete Version

3.8.1

**Comment by kennethtran93** [comment] 2022-11-27 08:59
Duplicate of #845.  Cache and Cache Storage are separate items, according to chrome, which has not been implemented yet.

**Closed as not planned by kennethtran93** 2022-11-27 08:59 UTC
Labels: duplicate
