### ISSUE TITLE
[BUG] Clean's dropdown menu doesnt fit (v3.5.1)

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#1008] opened 2020-12-23 11:13 UTC
When I click to Clean's dropdown menu, it shows up but doesnt fit to the screen. I'm using 1920x1080 also I've just tried in different resolutions, and it still occurs.

![cookieautodelete](https://user-images.githubusercontent.com/75943932/102990743-f4066400-4528-11eb-9cbf-5176fc6cb111.gif)

I've uploaded the gif to imgur, as well: [https://imgur.com/a/7HQTxMC](https://imgur.com/a/7HQTxMC)

**Comment by kennethtran93** [comment] 2020-12-23 14:55
Duplicate of #803. Please ensure that you search existing issues beforehand. 

This only happens in certain situations including specific display resolutions. I don't think we had planned for the popup to be in the overflow menu which is more constrained on the width. Workaround is to change popup font size in case settings.

**Closed as completed by kennethtran93** 2020-12-23 14:55 UTC
Labels: duplicate

**Comment by ghost** [comment] 2020-12-23 18:34
Sorry couldn't catch that it's already exist. Btw, thanks for sharing the link.
