### ISSUE TITLE
WhiteList not working on Opera

### ISSUE THREAD

**Issue by skjerns** [mrdokenny/Cookie-AutoDelete#458] opened 2018-10-29 19:53 UTC
This looks like a great extension, however, the WhileList just gets ignored, leaving me with no cookies!

Any idea what's at fault here? Or does it just simply not work with Opera?

- OS/version: Win 10 64bit
- Browser/version: Opera 57.0.3098.20
- Cookie AutoDelete version: 2.2.0

**Comment by ke-d** [comment] 2018-11-12 04:50
Duplicate of #452

**Closed as completed by ke-d** 2018-11-12 04:50 UTC
Labels: duplicate
