### ISSUE TITLE
Make it compatible with first-party isolation

### ISSUE THREAD

**Issue by Homme-Nuage** [mrdokenny/Cookie-AutoDelete#266] opened 2017-11-22 10:23 UTC
First-party isolation is described [here](https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/)

It looks like a very useful feature, but there's a conflict with Cookie Autodelete which prevents it from deleting first-party cookies. 

Is it possible to fix this? 

My settings:

- OS/version: Windows 7 service pack 1
- Browser/version: Firefox 57
- Cookie AutoDelete version: 2.0.1

**Comment by solracsf** [comment] 2017-11-22 17:06
WebExtension API cookie (used by the extension) is **not** compatible with `privacy.firstparty.isolate`

**Comment by Homme-Nuage** [comment] 2017-11-22 17:17
Ok. It seems the problem comes from Firefox and will be fixed eventually.

**Comment by Omen-of-Peace** [comment] 2017-11-23 13:39
For reference:
Meta FPI bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1299996
Cookie add-ons bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1381197

(links provided by user Brainfart in the comments of the GHacks article)

**Comment by Homme-Nuage** [comment] 2017-11-23 13:44
Yeah, I had read his/her comment.

**Comment by solracsf** [comment] 2017-11-23 17:54
Should be ok in Firefox 58: https://hacks.mozilla.org/2017/11/new-in-firefox-58-developer-edition/

> Access brand new website privacy controls like first-party isolation and fingerprinting resistance, added as part of the ongoing Tor Uplift.

**Comment by Homme-Nuage** [comment] 2017-11-23 17:54
Nice.

**Comment by haarp** [comment] 2017-11-24 09:25
Seems to be a dupe of #75

**Comment by ke-d** [comment] 2017-12-06 00:13
Duplicate of #75

**Closed as completed by ke-d** 2017-12-06 00:13 UTC
Labels: duplicate
