### ISSUE TITLE
Auto Export / Synchronisation

### ISSUE THREAD

**Issue by jsahoka** [mrdokenny/Cookie-AutoDelete#496] opened 2019-02-06 16:49 UTC
Hi,
It would be very useful if we could setup CAD to automatically export upon setting change.
I use CAD on multiple computers and would like to only have to set changes once.

**Comment by kennethtran93** [comment] 2019-02-14 06:21
May be duplicate of #30, #493

**Comment by ke-d** [comment] 2019-02-16 05:06
Duplicate of #30

**Closed as completed by ke-d** 2019-02-16 05:06 UTC
Labels: duplicate
