### ISSUE TITLE
[Bug] Mozilla Firefox crashes after opening Cookie AutoDelete in overflow menu, Wayland

### ISSUE THREAD

**Issue by utaxiu** [mrdokenny/Cookie-AutoDelete#1407] opened 2022-06-11 13:25 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

After clicking on addon icon in hotbar Firefox completely crashes.

### To Reproduce

Simply click on "Cookie AutoDelete" addon icon in overflow menu.

### Expected Behavior

I wanted to check whether site I was visiting is whitelisted or not.

### Screenshots

Mozilla crash stats: [https://crash-stats.mozilla.org/report/index/823bf208-b189-4660-8850-bd8230220611](url)

### System Info - Operating System (OS)

Fedora 36, kernel 5.17.13, Wayland

### System Info - Browser Info

Firefox 101.0

### System Info - CookieAutoDelete Version

3.7.0

**Comment by kennethtran93** [comment] 2022-06-12 07:33
By 'hotbar', do you mean the toolbar or overflow menu?

From a brief glance at that crash report (whatever I can publicly see), it looks like you are currently using a wayland or something (I don't have linux installed on my current machine so I cannot fully help myself).

Maybe related to #1385, or its connected bug from that issue https://bugzilla.mozilla.org/show_bug.cgi?id=1771528 which seems to be marked as duplicate of this: https://bugzilla.mozilla.org/show_bug.cgi?id=1771104 which seems to hint an issue on the wayland / gtk / gnome area https://gitlab.gnome.org/GNOME/gtk/-/issues/4308.  Per the second bugzilla report, it may be fixed once Firefox 102 is released.

As far as I'm concerned, our extension should work cross-platform as we're primarily using the webextension API that is exposed through the browser side, alongside html, css, and javascript to stylize the popups.  I highly doubt that we could trigger a crash that would be due to the extension (rather if it was a crash it would be more likely aimed at how that browser implemented parts of the webextension API that has been exposed for us to call (like how the cache cleanup in Firefox seems to take a decent amount of time according to user reports).

**Comment by utaxiu** [comment] 2022-06-12 09:28
> By 'hotbar', do you mean the toolbar or overflow menu?

Overflow menu, sorry.

> From a brief glance at that crash report (whatever I can publicly see), it looks like you are currently using a wayland or something (I don't have linux installed on my current machine so I cannot fully help myself).

Yes, I am using Wayland.

> Maybe related to #1385, or its connected bug from that issue https://bugzilla.mozilla.org/show_bug.cgi?id=1771528 which seems to be marked as duplicate of this: https://bugzilla.mozilla.org/show_bug.cgi?id=1771104 which seems to hint an issue on the wayland / gtk / gnome area https://gitlab.gnome.org/GNOME/gtk/-/issues/4308. Per the second bugzilla report, it may be fixed once Firefox 102 is released.

Indeed. It looks like I have a same problem as #1385. Crash doesn't happen if I move the addon from overflow menu to toolbar.
Also other addons I am using do not crash Firefox (even though they are in overflow menu).

**Comment by kennethtran93** [comment] 2022-06-14 06:10
Let me know once Firefox 102 has been released, if this bug still persists.  Unfortunately as it is more localized to the linux-wayland variation, I won't be able to troubleshoot this at this time as I don't have a working linux machine on my machine at this time (I'm using Windows).

**Comment by kennethtran93** [comment] 2022-07-17 04:45
Looks like Firefox 102 has been released (currently 102.0.1).  Is this still an issue?

**Comment by utaxiu** [comment] 2022-07-17 08:18
I've been using the 102 version for some time now and it seems that the bug was fixed. I'm closing this issue 👍

**Closed as completed** 2022-07-17 08:18 UTC
Labels: duplicate, external, Firefox
