### ISSUE TITLE
Drop-down menu has disappeared

### ISSUE THREAD

**Issue by lgbaldoni** [mrdokenny/Cookie-AutoDelete#487] opened 2019-01-15 12:36 UTC
### Describe the Bug/Feature

Drop-down menu is a [blank square](https://user-images.githubusercontent.com/1450716/51180912-05b94880-18ca-11e9-87cf-68709611c446.jpg) after the 3.0.0 or the Firefox 60.4.0esr update.
(likely the former, but I'm not 100% sure).

All of the settings menus are also mangled and show this:
```
Error!

can't convert undefined to object t.default</</n<@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:20:3219 t.default</<@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:20:3191 t.default<@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:20:3169 di@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:36:61969 qi@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:36:78334 Ki@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:36:78711 Ao@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:36:85134 Oo@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:36:84514 Do@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:36:90725 Sn@moz-extension://bf8f76b3-3bb1-48c6-84fa-cdbc8d2cf498/bundles/common-popup-setting.bundle.js:36:30438 at line 20 
```

No output on console when clicking on the extension icon.

No idea how to reproduce it.

Using openSUSE Leap 15.0, Firefox 60.4.0esr and Cookie Autodelete 3.0.0.

**Comment by ke-d** [comment] 2019-01-15 16:51
Duplicate of #484

**Closed as completed by ke-d** 2019-01-15 16:51 UTC
Labels: duplicate
