### ISSUE TITLE
Greylist only works if notification is enabled

### ISSUE THREAD

**Issue by klui2k1** [mrdokenny/Cookie-AutoDelete#531] opened 2019-05-19 21:57 UTC
### Your settings 

- OS/version: Windows 7
- Browser/version: Firefox Nightly 68
- Cookie AutoDelete version: 3.0.2

I have been using CAD for about 6 months and I find if I don't enable notification, some--not all--cookies aren't autodeleted upon relaunch. But enabling notification does. I don't want the notifications and prefer everything to work in the background. How could I make CAD work in this way?

Checked Settings:
Enable automatic  cleaning, delay before cleaning 5 sec.
Enable cleanup on domain change
Enable cleanup log and counter
Show number of cookies for that domain
Show notification after cookie cleanup 1 seconds <<< -- this is the setting I have issues with
Clean cookies from open tabs on startup
Local storage cleanup (Firefox 58+)

My list of expressions has 3 white lists that keeps only cookies and 2 grey lists that doesn't keep storage or cookies. Before I had a \*.\* greylist that doesn't keep storage or cookies but I have replaced it with \*.\*.com, \*.\*.net, \*.\*.org with the same policies.

What am I doing wrong?

Thanks!

**Comment by kennethtran93** [comment] 2019-05-20 06:13
Remember that white list takes precedence. If you had disabled notification, would it show up in the logs area after a certain amount of time (say 5-10 seconds - you would need to refresh the logs page after that timeframe)?

**Comment by klui2k1** [comment] 2019-05-21 04:50
Thanks for the reply. The logs do say the cookies have been deleted.

I will monitor it some more for the next week or so but I just checked today and it appears the issue is now largely isolated to local storage. I believe it's related to how FF works with local storage but don't understand what is meant by "Firefox lumps IndexedDB and localstorage in that storage size count. CAD can remove localstorage per site but not IndexedDB per site." https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/512#issuecomment-482820132. I have my greylist set to not store any local data. And these other sites fall within my \*.\*.com rule.

**Comment by kennethtran93** [comment] 2019-05-21 05:36
So at this point it's a duplicate of #171 and #512.  See if you could understand a bit more after reading my comment https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/512#issuecomment-477875623

Or is there something else that is still not working properly if you disabled notifications?

**Closed as completed** 2019-06-11 18:41 UTC
Labels: duplicate
