### ISSUE TITLE
Feature Request:   Sync Between computers with firefox or chromes sync.   Streamline the creation of new expressions, fewer clicks for each new manual entry. 

### ISSUE THREAD

**Issue by Bigbillsd** [mrdokenny/Cookie-AutoDelete#329] opened 2018-01-19 15:51 UTC
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by ke-d** [comment] 2018-01-22 05:27
@Bigbillsd 

>Sync Between computers with firefox or chromes sync. 

Duplicate of #30 

> Streamline the creation of new expressions, fewer clicks for each new manual entry.

What do you mean by that cause I think it's pretty easy as you have you options:

1. Use the popup and click the + Greylist or + Whitelist
2. Add it manually in the List of Expression page by typing in the domain and clicking + Greylist or + Whitelist

**Comment by ke-d** [comment] 2018-02-09 02:19
Closing for inactivity.

**Closed as completed by ke-d** 2018-02-09 02:19 UTC
Labels: duplicate
