### ISSUE TITLE
Enhancement: Active cookie display

### ISSUE THREAD

**Issue by BillLee20018** [mrdokenny/Cookie-AutoDelete#366] opened 2018-03-01 17:16 UTC
### Describe the Bug/Feature
It would be helpful to have a small display that could be pinned to the desktop that displayed the active cookies. Much like what can be seen in the Preferences->Privacy->Show Cookies  display but separate from the Preferences display, and also one that would not only add new cookies as they are created and also remove them from the display when they are removed. (Perhaps someone has an Addon that would do this?)

### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by ke-d** [comment] 2018-03-15 16:31
Duplicate of #314

**Closed as completed by ke-d** 2018-03-15 16:31 UTC
Labels: duplicate
