### ISSUE TITLE
AutoDelete and manually Delete doesn't work correctly.

### ISSUE THREAD

**Issue by hightower5** [mrdokenny/Cookie-AutoDelete#541] opened 2019-06-19 10:47 UTC
AutoDelete and manually delete doesn't work correctly.

There are a lot of unwanted cookies in "Manage Cookies and Site Data".

Windows 10 x641903
Mozilla Firefox 67.02 x64
Cookie AutoDelete 3.02

The problem seems [Multi-Account Containers](https://support.mozilla.org/en-US/kb/containers) and Removing Cookies and Site Data confirmation.

![Removing Cookies and Site Data confirmation dialog](https://user-images.githubusercontent.com/18751660/59678393-97581980-91cc-11e9-8686-71513036400d.png)

_Originally posted by @hightower5 in https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/540#issuecomment-503045424_

**Comment by chiraag-nataraj** [comment] 2019-06-19 10:54
1. Does the Cookie AutoDelete log show that cookies were deleted?
2. I can't tell if those sites are using *storage* or if they're storing *cookies*. Both are shown in the same place, but there are some kinds of storage (such as indexedDb) which Cookie AutoDelete cannot yet clean (basically, there is no way for web extensions to access that storage).

I'm currently using Cookie AutoDelete with MultiAccount Containers and it works, so there's something else going on here.

**Comment by hightower5** [comment] 2019-06-19 11:17
>1. The Log shows deleted cookies.
>2. It is posible to delete these cookies in  "Manage Cookies and Site Data" per hand.

After some days I always find a lot of not deleted cookies.
e.g.
www.redit.com
www.youtube.com
www.google.com
serienjunkies.org /container
board.serienjunkies.org /container

**Comment by chiraag-nataraj** [comment] 2019-06-19 11:24
Okay, so you're saying that this is what is happening:

1. You enabled Auto-clean in Cookie AutoDelete (CAD)'s settings.
2. You did not whitelist any cookies from www.reddit.com.
3. You go to Reddit, log in, browse, whatever.
4. You close the tab.
5. CAD reports that it cleared the cookies.
6. You go to about:preferences#privacy
7. You still see reddit.com in that list.

If this is the case, can I please also get confirmation that it shows a non-zero number of *cookies*? Because it could be the case that there's website data that is stored (in localstorage or in other places). To see if this is the case, on about:preferences#privacy, click on "Manage Data". The first column is the site URL (www.reddit.com in this case) and the second column is the number of cookies. If that number is greater than 0, then that site is still storing cookies. Otherwise, it's storing other types of data (the "Storage" column), which is _different_.

**Comment by hightower5** [comment] 2019-06-19 12:00
Hello chiraag-nataraj,

all what you said above is correct. There are non-zero number of cookies from www.redit.com, 
www.youtube.com and www.google.com.

Info: Mozilla Firefox Chronik (Clear all history)

I often use deleting chronik. I have deactivated: Cookies, Site Preferences and Offline Website Data.

**Comment by chiraag-nataraj** [comment] 2019-06-19 12:15
So here's how it looks from my end.
Enabled Auto-clean, cleaning Localstorage, and cleaning on domain change:
![2019-06-19-120958_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59764496-6a1e7080-928b-11e9-8044-3a3fe1d621ce.png)
Did not whitelist any cookies from Reddit:
![2019-06-19-121016_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59764519-77d3f600-928b-11e9-8f42-24d23b146260.png)
Cookies from Reddit after opening the page (but before closing):
![2019-06-19-121101_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59764530-80c4c780-928b-11e9-806e-59b7234b651f.png)
Cookie AutoDelete shows that cookies were deleted:
![2019-06-19-121322_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59764616-afdb3900-928b-11e9-989a-b8806bdb5d48.png)
All cookies have been removed (there is a little bit of some kind of storage remaining):
![2019-06-19-121408_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59764674-c8e3ea00-928b-11e9-937d-9b798b610b91.png)
This is in a completely new Firefox profile with everything set to default (except installing Cookie AutoDelete, of course).

**Comment by hightower5** [comment] 2019-06-19 13:36
![Zero-Cookies](https://user-images.githubusercontent.com/18751660/59770162-d313e180-92a7-11e9-8a9c-ae2492aa3d9c.png)

It would be nice if Cookie AutoDelete could delete all these zero-cookies.

**Comment by chiraag-nataraj** [comment] 2019-06-19 13:46
Okay, so cookies *are* being deleted. For anything other than localstorage, Firefox (and Chrome?) doesn't provide the APIs to delete by hostname. There's nothing Cookie AutoDelete (or any other extension, for that matter) can do until those APIs are available to extension developers.

**Comment by kennethtran93** [comment] 2019-06-21 20:03
Thanks for the further clarifications. At this point I'm going to close this as duplicate of #512

**Closed as completed by kennethtran93** 2019-06-21 20:03 UTC
Labels: duplicate, browserbug/limitation
