### ISSUE TITLE
LocalStorage cleanup throwing errors

### ISSUE THREAD

**Issue by rpgdev** [mrdokenny/Cookie-AutoDelete#483] opened 2019-01-14 00:19 UTC
### Describe the Bug/Feature

I'm getting this message in a notification in the last couple of days: ''Type error for parameter options (Error processing hostnames.0: Error: Invalid hostname ) for browsingData.removeLocalStorage."

I don't want to disable local storage deletion if not necessary, what can I do?

### Screenshot in which the bug can be seen
<img width="303" alt="image" src="https://user-images.githubusercontent.com/20094474/51092620-bbbc4f80-176f-11e9-9b98-083f6a794ad4.png">

### Steps for anyone to reproduce the bug

It happens after closing all the tabs displaying the same site.

### Your settings 

- OS/version: Fedora 27
- Browser/version: Firefox 63.0 (64-bit)
- Cookie AutoDelete version: 3.0.0

**Comment by ke-d** [comment] 2019-01-14 01:34
Duplicate of #482 

It was already failing either way so no localstorage was being cleaned. But you can try the patched version in the last comment i posted in there.

**Closed as completed by ke-d** 2019-01-14 01:34 UTC
Labels: duplicate
