### ISSUE TITLE
Feature request: Whitelist single cookie instead of whole domain

### ISSUE THREAD

**Issue by Bernd95** [mrdokenny/Cookie-AutoDelete#257] opened 2017-11-19 13:52 UTC
I have switched over from CookieKeeper, because it does not work with Firefox 57 anymore. I have a feature request: I would like to whitelist a certain cookie for a domain/name combination, so I don't want to whitelist a whole domain, only one cookie. Example: I want to whitelist the cookie for the 2-factor-login on Amazon (named sid), but want to have all other Amazon cookies deleted. Similar for iCloud. Maybe you can integrate this in the current interface by adding a second box for the cookie name with the default *. Or you add a second possibility for whitelisting, where you can pick a certain cookie from the existing ones (as it was in CookieKeeper).
- OS/version: Windows 10
- Browser/version: Firefox 57
- Cookie AutoDelete version: 2.0.1

**Comment by madduck** [comment] 2017-11-20 21:35
I just came online to ask for exactly the same feature. Please. ;) </aol>

**Comment by LaurentGrenet** [comment] 2017-11-25 15:50
Yes, sure. Would be VERY VERY VERY useful !

**Comment by kah0922** [comment] 2017-11-25 18:59
Is it even possible for WebExtensions to clear single cookies?

**Comment by ke-d** [comment] 2017-12-28 21:29
Duplicate of #68

**Closed as completed by ke-d** 2017-12-28 21:29 UTC
Labels: duplicate
