### ISSUE TITLE
[Bug]  i can't add extension to chromium 

### ISSUE THREAD

**Issue by hxvy0** [mrdokenny/Cookie-AutoDelete#1301] opened 2022-01-19 08:36 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

İ can't install the extension

### To Reproduce

...

### Expected Behavior

'Variable $matchedExpression$ used but not defined.'

### Screenshots

![image](https://user-images.githubusercontent.com/85783692/150093458-ab737f83-5285-45ad-8c42-83ad78a4a154.png)

### System Info - Operating System (OS)

Windows 11 Pro

### System Info - Browser Info

Opera GX 96 on Windows 11

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

LoL fix that

**Comment by kennethtran93** [comment] 2022-01-25 20:45
Duplicate of #1299

**Closed as completed by kennethtran93** 2022-01-25 20:45 UTC
Labels: duplicate
