### ISSUE TITLE
[Bug]  Crash on firefox wayland

### ISSUE THREAD

**Issue by Mrjelly13** [mrdokenny/Cookie-AutoDelete#1385] opened 2022-05-09 01:51 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

If the extension is pinned to the overflow menu and opened firefox crashes. This does not happen if not pinned to the overflow menu. This only happens when using wayland. In X11 it does not crash. This does not happen with any other extension

### To Reproduce

1. Run firefox under wayland
2. Pin extension to overflow menu
3. Try to open extension

### Expected Behavior

Extension opens menu and you can interact with it

### Screenshots

https://user-images.githubusercontent.com/18286513/167326560-5df18bec-d546-4365-ab64-6e405ccdfdb9.mp4

### System Info - Operating System (OS)

Arch Linux

### System Info - Browser Info

Firefox Stable 100.0

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

I have tried with all other extensions disabled. I also tried this on Ubuntu 22.04 under wayland and there was no issue.

**Comment by Mrjelly13** [comment] 2022-05-09 01:54
Errors thrown wen crashed:

```Gdk:ERROR:../gtk/gdk/wayland/gdkwindow-wayland.c:2231:rect_anchor_to_anchor: code should not be reached
Bail out! Gdk:ERROR:../gtk/gdk/wayland/gdkwindow-wayland.c:2231:rect_anchor_to_anchor: code should not be reached
Redirecting call to abort() to mozalloc_abort

ExceptionHandler::GenerateDump cloned child 311710
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.```

**Comment by kennethtran93** [comment] 2022-05-09 04:14
I don't know if this is a bug on our end, on Firefox's end, or on Wayland's end.  Either way, this seems like a specific scenario so far.

Also, in the screenshot you attached a 5 second video, but I don't see the issue at hand.

According to your comment above, it may be a wayland issue...or the communication between wayland/gdk/firefox...

Unfortunately I don't have any linux OS on hand at this time for testing this issue out.

**Comment by Mrjelly13** [comment] 2022-05-09 13:36
I realize that this is probably a specific issue and that opening this was a long shot. The video shows me trying to open the extension and Firefox crashing. I'm not sure why that isn't visible.

On May 9, 2022, 00:14, at 00:14, Kenneth T ***@***.***> wrote:
>I don't know if this is a bug on our end, on Firefox's end, or on
>Wayland's end.  Either way, this seems like a specific scenario so far.
>
>Also, in the screenshot you attached a 5 second video, but I don't see
>the issue at hand.
>
>Unfortunately I don't have any linux OS on hand at this time for
>testing this issue out.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1385#issuecomment-1120621559
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by kennethtran93** [comment] 2022-05-11 04:58
> I realize that this is probably a specific issue and that opening this was a long shot. The video shows me trying to open the extension and Firefox crashing. I'm not sure why that isn't visible.
> On May 9, 2022, 00:14, at 00:14, Kenneth T ***@***.***> wrote: I don't know if this is a bug on our end, on Firefox's end, or on Wayland's end. Either way, this seems like a specific scenario so far. Also, in the screenshot you attached a 5 second video, but I don't see the issue at hand. Unfortunately I don't have any linux OS on hand at this time for testing this issue out. -- Reply to this email directly or view it on GitHub: [#1385 (comment)](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1385#issuecomment-1120621559) You are receiving this because you authored the thread. Message ID:
> ***@***.***>

Try another screen recorder app if possible - if you were using a native/pre-installed app that is.  Then again, it probably would not help here at all.  Did you try bugzilla (firefox bug reporting system) as well as whatever wayland is using as their bug reporting system?

**Comment by 1player** [comment] 2022-05-15 08:35
Same issue here, Firefox 100, Fedora 36 GNOME on Wayland. Steps to reproduce:

1. Pin Cookie Autodelete to the overflow menu
2. Open the overflow menu and choose "Cookie Autodelete"

Can't reproduce if the extension hasn't been pinned.

**Comment by pizzadude** [comment] 2022-05-27 08:21
Same here, Fedora 36 KDE wayland. But this should be reported to Mozilla's bugtracker.

**Comment by pizzadude** [comment] 2022-05-27 18:11
I opened a bug report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1771528

**Comment by kennethtran93** [comment] 2022-06-02 07:32
Following the bug report, it does seem to be an issue with wayland/firefox in 100 and 101, and should be fixed in 102.  As this is an external issue, I will now be closing this.

**Closed as completed by kennethtran93** 2022-06-02 07:32 UTC
Labels: external, Firefox
