### ISSUE TITLE
[FEATURE REQUEST]  Blacklist: ban a listed (sub-)domain from setting cookies, or delete them at the earliest convenience.

### ISSUE THREAD

**Issue by BoboSims** [mrdokenny/Cookie-AutoDelete#710] opened 2020-05-04 19:26 UTC
I would like to have a Blacklist.

My idea of a Blacklist is a list where each rule defines a (sub-)domain that is not allowed to set **ANY** cookies. Alternatively, **ALL** cookies set by the (sub-)domain would be deleted at the earliest convenience... being at the next cleanup interval.

**Comment by kennethtran93** [comment] 2020-05-04 20:35
Possible duplicate of #134, #549.

Blacklist would be cleared at earliest convenience, not preventing cookie from being set at first.

**Closed as completed by kennethtran93** 2020-05-04 20:35 UTC
Labels: Feature Request

**Comment by BoboSims** [comment] 2020-05-04 20:45
Sir, you confuse me! Why would the blacklist itself be cleared? It's just a list of rules, following the same principles as the White- and Greylist. The idea was to clear the *cookies*, not the list.
But I'll look at the mentioned issues, see what I can salvage there.

**Comment by kennethtran93** [comment] 2020-05-04 20:49
My apologies - when I meant 'blacklist would be cleared' I meant the blacklisted domains and/or cookies checked in that domain would be cleared at earliest convenience.

**Comment by BoboSims** [comment] 2020-05-04 20:56
Precisely **that** is exactly the point! If the extension cannot prevent cookies from being created, it should clear them ASAP. Which is, as we both agree, at the earliest convenience. Either way, the cookie would no longer exist, which is what I hoped to achieve!

By the way, I looked at #549, and do not see any similarity there. But I could be missing something.

**Comment by kennethtran93** [comment] 2020-05-04 21:04
549 is almost the same where the blacklist would clear cookies from domains listed, and have `*` on the whitelist to keep the rest.  could be just my current interpretation of course.

**Comment by BoboSims** [comment] 2020-05-04 21:12
Woah! That's stretching it. I had not interpreted it that way at all.
But then, I would never even **consider** putting * on my Whitelist.
There are domains from which I accept some subdomains but not others; there are domains from which I accept everything; and there are domains that I don't even mention, because their cookies are acceptable as long as I am there, but can be deleted when I'm done with the domain.
The blacklist would be for cookies that I absolutely do NOT want at all.
