### ISSUE TITLE
[BUG] [Firefox Containers] "Automatic cleaning" triggers only when site's tabs are closed in all containers

### ISSUE THREAD

**Issue by wrkq** [mrdokenny/Cookie-AutoDelete#716] opened 2020-05-06 22:24 UTC
**Describe the bug**

The "Enable automatic cleaning with delay of [x] seconds" main feature activates when all tabs using a site are closed.

Unfortunately, this literally means "all tabs", not "all tabs within this container".

This results in cookies for sites that are visited in more than one container not being cleaned properly.

**Steps to reproduce**

CAD Settings:
* Enable Automatic Cleaning? Yes
* Delay Before Cleaning? 15 seconds (default)

Firefox containers:
* Default container / no container
* * CAD Expressions: none, clean everything
* Container "Test"
* * CAD Expressions: whitelist for *.github.com

Test 1:

1. Open tab in container "Test". Log in to Github in this tab.
2. Close all tabs of container "Test".
3. Wait >15 seconds, refresh CAD log. There should be no cleanup entry for github.
4. Open new tab in container "Test", navigate to Github, confirm you are still logged in.

**OK**

Test 2:

1. Close all tabs of container "Test".
2. Open tab in default container. Log in to Github in this tab.
3. Close all default continer tabs.
4. Wait >15 seconds, refresh CAD log. Cleanup entry for github in default container should appear.
5. Open new tab in default container, navigate to Github, confirm you are NOT logged in.

**OK**

Test 3:

1. Log in to github again in the default container. Leave the tab open for now.
2. Open new tab in container "Test". Navigate to Github. Leave the tab open.
(You should still be logged in due to whitelist; that's probably not relevant to this bug but let's make note of that).
3. Close all github tabs in default container, leave github tabs in container "Test" open.
4. Wait >15 seconds, refresh CAD log. There should be no cleanup entry for github.
5. Open new tab in default container, navigate to Github, confirm you are still logged in.
6. Close all github tabs, both in default container and in "Test" container.
7. Wait >15 seconds, refresh CAD log. Cleanup entry for github in default container should appear.
8. Open new tab in default container, navigate to Github, confirm you are NOT logged in.

**BUG**

**Expected behavior**
When all tabs for a site are closed in Container 1, its cookies should be cleaned inside Container 1 following the auto-clean timer and whitelist rules set up.
Existence of open tabs for the same site in container 2, 3, or 75 - other identities - should be irrelevant.
After all the white/grey list is per-container.

**Observed behavior**
The auto-clean task kicks off only when all tabs for a site are closed, globally in the browser, across all containers.
The cookies for the site are then cleaned or preserved in accordance to each container's whitelist.

**System Info**

 - Windows 10 Pro 1909
 - Firefox 76.0
 - Multi-Account-Containers 6.2.5
 - Cookie AutoDelete 3.2.0

**Comment by kennethtran93** [comment] 2020-05-08 02:54
I think somebody else may have already reported this issue but thanks for the detailed steps.

**Comment by kennethtran93** [comment] 2020-05-08 03:36
Duplicate of #262.  It's on my radar.

**Comment by wrkq** [comment] 2020-05-08 20:09
Ah shame. I did browse the open issues before reporting but apparently not thoroughly enough. Apologies.

**Closed as completed** 2020-05-24 16:05 UTC
Labels: bug, duplicate, good first issue

**Comment by kennethtran93** [comment] 2020-06-05 20:02
If you're up for testing, head on over to #753 to grab the dev files.
