### ISSUE TITLE
Protecting individual Cookies

### ISSUE THREAD

**Issue by Joel889** [mrdokenny/Cookie-AutoDelete#168] opened 2017-10-05 17:42 UTC
### Describe the Feature
Provide expert option to drill down on a whitelisted domain's cookies and select which specific cookies to keep (as opposed to keeping all the domain's cookies).
CookieCuller  (https://addons.mozilla.org/en-US/firefox/addon/cookieculler/) and CookieKeeper (https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper/) offer that functionality, but they won't work past FF56.

Thank you

**Comment by ke-d** [comment] 2017-10-05 18:12
Duplicate of #68

**Closed as completed by ke-d** 2017-10-05 18:12 UTC
Labels: duplicate
