### ISSUE TITLE
[Feature Request] Auto Remove Expired Cookies

### ISSUE THREAD

**Issue by zero77** [mrdokenny/Cookie-AutoDelete#426] opened 2018-07-31 12:33 UTC
Can you add the option to automatically remove cookies once they expire even if they are white or grey, so that there isn’t a build-up of old expired cookies.
Thanks

**Comment by VladV2** [comment] 2019-01-02 07:52
Please keep in mind the difference!
1. delete data older than N years
2. delete data older than M months for died sites, absent in DNS

**Comment by BoboSims** [comment] 2020-05-04 17:59
I would even suggest to remove ALL cookies - regardless of domain - for which the expiry date lies in the past, or which have been set to expire at the end of the session.

**Comment by kennethtran93** [comment] 2020-05-04 18:11
browser.cookies.getAll (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll) does not return expired cookies.  
Session cookies are usually cleared by firefox on browser restart (may not be the case if you have session restore active).

Aside from that it would be on #707's suggestion that the extension keeps track of ALL cookies that gets created and attempts to clean them after x days as a global setting.

I'm going to close this in favor of the referenced issue above.

**Comment by BoboSims** [comment] 2020-05-04 18:23
OK, as you wish. But let me ask you this: are you suggesting that it is impossible to find expired cookies as well as cookies set to expire at the end of the session? Because that would imply that the add-on named "Cookie Manager" performs black magic.

**Comment by kennethtran93** [comment] 2020-05-04 20:04
...This is what I get for taking the documentation as face value.

https://bugzilla.mozilla.org/show_bug.cgi?id=1388873 appears to include expired cookies.  I'll look into removing those soon!

Thanks for the fresh pair of eyes and brain!

**Comment by BoboSims** [comment] 2020-05-04 20:13
Hehehe, I apologize for having to do this to you.
Don't worry about it too much. We all overlook things occasionally, because we're only human.
I truly appreciate you for being big enough to acknowledge that, AND for reconsidering the issue.

**Comment by kennethtran93** [comment] 2020-05-22 06:14
I'm going to close this issue as duplicate of #344 as it relates to the exact same function to be implemented.

**Closed as completed** 2020-05-22 06:15 UTC
Labels: duplicate, enhancement
