### ISSUE TITLE
whitelist option for wildcard domains

### ISSUE THREAD

**Issue by gbjbaanb** [mrdokenny/Cookie-AutoDelete#162] opened 2017-09-27 14:27 UTC
The menu has an option to whitelist a domain, but this adds the entire domain to the whitelist when many sites use subdomains. An option to add a wildcard for the current domain would be awesome - so imagine a site, say cookie.com that had its user profiles in my.cookie.com or its social side in profile.cookie.com. The current menu will whitelist the main site, and delete cookies for the sub-site which is not ideal and will fool many people who assume that whitelisting a site keeps all cookies for it only to find half the functionality gets deleted.

A real example is the Guardian newspaper site, the main site is theguardian.com, the commenting system is profile.theguardian.com

**Comment by ke-d** [comment] 2017-09-27 14:38
That feature is already in 2.0.0 which is in beta now. Duplicate of #156

**Closed as completed by ke-d** 2017-09-27 14:38 UTC
Labels: duplicate
