### ISSUE TITLE
Clear cookies (except of opened tabs) not working

### ISSUE THREAD

**Issue by Symbai** [mrdokenny/Cookie-AutoDelete#136] opened 2017-09-04 17:32 UTC
### Describe the Bug/Feature

If you click clear cookies and ignore opened tabs, it will just clear all cookies except your whitelist (but includes opened tabs).

### Steps for anyone to reproduce the bug

Viist any site which is not whitelisted, keep that tab opened. Press context menu item

### Your settings 

[X] Clear cookies on tab close
[ ] Active mode

- OS/version: Windows 8.1 64bit
- Browser/version:  FF 55.0.3
- Cookie AutoDelete version: 1.4.3

**Comment by mrdokenny** [comment] 2017-09-04 17:35
You mean Cookie Cleanup (Ignore Open Tabs)? That's a feature/expected behavior.

Please read the description of the addon page before posting an issue 

Cookie Cleanup: This is basically a quick way of activating the Cookie Cleanup on demand. This looks at all your cookies and deletes them if they are not in any Open Tabs or the WhiteList.
Cookie Cleanup (Ignore Open Tabs): Same thing as Cookie Cleanup except that it only deletes cookies only if they are not in the WhiteList. Open tabs are not taken into consideration.
Clear All Cookies for This Domain: Easy way to delete all cookies for one particular domain that you are on.

**Comment by Symbai** [comment] 2017-09-04 17:46
Incredibly confusing name style. And by the way it works it's far from behing an alternative to self destructing cookie.

But you are right I should have read the description first, I would still recommend you changing the labels as this is definitely not what many people would understand at first.

**Comment by mrdokenny** [comment] 2017-09-04 17:52
SDC doesn't have a 'Cookie Cleanup (Ignore Open Tabs)'

I find this feature useful since if you have long lasting tabs that you keep open, you can clear those cookies rather than closing all of them (as long as they are not on the whitelist).

For example, if you pinned `calendar.google.com`, since `google.com` is the base domain, any other google cookie will not be deleted as long as `calendar.google.com` tab is pinned and open. 'Cookie Cleanup (Ignore Open Tabs)' goes around this and deletes all other google cookies even when `calendar.google.com` is open.

**Closed by mrdokenny** 2017-09-04 17:52 UTC

**Comment by doodhout** [comment] 2017-09-06 08:50
You can rename those labels to 'Cookie Cleanup (Excluding Open Tabs)' and 'Cookie Cleanup (Including Open Tabs)', because the term Ignore in one of the current labels means... what? Will the act of Cleaning Cookies disregard open tabs (~keeping their cookies in spite of them not being whitelisted), or will it disregard the fact that it should disregard open tabs (~destroy their cookies despite of the tabs being open)?

I'm with Symbai on this one, slightly confusing.
