### ISSUE TITLE
QUESTION: Can I whitelist an individual cookie?

### ISSUE THREAD

**Issue by storyjesse** [mrdokenny/Cookie-AutoDelete#448] opened 2018-10-11 13:24 UTC
### JUST A SIMPLE QUESTION:

Can this extension whitelist an individual cookie. e.g. I'd like to whitelist the user agent cookie for Etsy.com and other sites so that I don't get security notifications every time I login. But I still want to automatically delete all the other cookies from these sites. Is this possible?

![screenshot from 2018-10-11 21-22-13](https://user-images.githubusercontent.com/2957877/46807140-dad7c980-cd9b-11e8-9b01-a08b18f889b4.png)

**Comment by ke-d** [comment] 2018-11-12 05:01
Duplicate of #68

**Closed as completed by ke-d** 2018-11-12 05:01 UTC
Labels: duplicate
