### ISSUE TITLE
Can't access settings in Firefox on Android

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#192] opened 2017-10-16 13:31 UTC
### Describe the Bug/Feature

I can't open the pop-up menu (or any configuration menu) from the mobile version. I can only find a button named "Cookie AutoDelete" from the top-down menu panel that appears from clicking the 3 dots on top right of the monitor.
If I click that button, nothing at all happens

### Screenshot in which the bug can be seen

Does not apply

### Steps for anyone to reproduce the bug

Clicking the button does nothing

### Your settings 

I suppose the setting of Cookie AutoDelete are out-of-the-box since i wasn't able to access it.
Firefox settings are the usual settings. Tried to change anything ralted to this issue and did nothing. I can test any suggestion.

- OS/version: Android 6.0.1
- Browser/version: 56.0
- Cookie AutoDelete version: 2.0.0

**Comment by ke-d** [comment] 2017-10-16 14:34
Duplicate of #12

**Closed as completed by ke-d** 2017-10-16 14:34 UTC
Labels: duplicate

**Comment by ke-d** [comment] 2017-10-16 14:35
The popup only works on FF57 on Android.
