### ISSUE TITLE
Blacklist Only?

### ISSUE THREAD

**Issue by kmand** [mrdokenny/Cookie-AutoDelete#423] opened 2018-07-21 17:15 UTC
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by kmand** [comment] 2018-07-21 17:16
I am probably off base here. What I really want is just a blacklist of sites I want  to have cookies autodeleted. Is tjhis the wrong extnesion?

**Comment by kennethtran93** [comment] 2018-08-02 03:07
Normally people want to delete unwanted cookies, especially from (unknowing) third-party cookies and whatnot,.  Try another extension if blacklisting is what you want.

**Comment by ke-d** [comment] 2018-09-04 15:43
Duplicate of https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/134

**Closed as completed by ke-d** 2018-09-04 15:43 UTC
Labels: duplicate
