### ISSUE TITLE
From the open Tab not all "Cookies" will be deleted when Firefox is closed

### ISSUE THREAD

**Issue by bobdig** [mrdokenny/Cookie-AutoDelete#489] opened 2019-01-22 14:44 UTC
### Describe the Bug/Feature
From the open tab not all "cookies" will be deleted when Firefox is closed

### Screenshot in which the bug can be seen
[![Bild 1x2j70.jpg auf abload.de](https://abload.de/thumb/1x2j70.jpg)](http://abload.de/image.php?img=1x2j70.jpg) [![Bild 2g6k5i.jpg auf abload.de](https://abload.de/thumb/2g6k5i.jpg)](http://abload.de/image.php?img=2g6k5i.jpg) [![Bild 384k7w.jpg auf abload.de](https://abload.de/thumb/384k7w.jpg)](http://abload.de/image.php?img=384k7w.jpg) [![Bild 4y9k1b.png auf abload.de](https://abload.de/thumb/4y9k1b.png)](http://abload.de/image.php?img=4y9k1b.png) 

### Steps for anyone to reproduce the bug
On first picture you can see the different handling for e.g. on check24.de, on the upper one ff was closed with an open tab from check24.de. I did a search for a new power-company.

You can circumvent this by [setting all cookies to be deleted on browser restart rather than on tab close](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#how-do-i-set-all-cookies-to-be-deleted-on-browser-restart-rather-than-on-tab-close), but I don't think this is the intended behavior.  

- OS/version: Win10 1809
- Browser/version: FF 64.0.2
- Cookie AutoDelete version: 3.0.1

**Comment by kennethtran93** [comment] 2019-04-21 07:45
I believe scripts don't generally run if Firefox is being closed (Firefox program closing is NOT tab close), hence only upon startup will they be removed.  

Tab close actions only works while firefox is still running, not when you're closing firefox.

With that said this webextension is working as it is intended for and should be closed as it isn't an issue, unless you're referring to something else.

**Comment by kennethtran93** [comment] 2019-06-11 19:13
Keep in mind that sites will not set cookies all at once - it would depend on what you were doing on that site before the extension took over.
Closing as this is the expected behavior for the settings given.  Feel free to comment with more detailed steps to validate that this should be a bug.

**Closed as completed by kennethtran93** 2019-06-11 19:13 UTC
Labels: not a bug / expected behavior
