### ISSUE TITLE
FEATUERE REQUEST Clearing all web site data

### ISSUE THREAD

**Issue by mitvitaminen** [mrdokenny/Cookie-AutoDelete#150] opened 2017-09-13 23:12 UTC
Hi,
it would be nice if you could clear the website settings + cache for the site of the deleted cookie as well. Thank you
Chris

**Comment by ke-d** [comment] 2017-09-13 23:38
Duplicate of #44 , but mostly waiting on APIs that allow me to delete website data by `hostname`

**Closed as completed by ke-d** 2017-09-13 23:38 UTC
Labels: duplicate
