### ISSUE TITLE
[BUG]  Ipv6 Hostname error

### ISSUE THREAD

**Issue by n00b42** [mrdokenny/Cookie-AutoDelete#1066] opened 2021-03-03 00:06 UTC
**Describe the bug** 

Closed a page that I opened using an IPv6 address: "http://[fd11:34f:b25c::5d2]/" (Internal device not globally reachable)

Since then I receive the following message popups every now and then (I assume when cleanup starts)

"Type error for parameter options (Error processing hostnames.5: Error: Invalid hostname .[fd11:34f:b25c::5d2]) for browsingData.remove."

**To Reproduce** 

I assume it should be reproduible by
1. Open a page using an Ipv6 address
2. Close it
3. Get error messages

**Expected Behavior** 

Cleanup should work even if an Ipv6 address was used.

**Your System Info** 

- OS: Windows 10
- Browser Info: Firefox 87.0b4
- CookieAutoDelete Version: 3.6.0

**Comment by kennethtran93** [comment] 2021-03-03 05:28
Duplicate of #983

**Closed as completed by kennethtran93** 2021-03-03 05:28 UTC
Labels: duplicate

**Comment by n00b42** [comment] 2021-03-03 09:47
Sorry, was searching the issues and still wondering why I did not found the other one.
