### ISSUE TITLE
Change delay before cleaning resolution from minutes to seconds

### ISSUE THREAD

**Issue by thomasrussellmurphy** [mrdokenny/Cookie-AutoDelete#265] opened 2017-11-22 03:09 UTC
### Change delay before cleaning resolution from minutes to seconds
The current implementation provides:
>Enable Automatic Cleaning? Delay Before Cleaning: `integer number entry` Minute(s)

This results in a smallest setting resolution of 1 minute. The UI currently shows a red outline if you try to enter a decimal value (e.g. `1.5`, `0.1`). Can this setting be changed to use a resolution of seconds or settable seconds/minutes?

- OS/version: macOS 10.12.6
- Browser/version: FF 56.0.2
- Cookie AutoDelete version: 2.0.1

**Comment by TheRealestMVP** [comment] 2017-11-23 08:37
According to the [FAQ](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues), this is intentional:

> Why does the "delay before cleaning" default to 1 minute?
> - Consistency. Chrome's Alarm API fires off only after a minute.
> - Also, don't want to provide different defaults for different browsers since it is impossible since I have to test for each browser to see if the defaults stick (browser detection is not foolproof).

**Comment by thomasrussellmurphy** [comment] 2017-11-23 15:13
So the _implied_ answer from the FAQ is `Chrome only allows a resolution of 1 minute` and, for consistence in the code base, allowing smaller resolution isn't supported?

I'm perfectly fine with the default. The default could be 30 minutes for all I care. I'm just after an improved (personal) UX in wanting a smaller unit of resolution available.

**Comment by practik** [comment] 2017-11-29 20:46
No, smaller resolutions are supported. I have my delay set to 0.1 minute and my cookies get deleted after six seconds. Just ignore the red outline.

**Comment by thomasrussellmurphy** [comment] 2017-11-30 00:47
Hmm. Indeed it seems that in FireFox 56.0.2 the delay can be set to fractional minutes and it works. This may just be a UI correction, then. It would be valuable to better understand what the current practical limitations are so that the UI might be able to be improved.

**Comment by ke-d** [comment] 2017-12-06 00:35
> This may just be a UI correction, then. It would be valuable to better understand what the current practical limitations are so that the UI might be able to be improved.

Yes, that was a problem that was caused by moving to the newest version of bootstrap in #180.

**Comment by ke-d** [comment] 2017-12-29 06:55
I changed the delay from minutes to seconds in 5fd26736cd017a215295bc09cc497a7d70fd05e9 because I figured out a workaround for Chrome, which makes fixing the red outline unnecessary.

**Comment by ke-d** [comment] 2018-01-11 16:30
Closing since 2.1.0 is out.

**Closed as completed by ke-d** 2018-01-11 16:30 UTC
Labels: bug

**Comment by thomasrussellmurphy** [comment] 2018-01-12 00:20
Reverted title of issue for search accuracy and because there's still a red outline when a decimal value is entered. Now that outline reasonably indicates a non-optimal value entered in the field.
