### ISSUE TITLE
Site entry is not removed from Firefox Manage Cookies list when cookies are removed.

### ISSUE THREAD

**Issue by BigFriendlyGit** [mrdokenny/Cookie-AutoDelete#491] opened 2019-01-24 15:35 UTC
### Describe the Bug/Feature

Site entries in the Firefox 'Manage Cookies and Site Data' settings screen do not get auto removed when cookies are auto deleted.
For example, say you visit 'www.example.com' and the browser accepts some cookies then they will show up in the Firefox 'Manage Cookies and Site Data' settings with a Site of 'www.example.com' and a Cookies entry of (say) '5' as expected.  When you close all Firefox tabs for 'www.example.com' (or close and reopen Firefox) then the cookies are deleted as expected, however the Site entry in the 'Firefox Manage Cookies and Site Data' settings is not removed and neither is the Storage value set back to zero.  The Cookies value changes from say '5' to '0' but 'www.example.com' remains.  This may be by design however I feel it would be useful to also have the Site entry removed from the list.  Hope this makes sense.

### Steps for anyone to reproduce the bug

Ensure Firefox is set to accept cookies.
Visit a website that is not white or grey listed in the add-on.
Open Firefox Preferences > Privacy and Security > Cookies and Site Data > Manage Data and verify that a 'Site' entry is created in the 'Manage Cookies and Site Data' settings in the browser.
Verify that the 'Cookies' column has a non zero value.
Verify that the Last Used entry is current.
Close the 'Manage Cookies and Site Data'  settings page.
Close the Firefox Preferences page.
Close the webpage of the site you are testing with (so the cookies get deleted).
Reopen the Firefox Preferences Page and check the  'Manage Cookies and Site Data' settings again to verify if the Site entry remains even though the Cookies value has been set to zero.

### Your settings 

- OS/version: MacOS Mojave 10.14
- Browser/version: Firefox 64.0.2 (64 bit)
- Cookie AutoDelete version: 3.0.1

**Comment by ke-d** [comment] 2019-02-16 05:09
Duplicate of #171

**Closed as completed by ke-d** 2019-02-16 05:09 UTC
Labels: duplicate
