### ISSUE TITLE
Better Utilization of Firefox's Container Implementation

### ISSUE THREAD

**Issue by babyRigpa** [mrdokenny/Cookie-AutoDelete#378] opened 2018-03-30 19:13 UTC
I'm currently using Firefox's container implementation. I find that these two addons aren't logically coherent  even though there are no technical problems on my end, given the expected behavior. 

My issue is that the extension's operation is very crude given the amount of specificity to our cookies that containers grant us. It seems like the logical extension of this plugin's functionality would be to be able to distinguish between different container groups' cookies.

I have a use case in mind and I will use google as the example. By default I would want my google cookies removed after I have closed every last of the tabs that use the google cookies, in my "default" container. (I won't necessarily be logged into any google account in this container.) Then I could have a container named "google" for which cookies would never be removed, and I would use that container to use the google services, but once I'm in any other container, the google's identifying cookies will be isolated, therefore invisible.

At the moment, the whitelist is global, therefore if I want the cookies to be removed for a given domain, the containerization becomes irrelevant. I think this implementation would be very useful to many people, and given a, hopefully, good API on the part of Mozilla, should not be very difficult to implement, I imagine.

**Comment by ke-d** [comment] 2018-04-18 01:10
You mean the `Enable Support for Firefox's Container Tabs` setting?

**Comment by femtoRigpa** [comment] 2018-05-03 19:44
Well, I have that setting enable, but can't tell that there is any difference in behavior at all. Doesn't help that I couldn't easily find exactly what is the expected behavior with that option ticked.

The use case I outlined doesn't work with google nor facebook. I don't know if you tested it but here are the steps of the expected behavior:

1. Open a fresh browser w/o cookies/history/etc. Make sure container tabs and CAD are installed and enabled.
2. Open facebook.com in a default container. Log in.
3. Close the tab and observe that after the default 15secs, the cookies are cleared.
4. Now with all tabs closed, open 2 more for facebook.com, however one in container A and the other in B. Log in for both.
5. Close the tab in container B and observe that CAD doesn't clear any cookies after any amount of time. Check this by opening facebook in container B and be greeted with your profile.
6. Close the tab in container A and observe that CAD clears all cookies for those two tabs. Facebook is now reset for both Containers A & B.

Expected behavior: in step 5, after closing the only facebook tab in container B, I expect that CAD will clear cookies after 15 secs and if I open another facebook tab in container B, no information from previous session would be there and I would need to log in again. At the same time, container A and its tab should not be affected at all, and if I whitelist facebook from A's container, then it should be able to reuse the previous sessions independent from any behavior in other containers.

CAD should just treat every container and the tabs opened therein as a separate "browser" and let them be completely independent, even if it's the same facebook.com across those containers. 

I thought I explained myself sufficiently in the OP, but here it is again in a bit more detail. If you still don't understand what I'm trying to explicate, be a bit more specific in your questions please. Thank you for making this extension, it is great other than this one niche(?) behavior that I'm trying to explain.

**Comment by ke-d** [comment] 2018-05-09 06:09
Ah I think this is a duplicate of #262 . Short answer is that it's not trivial to implement currently.

**Closed as completed by ke-d** 2018-05-09 06:09 UTC
Labels: duplicate
