### ISSUE TITLE
are these messages from coockie-autodelete ? 

### ISSUE THREAD

**Issue by rezad1393** [mrdokenny/Cookie-AutoDelete#158] opened 2017-09-25 07:55 UTC
### Describe the Bug/Feature

- OS/version: archlinux 64x
- Browser/version: 55.0.3
- Cookie AutoDelete version: 1.4.4

when I start firefox from terminal I get a lot of these messages
`Extension error: TypeError: whiteList is undefined moz-extension://699b7c0f-6b46-4858-be77-99beae7e787d/background-webpack.js 838
[[Exception stack
checkIfProtected@moz-extension://699b7c0f-6b46-4858-be77-99beae7e787d/background-webpack.js:838:1
exposedFunctions</<@moz-extension://699b7c0f-6b46-4858-be77-99beae7e787d/background-webpack.js:852:3
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:54:129
runSafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:176:38
receiveMessage@resource://gre/modules/ExtensionChild.jsm:763:61
_callHandlers/<@resource://gre/modules/MessageChannel.jsm:585:17
_callHandlers@resource://gre/modules/MessageChannel.jsm:584:14
_handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:649:7
_handleMessage@resource://gre/modules/MessageChannel.jsm:646:24
receiveMessage@resource://gre/modules/MessageChannel.jsm:163:5
]]`

are these errors?
anyway to fix them?

**Comment by ke-d** [comment] 2017-09-25 22:42
Duplicate of #93.

The solution is to turn on e10s.

**Closed as completed by ke-d** 2017-09-25 22:42 UTC
Labels: duplicate

**Comment by rezad1393** [comment] 2017-09-26 12:13
the e10s?
you mean multi process?
it is on I think.
from about:support.
Multiprocess Windows 	1/1 (Enabled by user)
Web Content Processes 	1/1
