### ISSUE TITLE
Whitelisting of protonmail.com not works - cookies always get deleted

### ISSUE THREAD

**Issue by Mart0k** [mrdokenny/Cookie-AutoDelete#259] opened 2017-11-20 14:47 UTC
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by danmerl** [comment] 2017-11-20 18:38
I think this is intended behavior of protonmail:  https://www.reddit.com/r/ProtonMail/comments/5hwtzs/how_to_stay_logged_in/?st=ja8j3edi&sh=ca92cd97

**Comment by Mart0k** [comment] 2017-11-20 20:05
Hi,
the user should be able to control the situation and not some cooked-up rules. Anyways, without the anti cookie I do not have to login anymore. I uninstalled it and I am happy.

Sorry but thanks for info. Will consider it again if we can decide ourselves how our browser should work.

brgrds
Mart0k

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by ke-d** [comment] 2017-11-21 21:50
Closing as this is an external issue.

**Closed as completed by ke-d** 2017-11-21 21:50 UTC
Labels: invalid
