### ISSUE TITLE
[Bug]  CAD not deleting cookies

### ISSUE THREAD

**Issue by paoletto** [mrdokenny/Cookie-AutoDelete#1577] opened 2023-06-18 09:15 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Somehow, at least for certain sites, CAD does not delete the cookies in the default container, in which i keep 0 rules (or expression).
I would expect that everything that isn't whitelisted gets deleted, *at least* at startup/shutdown.
Yet this does not happen, and to make it happen i have to manually go to FF->settings->manage data and delete the specific cookie.
Also the clean button, clean all for this domain, clean include open tabs etc is not removing said cookies.

### To Reproduce

Go to rt.com
Open any news
go to comments section
log-in
restart firefox
go to rt.com
open any news
go to comments section
you are still logged in

### Expected Behavior

after browser restart, you should be logged out of the website

### System Info - Operating System (OS)

Linux

### System Info - Browser Info

Firefox 113

### System Info - CookieAutoDelete Version

3.8.2

**Comment by kennethtran93** [comment] 2023-06-27 05:56
what are your CAD settings?

**Comment by hbednar** [comment] 2023-06-30 12:10
@kennethtran93 
I am getting the same with firefox 115.0b9 on linux:

This is whats left after cleaning all including open tabs and google is not white or gray listed:
![VQMe6tc](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/assets/71215137/eee54c42-153c-4f7f-bda4-a107f972dae5)

These are the settings i am using:
![Du3x5n5](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/assets/71215137/9af68d1b-b1e4-4cfb-86f2-959cf84fdf2d)

**Comment by kennethtran93** [comment] 2023-07-01 20:05
Ah... most likely still due to this issue #807

**Comment by tsunami2311** [comment] 2023-07-02 17:14
I would like to say I noticed happens, for me  to truely have all cookies delete on exit restart of Firefox I need to select Clean cookies/site  when firefox is closed, only then do all cookies get cleaned

I had to set a exclusion with sites in Firefox manager in conjunctions with CAD whitelist and greylist to have all cookies and site data clean out they never there  upone shutdown/restart of FF 

At some point CAD actual was delete this upon exit but start again i guess,  mean no cookies of any kine where left upon shutdown/restart of FF, but stop i guess after certain FF update


FF cookie manager leave alot to desire which why i started use CAD in first to manage all this.

**Comment by kennethtran93** [comment] 2023-07-10 05:20
duplicate of #807 - closing unless otherwise noted below.

**Closed as completed by kennethtran93** 2023-07-10 05:20 UTC
Labels: duplicate
