### ISSUE TITLE
[FEATURE REQUEST]  Change Location Of Clean Up Notification

### ISSUE THREAD

**Issue by stylemessiah** [mrdokenny/Cookie-AutoDelete#1149] opened 2021-05-20 18:03 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

Can we please have the option or moving the clean up notification to the left of screen...while theyre displayed on the right they completely mess up scrolling...you have to wait till they disappear or clear them manually to get control back

Highly annoying...

Cheers

### Describe the solution that you'd like

Option to move location to left of screen

**Comment by kennethtran93** [comment] 2021-05-20 22:15
Duplicate of #940 and others.

Placements of notifications are handled by the browser and OS.  All our notifications goes through `browser.notifications` which does not provide any way to customize where it is shown.

**Closed as completed** 2021-05-20 22:16 UTC
Labels: duplicate, wontfix/cantfix, Feature Request
