### ISSUE TITLE
[SUPPORT]  Delete all cookies, except session cookies.

### ISSUE THREAD

**Issue by PepeParada** [mrdokenny/Cookie-AutoDelete#1124] opened 2021-04-23 01:30 UTC
### Acknowledgements

- [x] I acknowledge that I have read the above items

### Please describe what you need support with

[SUPPORT] Hello. I need help. I don't speak English so I'll translate with Google.

How can I delete all cookies from a website, except those that keep a session open?
 I guess the solution is in the "keep all cookies" section. I'm right?. Or what would be a way?

for example, Google. I want to delete tracking cookies, but keep the session active. Is it possible to do this?

Thank you.

**Comment by PepeParada** [comment] 2021-04-23 01:33
@kennethtran93

**Comment by kennethtran93** [comment] 2021-04-23 01:47
You will need to figure out which is the cookie that holds the session yourself. Websites can name the cookies whatever they want as long as they know what the cookie is used for. You can find a list of cookie names if you uncheck 'Keep All Cookies). 

Note that tracking cookies are usually from third-party sites and won't show up in that list of your domain expression is set to your main site, so you are usually ok with keeping it as "Keep All Cookies".  
E.g. If your session is with "example.com" and your domain expression is either "*.example.com" or "example.com" then you should be fine without doing anything else, unless you want that same site to track you less but still stay logged in). You won't see tracking cookies from "doubleclick.net" in that list if you uncheck the "Keep All Cookies" as those would only show cookies from the "example.com" domain. 

You can also use another cookie editor extension to see more details about a cookie, like the value, which site it came from, expiration date, and much more.

These things are trial and error, so you'll need to keep trying and undoing the cookie cleanups until you find the cookie(s) that are holding the session.

With Google you'll need to utilize subdomains to figure out where that session cookie is stored, preferably by using a cookie editor webextension. Accounts.google.com may be one place to start, but you may need multiple domain expressions in order to stay logged in (e.g. Mail.google.com)

**Comment by PepeParada** [comment] 2021-04-23 01:51
> Deberá averiguar cuál es la cookie que contiene la sesión usted mismo. Los sitios web pueden nombrar las cookies como quieran siempre que sepan para qué se utiliza la cookie. Puede encontrar una lista de nombres de cookies si desmarca 'Conservar todas las cookies'.
> 
> Tenga en cuenta que las cookies de seguimiento generalmente provienen de sitios de terceros y no aparecerán en esa lista de su expresión de dominio configurada en su sitio principal, por lo que generalmente está de acuerdo con mantenerla como "Conservar todas las cookies".
> Por ejemplo, si su sesión es con "example.com" y la expresión de su dominio es "* .example.com" o "example.com", entonces debería estar bien sin hacer nada más, a menos que desee que el mismo sitio lo rastree menos. pero aún permanecer conectado). No verá las cookies de seguimiento de "doubleclick.net" en esa lista si desmarca "Mantener todas las cookies", ya que solo mostrarían las cookies del dominio "example.com".
> 
> También puede usar otra extensión del editor de cookies para ver más detalles sobre una cookie, como el valor, el sitio del que proviene, la fecha de vencimiento y mucho más.
> 
> Estas cosas son de prueba y error, por lo que deberá seguir intentando y deshaciendo las limpiezas de cookies hasta que encuentre las cookies que mantienen la sesión.

I understood perfectly. Thank you.

**Comment by kennethtran93** [comment] 2021-04-26 20:16
Closing as resolved.

**Closed as completed by kennethtran93** 2021-04-26 20:16 UTC
Labels: support

**Comment by shodanx2** [comment] 2025-04-29 14:24
Hi all,

After reviewing the discussion here, I wanted to propose a broader solution to the difficulty raised in this issue.

Context:

- There is no centralized public list of which cookies are session cookies for each website.
- Privacy today is intentionally made burdensome — not by accident, but by design.
- Convenience (stay logged in easily) is tightly coupled to data extraction (persistent tracking).
- Thus, defending privacy requires users to individually rebuild the wheel, manually, for each site.
- Meanwhile, surveillance and vendor lock-in are automated, default, and effortless.
- The difficulty of managing cookies and sessions is itself a form of coercion.
- The system is built to ensure that most people give up and remain trackable.

    Because of this, CookieAutoDelete (CAD) is perfectly positioned to change the game, much like how SponsorBlock helped millions of users collaboratively purge YouTube ads.

    Proposal:

        Add a feature that allows users, with a single action, to specify for a specific website:
        ➔ Keep only session cookies for this site
        ➔ Optionally, only inside a specific container

- Use a shared session-cookie rules repository that CAD can reference and update dynamically, similar to how uBlock Origin uses filter lists.
- Allow users to create cookie rules manually for a domain+container combo and submit them to the repository if a rule doesn't already exist.
- If a session cookie rule exists for a given site, CAD could automatically recognize and apply it when the user chooses "Keep Session Cookies Only" for that site/container.

Over time, this would scale privacy defense collaboratively, just like SponsorBlock scaled ad removal.

Why this matters:

Today, maintaining privacy and session persistence demands highly technical, repetitive manual labor from each user individually.

With a shared repository + one-click "keep only session cookies" option, CAD could:

- Massively reduce the burden on individual users,
- Democratize privacy-preserving cookie management,
- Make strong privacy easy instead of hard,
- And ultimately coordinate users to take back control of their browsing.

SponsorBlock showed that decentralized user contributions can power effective, real-time defenses against corporate manipulation.

CookieAutoDelete could do the same for cookie surveillance.

Thanks for considering this!

**Comment by shodanx2** [comment] 2025-04-29 14:34
## 🛠 How Rules to Detect Session Cookies Can Be Made

A session cookie detection rule could be simple:

| Field | Description |
|:------|:------------|
| Domain | Which website (or subdomain) the rule applies to. |
| Container (optional) | Which container context the rule applies to. |
| Cookie Name(s) | List of specific cookie names to *keep* (because they are session cookies). |
| Notes/Source | (Optional) Human-readable explanation ("Keeps Gmail login alive", etc.) |
| Metadata | Creator, creation date, verification status, number of votes |

**Example rule:**
```json
{
  "domain": "mail.google.com",
  "container": "Work",
  "keepCookies": ["SID", "SSID", "HSID"],
  "notes": "Essential cookies to maintain Gmail session",
  "metadata": {
    "submittedBy": "user123",
    "dateCreated": "2025-04-29",
    "verification": {
      "votesYes": 14,
      "votesNo": 1
    }
  }
}
```

## 📤 How Users Can Create and Export Rules

Inside CookieAutoDelete (or a similar extension):

- When a user manually selects cookies to keep (e.g., from a live cookie list),
- They get an option: **"Export Session Cookie Rule for this site"**.

This generates a rule file (like the JSON above) that they can:

- Save locally,
- Share publicly (submit to a repository),
- Reimport later.

Benefits:

- ✅ Simple
- ✅ Low effort
- ✅ No coding needed

---

## 📥 How Users Can Import Rules

- Extension loads a subscription list of rules, similar to how uBlock Origin filter lists work.
- Users can manually add trusted lists or their own custom rules.

Example:

- Default list curated by maintainers,
- Community lists curated by volunteers (e.g., "Banking Sites Rulepack", "Social Media Rulepack").

Benefits:

- ✅ Decentralized
- ✅ Flexible

---

## 🔎 How Rules Can Be Voted and Verified

Inspired by SponsorBlock:

| Step | Action |
|:-----|:-------|
| 1. Submit Rule | Users create and upload a rule for a site. |
| 2. Community Voting | Other users vote: 👍 "works" or 👎 "breaks login". |
| 3. Reputation Weight | Longtime contributors have higher voting weight. |
| 4. Auto-Removal of Bad Rules | Rules with too many 👎 votes get flagged or removed. |
| 5. Confidence Score | Rules show trust level based on votes and reports. |

Example on a rule's page:

```
mail.google.com Session Rule
✅ 94% of 150 users confirm this rule keeps login working.
❗ 3 users reported "breaks after logout"
Last verified: 3 days ago
```

## Benefits

- Trustable over time
- Catches when sites change
- Open community moderation

---

## 🧠 How CookieAutoDelete (or a Fork) Could Use This

Extension UI could have options:

- "Contribute Session Cookie Rule"
- "Browse Session Cookie Rules"
- "Export your session rules"
- "Import session rules from repository"
- "Automatically apply trusted rules"

---

## 🚀 Advantages of This Approach

| Advantage | Why It Matters |
|:----------|:---------------|
| Scalable | Thousands of users can contribute in parallel. |
| Self-correcting | Bad rules die quickly by downvotes. |
| Open | No single point of failure or control. |
| Empowering | Users stop micromanaging each site individually. |
| Immediate Practical Impact | Drastically cuts down "re-login fatigue" without sacrificing privacy. |

---

## 🧩 Big Picture

This approach would:

- Turn manual privacy micromanagement into collaborative maintenance.
- Make cookie-based surveillance a solvable community problem, similar to ad-blocking.
- Give normal users real agency again on the web.

---

## ✅ Quick Recap

| Phase | Action |
|:------|:-------|
| Detect | User manually selects session cookies on a site. |
| Export | One click generates a rule (domain, cookies, optional container). |
| Share | Submit the rule to a public repository. |
| Vote | Community verifies (works or does not work). |
| Sync | Users subscribe to updated trusted lists automatically. |
