### ISSUE TITLE
[FEATURE REQUEST]  Be able to change notification popup position from top to bottom of the screen.

### ISSUE THREAD

**Issue by jkuj6** [mrdokenny/Cookie-AutoDelete#940] opened 2020-10-22 17:00 UTC
**Is your feature request related to a problem? Please describe.** 

When i close tabs, i like to see the notifications of cookies getting cleaned (even though i have set the popup to 1sec) i still dont want it to show and popup where my tabs are as it is covering up the tabs where im busy closing multiple tabs, one after the other, and the popup notification is always in the way, i have to wait 1sec for the notification to disappear before i close the next tab, this is especially frustrating when you are closing multiple tabs.

**Describe the solution you'd like** 

The solution to this would be to have an option in the settings to move the notification popups at the bottom right hand corner, or basically anywhere the user feels like putting them, so that they are not in the way of the tab X's for example.

**Describe alternatives you've considered** 

none

**Comment by kennethtran93** [comment] 2020-10-22 18:54
This is out of our hands as we call `browser.notifications.create` for notifications, so you'll need to see if your browser has any sort of configuration for that, or else your OS configuration for notifications. We have no control on where it gets displayed - only the title and contents within it.

I believe this is a duplicate of another related notification issue (#367).

**Closed as completed** 2020-10-22 19:41 UTC
Labels: duplicate, browserbug/limitation, Feature Request
