### ISSUE TITLE
Cookie-AutoDelete does not delete ebay.co.uk cookies

### ISSUE THREAD

**Issue by Noexpert** [mrdokenny/Cookie-AutoDelete#263] opened 2017-11-21 21:39 UTC
Log in to ebay.co.uk (possibly replicated for ebay.com).
Close tab. No notification appears about deleting cookies.

Checking the browser cookies, the ebay cookie is still there.
The domain is not whitelisted.

- OS/version:  Windows 10
- Browser/version:  FX 57
- Cookie AutoDelete version: 2.0.1

**Comment by Noexpert** [comment] 2017-11-25 16:49
Also on Amazon.
Possibly related to: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/274

**Comment by andlaus** [comment] 2017-11-26 22:37
I just had a similar experience with a google.com cookie (cookie name: "NID") on FF 57+Linux: pressing the cleanup button multiple times in a row produced a "one cookie deleted from google.com" every time. Manually deleting the cookie via the preferences worked, though.

I have occasionally seen this before, but unfortunately I cannot reproduce relieably. Finding out what object set the cookie in question would probably be helpful here, but I had to fold here.

**Comment by practik** [comment] 2017-11-29 20:38
@andlaus, your Google NID cookie is probably being set by the Google Safe Browsing API. This is a known issue, mentioned at https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/ :
"If you get notifications for a google cookie (with the name: NID) that can't be deleted, then it's probably this Firefox bug. The workaround is to just delete that cookie from Firefox's cookie manager."

@Noexpert, much to my surprise, I can reproduce the same problem on macOS 10.12 (same versions of FF and CAD as yours) – and I can report that it doesn't appear for ebay.com, ebay.de, ebay.in, or ebay.co.jp.  Only ebay.co.uk.  Very strange.

**Comment by andlaus** [comment] 2017-11-30 10:08
> @andlaus, your Google NID cookie is probably being set by the Google Safe Browsing API. This is a known issue, mentioned at https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/ :
"If you get notifications for a google cookie (with the name: NID) that can't be deleted, then it's probably this Firefox bug. The workaround is to just delete that cookie from Firefox's cookie manager."

ah, okay, thanks for the pointers. I somehow missed this. has that bug already been fixed in the FF development version, or if it isn't, is it on the radar?

**Comment by practik** [comment] 2017-11-30 16:35
@andlaus, I believe it's being worked on [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197). You might also want to read issue #83, which I meant to link above but forgot. Any further discussion of the NID cookie should ideally happen there.

**Comment by practik** [comment] 2017-11-30 20:46
One other comment, back on topic now:  I've replicated @Noexpert's bug with bbc.co.uk and telegraph.co.uk as well.  So this appears to be a general problem with co.uk domains.

**Comment by bugcon** [comment] 2017-12-05 16:41
Came here after seeing the option to whitelist the whole .co.uk second level domain.

I suspect this bug will be present on any CC Second Level Domain:
https://en.wikipedia.org/wiki/Second-level_domain#Country-code_second-level_domains

IMO these domains should be made exceptions and the dialog should not offer to whitelist them.

**Comment by practik** [comment] 2017-12-05 17:10
@bugcon, strangely, this bug is more specific than that – as I mentioned above, it doesn't appear for ebay.co.jp.  I've done some more testing just now on some other second-level domains (co.il, com.ar, com.mx, plus a couple more co.jp sites), and their cookies all get cleared as expected.

As for the whitelisting options, there's already a bug for that at #243.

**Comment by ke-d** [comment] 2018-01-16 06:47
I think the side effect of d2d6c110635b5a7e4597d614aa3894d4d97603ab is that it should resolved this issue as well.

**Closed as completed by ke-d** 2018-01-16 06:47 UTC

**Comment by practik** [comment] 2018-01-16 18:14
Yes, it does seem to be resolved – I just tested on a few different co.uk sites and CAD cleared all of their cookies as expected.
