### ISSUE TITLE
[Bug] seems not deleting some data or cookies

### ISSUE THREAD

**Issue by anonymcoding** [mrdokenny/Cookie-AutoDelete#1356] opened 2022-04-09 13:13 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

after clean processes still show some data exist from twitter (at the all data and permissions page of chrome)

### To Reproduce

i m enabled automatic clean and all other browsing data cleanup options also tried manual cleaning from pop up

### Expected Behavior

expecting clear those data or cookies

### System Info - Operating System (OS)

win 11 pro

### System Info - Browser Info

100.0.4896.75 (Official Build) (64-bit)

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment] 2022-04-10 00:08
Do you have Twitter installed as a Web App?
Do you have existing tabs open with twitter.com?
Do you have any domains or regular expressions in the list of expressions that matches twitter.com?

**Comment by anonymcoding** [comment] 2022-04-10 11:51
> Do you have Twitter installed as a Web App? Do you have existing tabs open with twitter.com? Do you have any domains or regular expressions in the list of expressions that matches twitter.com?

no i haven't, actually if you try to the open twitter.com then make clear process i think also you can see that if im not doing something wrong.

**Comment by kennethtran93** [comment] 2022-04-30 23:01
While the extension does clean up the items as it should (Cache, Cookies, IndexedDB, localstorage, Service Workers), the only data remaining is Cache Storage, which is as expected as it is not the same as Cache, according to the chromium webextension docs.

This is now a feature request, as **Cache** and **Cache Storage** are two separate things.  Firefox had yet to implement this so it wasn't on my list of things to try and implement yet.

![image](https://user-images.githubusercontent.com/6724477/166125405-f7aa39be-5082-4d7f-a1f9-9acb92ce9ebf.png)

**Comment by kennethtran93** [comment] 2022-04-30 23:02
As this issue now revolves cleaning up data that isn't implemented by this extension yet, it will be closed as a duplicate issue.

Duplicate of #845.

**Closed as completed by kennethtran93** 2022-04-30 23:02 UTC
Labels: duplicate, Google Chrome
