### ISSUE TITLE
Feature Request: Keyboard Shortcut

### ISSUE THREAD

**Issue by darkzbaron** [mrdokenny/Cookie-AutoDelete#553] opened 2019-07-12 09:55 UTC
Hi there, any chance to have keyboard shortcuts to enable "Auto-clean" and other functions? Thanks for the great work!

**Comment by kennethtran93** [comment] 2019-07-14 23:22
Generally enabling auto-clean should be a one-time thing (enable and forget), so a keyboard shortcut isn't really needed.

That being said that could be a possibility though we would need to research which initial key combination shortcut we would use for
1. Show popup
2. Manual Clean
(Feel free to chime in for proposing a usable keyboard that is cross-platform compatible, as well as other potential functions that could use a shortcut).

As for the whitelist/greylist buttons on the popup, it's slightly hard to make a concrete key combination due to the fact that there are wildcards for sub domains, and will contain as many buttons as there are sub domains+main domain

**Comment by teake** [comment] 2020-02-11 10:23
Duplicate of #46.

**Comment by kennethtran93** [comment] 2020-02-12 10:00
Thanks @teake .  

Closing for duplication per note above.  I didn't look too far back into the open issues yet.

**Closed as completed by kennethtran93** 2020-02-12 10:00 UTC
Labels: Feature Request
