### ISSUE TITLE
Why Does CAD Store 112 MB of Cookies??

### ISSUE THREAD

**Issue by koolx** [mrdokenny/Cookie-AutoDelete#589] opened 2019-11-15 03:17 UTC
I read our FAQ but my issue still remains. Is it normal for CAD to store 112 MB of cookies?? This is very strange. I only keep about 12 sites with cookies so why are there 1212 MB of cookies stored?.

**Comment by kennethtran93** [comment] 2019-11-15 04:39
May I ask where you got that number from?  A screenshot or steps to get that info?

**Comment by koolx** [comment] 2019-11-15 04:45
Hi kenneth. I got it from firefox settings > Privacy and settings > 
Cookies and Site Data > Clear Data. It says 112 MB.

**Comment by kennethtran93** [comment] 2019-11-15 05:03
Cookies generally don't use that much space unless the site stores that much data in cookies.  Your sites would most likely be utilizing a combination of localstorage and/or indexDB (thus, site data).  Keep in mind that CAD cannot remove some site data per site due to browser limitations (i.e. no specific function/api to remove data by sitename/host).

**Comment by kennethtran93** [comment] 2019-11-15 05:23
Also, if you click on 'Manage Data' right below that, you should see which specific site is storing how much cookies and data.  Storage size consists of non-persistent storage as well as persistent storage.  Both indexDB and localstorage counts are in there.

**Comment by koolx** [comment] 2019-11-15 07:21
> 
> 
> Also, if you click on 'Manage Data' right below that, you should see which specific site is storing how much cookies and data. Storage size consists of non-persistent storage as well as persistent storage. Both indexDB and localstorage counts are in there.

And thats whats extremely confusing about this issue. In 'Manage Data' for example, I have 23MB under 'forums.t-nation.com' and 7MB under 'freshwatersystems.com'. Both of these websites I have NEVER added to CAD. Why is this happening?? How do I fix this to make sure the sites dont store cookies on my firefox again??

**Comment by koolx** [comment] 2019-11-16 00:22
Kenneth.. could you please answer my questions in my last post? Would appreciate it greatly.

**Comment by kennethtran93** [comment] 2019-11-16 00:54
@koolx Please be patient.  There's only so much time I have between work and sleep.
These sites may have set data through your currently opened sites, and it may not be related to cookies at all.  There is an option in CAD popup that allows you to clear third-party cookies that your site has set.  The CAD only runs upon domain change (if enabled in CAD settings) or on tab close.  If you enable the cleanup log and counter setting, you can see what CAD is doing during automatic and manual cleanings.

**Comment by kennethtran93** [comment] 2019-11-16 00:56
Sites (including third-party ones) will always be able to store cookies and data (localstorage/indexDB) upon load.  It is up to you/the addons to clear it as needed.

**Comment by koolx** [comment] 2019-11-16 01:05
Hi Kenneth. Sorry for rushing you, I didnt mean it. I got 4 questions. Please answer them when you have time.. no rush at all.

1. How do i clear 3rd party cookies?
2. Do you think when I whitelist a site whose cookies I want to keep, that I should just keep the cookies but not its local storage?
3. Whats a good way to delete 3rd party cookies and ensure theyre never ever stored?
4. Dont you think 112MB is unusually high for cookies and cachestorage? Especially when all I want to keep are cookies from 10 sites ONLY?
.

**Comment by kennethtran93** [comment] 2019-11-17 05:39
1) That depends on what settings you are using.
2) That depends on the site itself.  Some sites may utilize a combination of cookies and/or localstorage.
3) 3rd party cookies will be stored regardless.  This and other extensions can provide a way to 'auto' remove them depending on the configuration in the settings.
4) I don't think so.  My Firefox on linux is currently using 666MB (lol) of storage.  As a side note, cache is included in that count, which is where the browser stores images, pages, scripts, etc. (separate from localstorage) so that if you reload that page there is usually less requests to the original site since you already have some files from that page that is needed to load, thus making the final response time faster.

**Comment by koolx** [comment] 2019-11-17 21:43
Hi Ken,

1. Regarding 3rd party cookies, I have ff set up in Privacy and Security > Custom to block all 3rd party cookies. It should block them all. But you said 3rd party cookies will be stored regardless. I'm confused. 
2. How do I delete 3rd party cookies on CAD?
3. But 23MB for 'forums.t-nation.com' which is a site NOT whitelisted makes no sense. How was that stored when I never whitelisted it??
4. Do you think I should wipe all storage (cache, cookies and localstroage) to start afresh? I want to ensure I dont accumulate unneeded storage again that I never whitelisted.

**Comment by kennethtran93** [comment] 2019-11-18 02:38
1) My apologies - I forgot that firefox itself does have those settings.  You can block it but keep in mind that some site may not work properly with 3rd party cookies disabled.

2) Usually CAD should be able to delete it as it should not be listed on your grey or white list during auto or manual cleaning.

3) I can't answer that question.  Maybe a combination of images, files, scripts?  Some images do take up space.

4) That's up to you.  Feel free to remove that individual line in Firefox if you so desired.  You'll always get accumulate some extra storage that isn't whitelisted through this web extension as we can't clean a few things up by domains yet due to API limitations.

**Comment by kennethtran93** [comment] 2019-11-20 02:21
I'm closing this as it isn't really an issue that is caused by this extension.

**Closed as completed by kennethtran93** 2019-11-20 02:21 UTC
Labels: invalid, support

**Comment by koolx** [comment] 2019-11-20 19:00
Thanks Kenneth for your help and your immediate attention.
