### ISSUE TITLE
Feature Request: reject cookies from all websites by default

### ISSUE THREAD

**Issue by MrGlasspoole** [mrdokenny/Cookie-AutoDelete#210] opened 2017-10-27 17:07 UTC
Hi,

i was using 'Cookie Whitelist, With Buttons' for a long time:
https://addons.mozilla.org/en-US/firefox/addon/cookie-whitelist-with-buttons/

It would be nice to have a mix of your Add-on and 'Cookie Whitelist, With Buttons'.
So that all cookies are reject from all websites by default. And a second button to allow all cookies until the button is disabled. So exactly like that other Add-on but with the rest of yours (auto-clean, white-/grey-list).

**Comment by ke-d** [comment] 2017-10-27 23:34
Duplicate of #134

**Closed as completed by ke-d** 2017-10-27 23:34 UTC
