### ISSUE TITLE
Request ability to delete only specific cookies for a domain

### ISSUE THREAD

**Issue by snowbound** [mrdokenny/Cookie-AutoDelete#460] opened 2018-11-02 17:45 UTC
Google has indicated that they soon will prevent people from logging in if their browser is blocking Javascript. Some disable javascript on accounts.google.com so that it forces the old log in screen and allows when Chrome is closed to automatically logging you out of your account.  You can delete all the cookies for say google.com or account.google.com but if you are using 2FA on a trusted computer then taking this sort of action forces you to re-authentic with the current 2FA code on every login.

Google appears to set a SID and HSID cookie when logging in to Gmail and does not set the Current Session  ID flag on. This means that unless you explicity remember to log out of the account BEFORE you close the browser then anyone with physical access to the browser can get into your Gmail account.

What would be nice is the ability to delete specific cookies automatically on browser closure such as the above mentioned SID and HSID cookies for Gmail. Even the ability to remove whatever cookie that the Google Account Chooser users to store you account name in would also be a god send to tighten up security on shared computers.

**Comment by ke-d** [comment] 2018-11-08 01:39
Duplicate of #68

**Closed as completed by ke-d** 2018-11-08 01:39 UTC
Labels: duplicate
