### ISSUE TITLE
[Bug] Local storage for whitelisted domain deleted when cleaning expired cookies

### ISSUE THREAD

**Issue by wkral** [mrdokenny/Cookie-AutoDelete#1427] opened 2022-07-18 02:41 UTC
Using a service that recently switched to using local storage for session tokens rather than cookies. I have been getting logged out repeatedly and seems to be CAD causing the issue.

In a container tab with a whitelisted domain, there seems to be a cookie set with an expiry somewhere between 30 minutes and a few hours from the time of creation shortly after logging in. That cookie doesn't seem to have anything to do with the login session for the site. 

I've observed a few times that after the expiry of that cookie a log entry in CAD stating that it's cleaning up the domain and deleting that specific cookie. After this when I look in the developer tools storage section in FF, and the local storage items are gone, one being the login session token.

I ran the experiment again with "Clean All Expired Cookies" setting off, and as expected there is no log entry after the expiration. The local storage also remains intact after the expiration. So it seems that cleanup of the domain for expired cookies also deletes the local storage for that domain even if it is explicitly whitelisted.

_Originally posted by @wkral in https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1395#issuecomment-1186643439_

**Comment by kennethtran93** [comment] 2022-07-21 05:00
Seeing that you already looked into this further, I wonder if you can enable debug mode on the extension (CAD Settings), then follow the instructions to view the extension console log.  Then reproduce the bug and supply the logs for it (May save some file size if we filter for `CAD_`, and then right-click -> 'Save All Messages to File')

**Comment by wkral** [comment] 2022-07-23 05:54
Sorry it took me a while to get the time to collect these logs as it takes a good amount of time to reproduce the issue. 

That particular output unfortunately has a lot of sensitive information I wouldn't want to put on a public forum, it's also a huge file ~60K lines, but I think the relavent log lines are the following:

```
CAD_3.8.1 - debug - CleanupService.filterSiteData: debug data.
{
  "notProtectedByOpenTab": true,
  "notInAnyLists": false,
  "siteData": "LocalStorage",
  "isCADCookieNoExpression": true,
  "cleanSiteDataInExpression": false,
  "isRestartCleanup": false,
  "canCleanSiteData": true,
  "nonBlankCookieHostName": true,
  "notOpenTabAndCanClean": true,
  "CleanReasonObject": {
    "cached": false,
    "cleanCookie": true,
    "cookie": {
      "name": "__stripe_sid",
      "value": "***",
      "domain": ".nebula.app",
      "hostOnly": false,
      "path": "/",
      "secure": true,
      "httpOnly": false,
      "sameSite": "strict",
      "session": false,
      "firstPartyDomain": "",
      "partitionKey": null,
      "expirationDate": 1658553050,
      "storeId": "firefox-container-11",
      "hostname": "nebula.app",
      "mainDomain": "nebula.app",
      "preparedCookieDomain": "https://nebula.app/"
    },
    "openTabStatus": "reasonTabsWereNotIgnored",
    "reason": "reasonCleanCookieExpired"
  }
} common-background-popup-setting.bundle.js:2:44103
CAD_3.8.1 - debug - CleanupService.filterSiteData: LocalStorage cleanup returned true for nebula.app
```

In the reproduction I had the tab open, in the correct container, the cookie had expired, the only other tabs I had open were the consol, and the CAD preference page. It seems I needed to open/close a new blank tab to trigger the cleanup, as I waited a few minutes after expiration and nothing happened.

From the log, there seems to be a logical conflation of the expired cookie cleanup with local storage. As further confirmation, I had the "Clean All Expired Cookies" setting off for the last few days since I reported this bug and I was not logged off from the site. After reproducing the issue I currently am.

Including a screenshot of my expression for this domain to show LocalStorage as whitelisted:
![20220722_22h37m25s_grim](https://user-images.githubusercontent.com/105114/180592254-62215d97-c8dd-44dd-8fd1-e219cc52efe4.png)

I also have another expression for `*.nebula.app` which I don't think is necessary, but just to be extra sure.

**Comment by kennethtran93** [comment] 2022-07-23 06:44
Thank you for helping with this, and for putting in some time to dig deeper into this.

Whoops, seems I put the expired cookie check before checking if it was part of any lists...

Part of this was that expired cookies need to be cleaned up anyways, so it got the first check.

I'll rework some logic behind this to ensure it also checks the list for the site data options.

**Comment by SpaceClicker** [comment] 2022-09-08 14:01
I just wanted to say that this has been driving me nuts for a while now...

The symptoms were that I would lose all my settings for Twitch.tv as well as the settings for the FrankerFaceZ add-on (for Twitch) periodically (I also think I would lose setting for discord.com as well).

I would continually have to restore my settings for FrankerFaceZ and re-enable all the settings for Twitch (such as dark mode, default video settings, etc.)

I determined that Twitch had these settings stored in "Local storage" as did the FrankerFaceZ plugin (under the twitch.tv domain).

This led me to start to look at CAD to see if it was clearing the Local Storage for twitch.tv, even though I had it in the whitelist.

I finally caught it in the log today (the logs only keep 10 entries, so it took a LONG time to catch it in the log... is there any way to increase that limit?).

It had the following entries:

Invoked cleanup of Cache for: outlook.live.com, live.com, microsoft.com, bing.com, www.bing.com, twitch.tv
Invoked cleanup of IndexedDB for: outlook.live.com, live.com, microsoft.com, bing.com, www.bing.com, twitch.tv
Invoked cleanup of LocalStorage for: outlook.live.com, live.com, microsoft.com, bing.com, www.bing.com, twitch.tv
Invoked cleanup of Plugin Data for: outlook.live.com, live.com, microsoft.com, bing.com, www.bing.com, twitch.tv
Invoked cleanup of Service Workers for: outlook.live.com, live.com, microsoft.com, bing.com, www.bing.com, twitch.tv
twitch.tv (referrer_url): Partial clean because of expired cookies from twitch.tv.


Since I had twitch.tv in my whitelist, I knew something was wrong that it was invoking cleanup for LocalStorage, et. al., and since none of the other entries were cleaning cookies from a container (I have the container option enabled), I knew it wasn't that.

So this drew me to that "expired cookies cleanup" message and my search that resulted in being able to find this bug report!

Before this, I was thinking the problem was related to containers, because I know that if I visited twitch.tv in one of my containers, that would result in Local Storage being deleted for twitch.tv, since i had no whitelist for twitch.tv in the containers.

As an aside, there really should be a setting that does the following:
If you have ANY whitelist for a domain in ANY container or globally that keeps any of the Cache, IndexedDB, LocalStorage, Plugin Data, or Service Workers, then it should NOT clean that item up no matter what container you visit that domain in.
It makes little sense to have, for instance, LocalStorage whitelisted on twitch.tv in the global whitelist, but if I visit twitch.tv (even in the background via, for instance an image loaded on a page from another site), it will delete LocalStorage for ALL containers and the non-container context (global).
I understand why it does this (there is no Firefox API to clean these things per container) but I think there should at least be an option to keep them if ANY of the containers has a whitelist for one or more of those items for the particular domain.
I understand that this will mean that, for instance, LocalStorage will now be saved for that domain in ALL containers in which you visit that domain (even if not explicitly mentioned in a whitelist for that container) but if you make it an option, people can be told this when they enable it.

Anyway, I have disable the cleanup of expired cookies, and I expect this will fix my problem, I look forward to when this bug is fixed in the add-on.  Thanks for this add-on and for reading this!

**Comment by vexillia** [comment] 2022-10-01 21:16
This is still a problem with feedly in a firefox container.

**Comment by IzzySoft** [comment] 2022-10-26 23:18
Looks like git-master is affected as well, storing e.g. Github access token in LocalStorage (site is white-listed of course). I was wondering why it always forgets it (which it does not do in my other browser) until I noticed I don't have CAD installed there. Have just disabled LocalStorage support in CAD for know to see if it's the same problem. Looking forward to the next release then :wink:

**Closed as completed** 2022-11-15 01:25 UTC
Labels: bug, has:pr

**Comment by kennethtran93** [comment] 2022-12-08 03:39
3.8.2 is released, and browsers will start getting updates once the webextension teams have approved them.
