### ISSUE TITLE
Feature Request: Clear site data when tab closed. 

### ISSUE THREAD

**Issue by Madeupname722** [mrdokenny/Cookie-AutoDelete#288] opened 2017-12-13 19:37 UTC
Will this feature be returning in the webextension version of this addon?

Currently, firefox itself can't even delete site data for a single site without wiping out all data as well as all cookies.

Win 10x64Pro
FF 57 (up to date)
Addon V2.01

**Comment by confiks** [comment] 2017-12-27 14:32
This feature has actually just been released as `2.1.0b1` on the PMO beta channel. See [this comment in #44](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44#issuecomment-353769132).

**Comment by ke-d** [comment] 2017-12-28 17:10
Only for localstorage at this point. Other site data depends on Mozilla implementing the APIs.

Duplicate of #44

**Closed as completed by ke-d** 2017-12-28 17:10 UTC
Labels: support
