### ISSUE TITLE
[Feature Request] Blacklist - Keep all website cookies but delete the ones on the blacklist

### ISSUE THREAD

**Issue by MattFromGer** [mrdokenny/Cookie-AutoDelete#191] opened 2017-10-16 12:41 UTC
I guess the title pretty much describes my suggestion.
Right now there's a white- and greylist, but no blacklist. I want to delete cookies just from specific sites and keep the general web as it is. Not possible right now as I see it.

**Comment by ke-d** [comment] 2017-10-16 14:37
Duplicate of #134

**Closed as completed by ke-d** 2017-10-16 14:37 UTC
Labels: duplicate

**Comment by ElhemEnohpi** [comment] 2017-11-03 16:50
@MattFromGer how do you see this working exactly? The issue in #134 is about having a blacklist for sites that should never be allowed to set cookies. It sounds like you're asking for something else - basically that all websites should be whitelisted by default, and only certain sites that you add to a blacklist will have their cookies auto-deleted when the tab is closed. Is that correct?

#134 also talks about using "*" in a blacklist to block all sites by default, but that wouldn't work for the whitelist, because the whitelist has priority. So even if 134 is implemented, I think it won't do what you want.

**Comment by BoboSims** [comment] 2020-05-04 18:11
I appreciate the age of this issue, but I think it's being misinterpreted. I would expect a blacklist to mean: prevent cookies from this (sub-)domain to even be created, or delete them at the earliest convenience.
I would even prefer to be able to name *specific cookies* , instead of a (sub-)domain to look for.

The "*" on a blacklist seems like a terrible idea, because that violates the whitelist. My 2 cents.

**Comment by kennethtran93** [comment] 2020-05-04 20:30
blacklist, when implemented, would be remove at earliest trigger.
At this point there's no specific cookie naming (unless it is from custom import).  You can use *.domain to look at all cookies on that domain, and check/uncheck accordingly.

**Comment by BoboSims** [comment] 2020-05-04 20:35
Yeah, I understand that. Well, I had to ask!
