### ISSUE TITLE
Whitelist everything

### ISSUE THREAD

**Issue by kzzyn** [mrdokenny/Cookie-AutoDelete#552] opened 2019-07-10 17:27 UTC
Can you add an option to whitelist everything and then choose on which sites cookies will be deleted on startup/restart ?
I would like to keep all cookies and pick individual websites where the cookies will be deleted.

**Comment by kennethtran93** [comment] 2019-07-11 07:17
This is a duplicate of #549.  Please try searching up keywords of issues or feature requests first before making a new one.

**Closed as completed by kennethtran93** 2019-07-11 07:17 UTC
Labels: duplicate

**Comment by kennethtran93** [comment] 2019-07-11 07:20
Also, the way this web extension works is that the whitelist is the first thing it checks for.  If the URL matches the regular expression on the whitelist, it stops doing anything altogether (that is, no cookies would get deleted at all).  

If you really want to whitelist everything, go into the expression tables in the settings and use `*` in the text box and click whitelist.
