### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by Birger52** [mrdokenny/Cookie-AutoDelete#328] opened 2018-01-17 19:59 UTC
FF 57.0.4 64bit - maybe also earlier.

A new version - presumably 2.0.0, not really sure, as there is no way to see current version, and I'm not sure if it is the one running or if it is actually installed already or it just want to - is asking permission to fiddle with my browsing history and my privacy settings.

And ... well ... permission not granted.
So how do I stop it from keep asking for it?
And what is the point of wanting to change my settings or browsing hisory?

### Your settings 

- OS/version: Win 7 64bit
- Browser/version: FF 57.0.4 64bit
- Cookie AutoDelete version:  maybe 2.0.0 - otherwise what came before...

**Comment by ke-d** [comment] 2018-01-17 23:17
Duplicate of #317

**Closed as completed by ke-d** 2018-01-17 23:17 UTC
Labels: duplicate
