### ISSUE TITLE
pls disable 'notifications' on default - it's insanely annoying and frustrating and bad design - pls make this better

### ISSUE THREAD

**Issue by SolveEverything** [mrdokenny/Cookie-AutoDelete#759] opened 2020-06-05 07:57 UTC
**Is your feature request related to a problem? Please describe.**

pls disable 'notifications' on default - it's insanely annoying and frustrating and bad design - pls make this better

**Describe the solution you'd like**

pls disable 'notifications' on default

**Describe alternatives you've considered**

uninstall this, pls streamline this extension, it's extremely cluttered

**Additional context**

pls disable 'notifications' on default - it's insanely annoying and frustrating and bad design - pls make this better

**Comment by kennethtran93** [comment] 2020-06-05 13:14
~~I think this will stay - just in case somebody accidentally activates the auto clean and wondering why the cookies were removed /not staying logged on and blaming this webextension.~~

Edit: fine. At least the cleanup log and counter is enabled by default so users have a way of undoing it.

**Comment by kennethtran93** [comment] 2020-06-05 15:46
Then again with the option to export and import core settings, this shouldn't really be an issue...unless you keep reinstalling the extension for some reason...

**Comment by kennethtran93** [comment] 2020-06-05 15:46
By the way...this is duplicate of #427

**Closed as completed by kennethtran93** 2020-06-05 15:46 UTC
Labels: Feature Request
