### ISSUE TITLE
[Bug]Chrome Cookies and Browsing Data

### ISSUE THREAD

**Issue by redwolfe98** [mrdokenny/Cookie-AutoDelete#1287] opened 2021-12-25 04:12 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

beginning with chrome version 96.0.4664.93, released on 12/11/2021, chrome now has a new "network" folder with a "cookies" file within it. the new "network" folder is located at "C:\Users\(user)\AppData\Local\Google\Chrome\User Data\Default\Network." since CAD has not been updated in the past 11 months, i would assume that it needs to be updated to address the new "cookies" file within the new "network" folder.

since this new "network" folder has been added to chrome, along with the "cookie" file within it, lots of people who use the chrome browser have been complaining that cookies are not being deleted, though i myself have not noticed that problem:

https://community.ccleaner.com/topic/61744-ccleaner-not-deleting-chrome-cookies/

additionally, "temp-files" appear to build up within the "code cache/js" folder, at "C:\Users\(user)\AppData\Local\Google\Chrome\User Data\Default\Code Cache\js." it would be good if CAD removed those "temp-files."

### To Reproduce

1. use chrome to browse webpages. 2. examine the "cookies" file within chrome's new "network" folder. 3. examine "temp-files" within chrome's "code cache/js" folder.

### Expected Behavior

i expect CAD to be updated to address the new "cookies" file within the new "network" folder, if needed, and for CAD to be updated to address the "temp-files" that accumulate within chrome's "code cache/js" folder, if possible. incidentally, those "temp-files" within the "code cache/js"-folder are removed when running chrome's own "clear browsing data."

### System Info - Operating System (OS)

windows 10-21H2

### System Info - Browser Info

chrome Version 96.0.4664.110

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

changes to the chrome browser which probably need to be looked into by the CAD developers.
i posted about this issue previously but it appears that my post was deleted. considering that chrome now appears to have a new location for storing cookies, the new "network" folder, i would think that it is something that the CAD developers should be made aware of and that the CAD browser-extension should be updated to address these changes to the chrome browser.

**Comment by kennethtran93** [comment] 2021-12-25 04:50
@redwolfe98 Your original post is here: #1286 and it is closed as not fixable by us as I cannot do anything about it due to browser limitations.  We can not delete any files - all we do is utilize the WebExtension API that is available to us.  If it is included in either of the following links
| Firefox | Chrome |
| --- | --- |
| https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData | https://developer.chrome.com/docs/extensions/reference/browsingData/ |
| https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies | https://developer.chrome.com/docs/extensions/reference/cookies/ |

then I could look into implementing it in.

Closing as duplicate of #1286.

**Comment by kennethtran93** [comment] 2021-12-25 04:55
I'll keep it open for now, but do refer to my comments in this and the other issue.

You are free to raise this issue up with the people who develop the WebExtension APIs for us to use.

**Closed as completed** 2022-01-04 21:10 UTC
Labels: duplicate, wontfix/cantfix, browserbug/limitation, external, Google Chrome
