### ISSUE TITLE
Request Feature: Blacklist for sites.

### ISSUE THREAD

**Issue by AirplaneRandy** [mrdokenny/Cookie-AutoDelete#255] opened 2017-11-19 03:25 UTC
This add-on currently has the Whitelist feature, which prevents the add on from deleting cookies from whitelisted websites. I'm requesting a blacklist. A list of websites the user can add that will automatically get deleted or get deleted with a press of a button. Basically, the addon is flipped upside down from instead of saving a select number of sites in a whitelist, it'll instead selectively delete only the ones in the blacklist. This was the primary feature in the old addon "selectivecookiedelete" that was last updated in 2011, and that I doubt will get ported to firefox quantum.

also, requesting a button that can be pressed from the toolbar to delete the cookies quickly without opening any further menus.
EDIT: to add to the button request. It would be cool if the user was able to add a single click button shortcut icon to the toolbar for "Clean", "Clean, include open tabs", and "Clear Cookies for this Domain". For me personally, I would like a "Clean, include open tabs" shortcut button.

need to mention that I'm aware that firefox has a blacklist cookie feature, but it just does not work for me, websites are still able to store cookies on my browser even after closing and resetting.

- OS/version: win7
- Browser/version: firefox57 
- Cookie AutoDelete version: nov 18 2017

**Comment by AirplaneRandy** [comment] 2017-11-19 03:32
https://addons.mozilla.org/en-US/firefox/addon/selectivecookiedelete/

This is the addon that I've previously used before updating to firefox quantum. Loved it, unfortunately I don't see it ever being ported to quantum.

Anyways, the primary features that I used this addon are the following:
- Blacklist, a list of a websites chosen by the user that will be deleted either by pressing the button on the toolbar in a single click, or closing the browser.
- Does not affect any other website, will only delete what's on the blacklist.
- A shortcut button that can be placed on the toolbar. Allows me to delete the blacklisted cookies very quickly with a single click.

**Comment by drcheap** [comment] 2017-11-21 06:10
This sounds a lot like #95 and #126 (a dupe of 95) and #134.

Also, a **blacklist** would prevent those cookies from ever being stored in the first place (which would be awesome, but apparently isn't possible using current APIs), so there would be no reason to have a button to do anything.

**Comment by practik** [comment] 2017-11-21 19:34
> need to mention that I'm aware that firefox has a blacklist cookie feature, but it just does not work for me, websites are still able to store cookies on my browser even after closing and resetting.

@AirplaneRandy, do you also have "Accept third-party cookies" set to "Never" in your Firefox privacy/history preferences? If not, I wonder if that's how your unwanted cookies are being stored.

**Comment by AirplaneRandy** [comment] 2017-11-21 21:48
> do you also have "Accept third-party cookies" set to "Never" in your Firefox privacy/history preferences? If not, I wonder if that's how your unwanted cookies are being stored.

@practik, It was set to "From visited". Okay, so I disabled Cookie Autodelete and set that setting to "Never". Even after setting firefox's blacklist for the website, the website was still able to store its cookie. The website in question is 4chan.org, the blacklist is the following:

4chan.org
.4chan.org
boards.4chan.org
.boards.4chan.org

So yea, I still have a problem here. In the mean time, I am using the whitelist feature for Cookie Autodelete, I just don't like having to add websites to a whitelist, I just prefer to add the select few problem sites that I visit often to a blacklist, it's much more simpler for me.

**Comment by ke-d** [comment] 2017-11-21 21:55
No need for duplicated issues #134

**Closed as completed by ke-d** 2017-11-21 21:55 UTC
Labels: duplicate
