### ISSUE TITLE
Error: can't convert undefined to object t.default

### ISSUE THREAD

**Issue by hurtstotouchfire** [mrdokenny/Cookie-AutoDelete#490] opened 2019-01-22 16:19 UTC
### Describe the Bug
Cookie Autodelete log menu is inaccessible on all sites. When opened, it displays an error trace (see below).

~Unclear if cookie deletion is functional.~ I checked my cookies and it looked as if no cleanup had happened for the last 6 days or so (extension was last updated 1/15, about six days ago) but the icon still displays a count of cookies for each site. _Update: Confirmed that no cookies are being deleted._

There does not seem to be an associated console error.

### Screenshot in which the bug can be seen
![screen shot 2019-01-22 at 11 06 37 am](https://user-images.githubusercontent.com/1400344/51549641-c8f4d080-1e38-11e9-922b-a6221a1e5507.png)

### Steps for anyone to reproduce the bug
Click on Cookie Autodelete icon in the browser toolbar.

Expected: Shows a log of deleted cookies
Error: Shows an error trace.

Uncertain of environmental factors necessary to reproduce at the moment. Will go through and disable my other extensions one at a time to see if that affects anything, and I'll try downgrading to 3.0.0. It seems most likely that the regression was introduced in 3.0.1.

### Your settings 
- OS/version: Mac OS 10.13.6
- Browser/version: FF Quantum 64.0.2 (64-bit)
- Cookie AutoDelete version: 3.0.1

------------------------------------------

Firefox 64.0.2 (64 bits) under Debian 9, CAD 3.0.1, Localstorage Cleanup disabled.

When I go to the extensions's Cleanup Log ("Journal de nettoyage" here in french, I'm not sure of the original wording), I get this error:

```
can't convert undefined to object
t.default</</n<@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:20:5269
t.default</<@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:20:5241
t.default<@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:20:5219
po@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:36:61969
Ko@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:36:78334
Yo@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:36:78711
Ai@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:36:85134
Oi@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:36:84514
Ii@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:36:90725
Sn@moz-extension://9b6e96d4-7e04-4c52-8f1a-2812cff186cd/bundles/common-popup-setting.bundle.js:36:30438
at line 20

```

_Originally posted by @pcdavid in https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/486#issuecomment-455193449_

**Comment by B00ze64** [comment] 2019-01-24 02:33
I'm on Chrome (which I use very rarely) and today I find I cannot open CAD's UI.
The error is similar to the above...

Error!
Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object at Function.entries (<anonymous>) at chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/bundles/common-popup-setting.bundle.js:20:5276 at a.createElement.i.map (chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/bundles/common-popup-setting.bundle.js:20:5381) at Array.map (<anonymous>) at t.default.o.connect.e (chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/bundles/common-popup-setting.bundle.js:20:5221) at po (chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/bundles/common-popup-setting.bundle.js:36:61969) at Ko (chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/bundles/common-popup-setting.bundle.js:36:78334) at Yo (chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/bundles/common-popup-setting.bundle.js:36:78711) at Ai (chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/bundles/common-popup-setting.bundle.js:36:85134) at Oi (chrome-extension://fhcgjolkccmbidfldomjliifgaodjagh/bundles/common-popup-setting.bundle.js:36:84514) at line undefined

**Comment by ke-d** [comment] 2019-01-24 06:24
Reset the extension data after exporting lists. 

The problem is I changed completely changed the activity log to support #196. The new code for the activity log ui uses the new structure, but if there's still old activity log from 2.X.X, it breaks cause it expects new 3.X.X activity log variables which the old structure won't have.

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/3.X.X-Branch/src/background.ts#L155

In theory, on update from 2.X.X to 3.X.X it should have cleared the activity log, but maybe sometimes it doesn't clear the activity log for some reason?

**Comment by hurtstotouchfire** [comment] 2019-02-03 14:53
@mrdokenny afaict there is no way to export the lists in this error state. None of the UI is available. I'm in FF, so I can go to the extension "preferences" page, but the only thing there is release notes and a link for rating the extension.

I uninstalled and re-installed and that fixed the issue.

**Comment by ke-d** [comment] 2019-02-16 04:31
I'm going to mark this as a duplicate of #484

**Closed as completed by ke-d** 2019-02-16 04:31 UTC
Labels: duplicate
