### ISSUE TITLE
Cookies not deleted consistently

### ISSUE THREAD

**Issue by Jerroder** [mrdokenny/Cookie-AutoDelete#570] opened 2019-09-04 19:18 UTC
Hi,

I have CAD installed for over a year now and I noticed recently that some cookies aren't not cleared whether automatically or manually. The auto-clean is enabled and set a 10 seconds and when I log into a website that is not whitelisted nor greylisted, if I close the tab and wait for more then 10 seconds, nothing happens.

However, when I open two not-whitelisted websites one after another (i.e. I close the first one before opening the second one), sometimes cookies for one of them get cleared (whereas it's not when I don't open the second website) and some other times both get cleared correctly. You may have to open both of them at the same time to trigger this behavior. Also, sometimes cookies get cleared for a website when I revisit this same website and not after 10 seconds. The behavior is not consistent.

_ log into not-whitelisted website 1
_ close the tab 1 and wait for x seconds
_ reopen website 1
--> still logged in
_ close the tab 1
_ log into not-whitelisted website 2
_ close the tab 2 and wait for x seconds
_ reopen website 2
--> still logged in
_ reopen website 1
--> maybe still logged in
_ close both
--> random cookies are cleared
_ reopen both
--> you're still logged into one of them but not the other, or not logged in at all, or still logged into both

- OS/version: Windows 10 - 1809
- Browser/version: Firefox 69.0 ("network.cookie.cookieBehavior = 1" and "network.cookie.lifetimePolicy = 0")
- Cookie AutoDelete version: 3.0.2

**Comment by LLI-inc** [comment] 2019-09-05 17:33
Yes, and I just noticed cookies from nytimes.com are never deleted. And I don't have it on a white or greylist. 

This is happening in the Vivaldi browser, version 2.7.1628.30.

I'm not having this problem in Chrome.

**Comment by kennethtran93** [comment] 2019-09-06 06:01
@rderensy Hmm...There seems to be a few cookie-related bugs surfacing recently and mostly from the firefox side. I recall the newly published webextension DownThemAll mentioning something about a bug in Firefox relating to cookies but not sure exactly what that bug is at this time.

@LLI-inc I can check that site, but I cannot offer support for the browser you're using as it is not one of the officially supported ones (i.e. Firefox or Chrome).

**Comment by Jerroder** [comment] 2019-09-06 11:05
@kennethtran93 I tried with the add-on "Forget Me Not" and it seems like it clears cookies correctly, same Firefox, same settings

**Comment by kennethtran93** [comment] 2020-02-29 09:35
@rderensy does the site you are referring to use cookies, localstorage, or indexedDB?  We can only clear certain data by hostname, namely cookies and localstorage.  There's a storage inspector in the development tools that will aid us in seeing what is being stored by that site.

@LLI-inc nytimes.com appears to have its cookies removed by CAD (at least the 4 that it found)
>  nytimes.com (nyt-a, nyt-gdpr, nyt-purr, nyt-geo): Clean because nytimes.com is not in the White/Grey lists

**Comment by Jerroder** [comment] 2020-03-03 13:57
@kennethtran93 I don't know about localstorage or indexedDB but it was at least cookies. Although, now the add-on previously mentioned doesn't work anymore, I encounter the same problem than with CAD so it might indeed be a Firefox problem.

**Comment by kennethtran93** [comment] 2020-03-30 05:55
Honestly I'm not sure what the issue is - we listen to the tabs.onclosed (and tabs.onUpdated if options were selected) event for all tabs and run the checks and have setTimeout set accordingly...

I can say that there was a localstorage bug that didn't get looked into until now, so that part will be fixed on the next release.  Another issue recently had their website use localstorage to store existing login data so it may have been that...

Is it still doing it at this time?

**Comment by Jerroder** [comment] 2020-04-05 20:41
Well, it seems like it works when you install/reinstall the add-on. It definitely stops working after a while. Same problem with ForgetMeNot.

**Comment by kennethtran93** [comment] 2020-04-17 03:36
If it is happening to more than one webextension, perhaps try to create an issue with Firefox itself via Bugzilla.

For the time being this will be treated as an external issue.

From what I can decipher from the source code, it seems that the cleanup action will be executed after X seconds when triggered.  If additional events also trigger the cleanup action, then it is ignored *only during* those X seconds of the first trigger as it will already get cleaned up when the first cleanup action is fired.

**Comment by Jerroder** [comment] 2020-04-17 09:42
I don't know if that's a Firefox problem.
Here on Github, I have "No rules matched this domain" but I am still logged in when I come back on it. Also, nothing gets cleared with I press the "clean" button, even when the Github tab is closed.
However, it gets cleared with I select "clear cookies for this domain" and I'm logged out when I refresh.

So I guess the cleaning mechanism isn't the problem, but the URL matching might be.

**Comment by kennethtran93** [comment] 2020-04-17 15:12
Is notifications enabled?  Do you have `cleanup logs and counter` enabled?

The only thing I can think of at this time is a cookie or a domain with some invalid characters or malformed cookie names/domain names before CAD was installed and used. Maybe you'll need to manually clear those domains using Firefox's internal cookie manager.

The `Clear Cookies for this domain` grabs the tab URL and extracts the main domain to clean for that container.

I wonder...If you know how to open up and inspect the extension console, if any details are shown if you press clean.  That may give an indication of something.

**Comment by Jerroder** [comment] 2020-04-17 21:42
Notifications are disabled and `cleanup logs and counter` is enabled.

I cleared Github cookies, logged back in (so recreated) and I'm still logged in after 15 secs and clicking `clean` (my automatic cleaning is set to 10 secs).

I'm not sure, no. I tried in the "browser console" (different than F12) but nothing happens here.

**Comment by kennethtran93** [comment] 2020-04-17 23:59
about:devtools-toolbox?type=extension&id=CookieAutoDelete%40kennydo.com 

If that doesn't work, then try about:debugging#/runtime/this-firefox and clicking `inspect` on CAD.

**Comment by Jerroder** [comment] 2020-04-18 18:18
So I can see `Object { payload: {…}, type: "COOKIE_CLEANUP" }` when I click on `Clean` but you'll have to tell me exactly what I should look at.

**Comment by kennethtran93** [comment] 2020-04-19 05:36
Any errors when cleanup action is triggered.

I'm assuming that there's no other GitHub tabs are open in any windows.

While I don't think enabling notifications will solve anything, could you try it anyway?

**Comment by Jerroder** [comment] 2020-04-19 15:09
I can confirm that I visited a few websites, and cookies have been cleared, but once again not Github's.

No, I didn't have any Github tabs openned.

Notifications don't change anything.

**Comment by kennethtran93** [comment] 2020-05-04 17:33
Sorry for the lack of updates - I'm working on getting console debug outputs so we'll see when I get a beta build for you to try.

**Comment by kennethtran93** [comment] 2020-05-06 04:47
Could you try PR #713 - there's build files in the comments - try to start with a fresh profile and see if the problem still persists?  There's debug mode available in this one if you're comfortable with reading the logs from browser extension console (devtools).

**Comment by kennethtran93** [comment] 2020-05-14 16:15
@rderensy could you try out the alpha builds in the release section?  I'm just working on some rough translations at this time before making it official

**Comment by kennethtran93** [comment] 2020-05-25 18:08
Latest version released is 3.3.1, with debug mode available.  Is this still happening?  If so some logs would be appreciated.

**Comment by Jerroder** [comment] 2020-05-25 21:42
Hello,

Sorry, I haven't had time to look into it before. I updated to 3.3.1 but I still see the same `Object { payload: {…}, type: "COOKIE_CLEANUP" }` in the console, but no errors.

Tbh I'm not sure where to look at to see the debug mode or to enable it.

**Comment by kennethtran93** [comment] 2020-05-25 21:44
Debug mode is in settings, all the way at the bottom. Once that is enabled, you'll see alot more than 'cookie cleanup' line on there. Might take some time to read through though.

**Comment by Jerroder** [comment] 2020-05-25 21:54
Got it.

There are no error. I can see
```
CAD_3.3.1 - debug - TabEvents.onDomainChangeRemove: Tab was closed.  Removing old tabToDomain info.
{
  "tabId": 20,
  "mainDomain": "github.com",
  "removeInfo": {
    "windowId": 1,
    "isWindowClosing": false
  }
} common-background-popup-setting.bundle.js:31:6015
CAD_3.3.1 - debug - TabEvents.cleanFromFromTabEvents:  No Alarms detected.  Creating alarm for cleaning...
```

But that's the same output for a domain that is cleaned correctly.

**Comment by kennethtran93** [comment] 2020-05-25 22:02
Best to just filter by CAD_ to get all the info, including if the cookies will be cleaned or not via isSafeToClean and whatnot.

**Comment by kennethtran93** [comment] 2020-05-25 22:06
I'd suggest copying the log into a text file and upload it here for me to diagnose further.  If you are planning on restarting the browser, get the logs beforehand as it doesn't survive restarts.

**Comment by Jerroder** [comment] 2020-05-27 09:50
Cookies are cleared when I close/reopen the browser (they get cleared when I reopen it) but not when I close the tab.

The file is coming.

**Comment by kennethtran93** [comment] 2020-05-27 15:17
> Cookies are cleared when I close/reopen the browser (they get cleared when I reopen it) but not when I close the tab.

Sounds like you are using a greylist for a few things...

**Comment by Jerroder** [comment] 2020-05-27 16:56
I don't have any greylisted item.

To complete my comment, Github's cookies are cleared when I close/reopen the browser while the tab is opened and in the foreground. If the tab is already closed or if I'm in another tab when I close the browser, I'm still logged in (i.e. cookies not cleared).

**Comment by kennethtran93** [comment] 2020-05-28 04:12
Until I read the logs I'm not sure what else to suggest at this time.

**Comment by Jerroder** [comment] 2020-05-28 09:04
I got something there

```
CAD_3.3.1 - debug - TabEvents.cleanFromFromTabEvents:  No Alarms detected.  Creating alarm for cleaning...
common-background-popup-setting.bundle.js:31:6015
CAD_3.3.1 - debug - TabEvents.onTabUpdate: actions will now commence.
{
  "tabId": 23,
  "changeInfo": {
    "attention": false
  },
  "partialTabInfo": {
    "id": 23,
    "windowId": 1,
    "status": "complete",
    "incognito": false,
    "cookieStoreId": "firefox-container-39",
    "url": "https://github.com/",
    "title": "GitHub"
  }
} common-background-popup-setting.bundle.js:31:6015
CAD_3.3.1 - debug - TabEvents.getAllCookieActions:  browser.cookies.getAll for domain.
{
  "partialTabInfo": {
    "id": 23,
    "windowId": 1,
    "status": "complete",
    "incognito": false,
    "cookieStoreId": "firefox-container-39",
    "url": "https://github.com/",
    "title": "GitHub"
  },
  "domain": "github.com",
  "firstPartyDomain": "github.com"
} common-background-popup-setting.bundle.js:31:6015
CAD_3.3.1 - debug - TabEvents.onTabUpdate: actions have been processed and flag cleared.
common-background-popup-setting.bundle.js:31:6015
CAD_3.3.1 - debug - TabEvents.getAllCookieActions:  Filtered Cookie Count
{
  "partialTabInfo": {
    "id": 23,
    "windowId": 1,
    "status": "complete",
    "incognito": false,
    "cookieStoreId": "firefox-container-39",
    "url": "https://github.com/",
    "title": "GitHub"
  },
  "tabURL": "https://github.com/",
  "hostname": "github.com",
  "cookieCount": 11
} common-background-popup-setting.bundle.js:31:6015
CAD_3.3.1 - debug - TabEvents.getAllCookieActions: executing checkIfProtected to update Icons and Title.
common-background-popup-setting.bundle.js:31:6015
CAD_3.3.1 - debug - TabEvents.getAllCookieActions: executing showNumberOfCookiesInIcon.
common-background-popup-setting.bundle.js:31:6015
Error: Invalid tab ID: 23                                                     5 undefined
```

The error is not thrown every time I close the tab, only sometimes. Here, it appeared when I closed the Github tab.

**Comment by kennethtran93** [comment] 2020-05-28 13:55
This just means that the icon badge text holding cookie count didn't have a chance to update before you closed it. Has nothing to do with cleaning of cookies.

This triggers on first complete load/updated as well as when cookies are changed for that domain. Essentially updates the cookie count badge.

**Comment by kennethtran93** [comment] 2020-05-28 13:57
Looks like you are using containers /contextualidentities. Are you using another extension to manage the creation and removal of containers?

Also presume you have container cleaning checked?

**Comment by Jerroder** [comment] 2020-05-28 14:44
> Looks like you are using containers

I do, I thought I mentioned it but I haven't, my bad.

The problem comes from here: if a domain is opened in a [Firefox Container](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/), it doesn't get cleared. I just tried with a domain that was cleared before, to create a new separate container for it and cookies are not cleared anymore. If I open it outside the contained, it's cleared correctly again.

**Comment by kennethtran93** [comment] 2020-05-28 14:56
There is already an issue regarding cleaning on a containers not being cleared if the domain on question is still open on other containers, if that is your issue... 

Somebody had an issue with Facebook containers as well but may be unrelated.

I don't use Facebook container so I'm not sure how it operates. So far just using multi-container Firefox is working fine for me.

If you want you can send the logs my way so I can see if I can find the cause.

**Comment by kennethtran93** [comment] 2020-05-28 14:58
Oddly enough the current addon actually queries and checks all containers even if the clean containers is unchecked, (a bug that will be fixed in the next release.)

First party isolation setting?

**Comment by Jerroder** [comment] 2020-05-28 15:08
> There is already an issue regarding cleaning on a containers not being cleared if the domain on question is still open on other containers, if that is your issue...

But the domain isn't opened in another container, I only have one Github tab and I close it.

> If you want you can send the logs my way so I can see if I can find the cause.

https://send.firefox.com/download/a31c15abeb4b57a0/#NdT7uSiS5I04n8dI_BRKIw

> First party isolation setting?

firstparty.isolate is true in my Firefox config

**Comment by kennethtran93** [comment] 2020-05-28 17:12
Thanks for the logs.  I'm slowly deciphering it as I go.  In the meantime if you're wanting to look somewhere, `CleanupService.cleanCookiesOperation` is where the cleaning of cookies happen.

Normally on tab close (if it is active and after the delay), it triggers `TabEvents.cleanFromFromTabEvents`, which sets an alarm for the delay and executes the function above.  That goes through the list of cookies and (through debug) outputs the reason why it was cleaned/kept.

**Comment by kennethtran93** [comment] 2020-05-28 18:49
Based on the logs you've given me:
GitHub-relevant lines start from 2717 to 3537.  Cookies weren't deleted because on at least one of the open tabs, there was github.com in it.  I have yet to implement container checks on open tabs.

firefox-container-39 seems to be your github.com container or was just the test.  If you've removed that container beforehand, we won't know that and won't do anything to deleted containers as Firefox should be removing it internally. (Well we just call browser.contextualIdentities.query to get a list of all containers, then get all cookies from each container.).

With FirstPartyIsolate, I've committed a patch that removes the 'privacy' permission and uses a workaround for it, which also removes the need to restart the browser if that setting has been changed.  Previously, this setting was only cached at browser startup / extension startup.  With FirstPartyIsolate, we add in firstPartyDomain as undefined so that we get all the cookies regardless of isolation, so that shouldn't be an issue with clearing up cookies.

The only other thing I can say is that the openTabs request is only called once at the start of the cleanup, so there may have been a cleanup that was in progress when you removed the tab, thus those cookies weren't deleted at that time.  I'll need to spruce up the opentab output to get the container and whatnot soon.

**Comment by kennethtran93** [comment] 2020-06-26 19:02
With the release of 3.4.0 which adds the ability to keep container domains separate from each other during cleaning, do you still have this issue?

**Comment by Jerroder** [comment] 2020-06-26 21:00
I do have the 3.4.0 and Github's cookies still aren't cleared, whether it is manually or automatically.

**Comment by kennethtran93** [comment] 2020-06-26 21:47
By manual, is it the manual 'clean' button which triggers the autoclean, the 'clean, include open tabs' or the clean all cookies/localstorage for this domain manual clean?

**Comment by Jerroder** [comment] 2020-06-27 09:19
The first one, the manual "clean" button.

**Comment by kennethtran93** [comment] 2020-06-27 23:28
can you send me the latest logs again from the latest version?

Maybe I was doing it wrong, but here's what I did (in a gif).  I'm running Kubuntu (linux) with Firefox Developer Edition at this time so I'm not sure if it is a OS/browser thing.  Perhaps you could also try doing some sort of screen record to a gif and post it here too?
- privacy.firstparty.isolate = true
- network.cookie.cookieBehavior = 1
- network.cookie.lifetimePolicy = 0

- CAD AutoClean enabled; 10 seconds delay w/ notification and container cleaning.
- Container 'GitHub' freshly created and logged into prior to record.

![Peek 2020-06-27 16-22](https://user-images.githubusercontent.com/6724477/85934049-9bfce680-b892-11ea-8dc7-279d98386079.gif)

**Comment by Jerroder** [comment] 2020-06-28 08:36
I didn't have the option `Enable Support for Firefox's Container Tabs` enabled. I got this notification as soon as I checked it:
`6/28/2020, 10:33:09 AM GMT+2 - 191 Deleted Cookies`

I just tried with github and it works perfectly now!

**Comment by kennethtran93** [comment] 2020-06-28 12:20
I had presumed that was enabled already. Guess I should asked for the full settings list first.

Yes if you're using containers, you need to enable that option. Otherwise it should only clear the default / no container one.

**Closed as completed by kennethtran93** 2020-06-28 12:20 UTC
Labels: support, cannot reproduce
