### ISSUE TITLE
[Bug] I get auto logged out of the sites I whitelisted

### ISSUE THREAD

**Issue by UltimateNovaX** [mrdokenny/Cookie-AutoDelete#706] opened 2020-05-01 10:42 UTC
This hasn't happened until 3.2.0

I get logged out when I reopen browser upon restarting the PC. I'm using Brave.

none of the sites I whitelisted were listed in the cleanup log either.

I tried disabling auto-clean, but the same issue persisted.

**Comment by kennethtran93** [comment] 2020-05-01 15:24
Normally I would get you to fill in the bug report properly using the bug report template.

Nonetheless here's a couple pointers:
- 3.2.0 has chrome localstorage enabled.  As there may not be any localstorage option for each of your expressions, it may have cleaned the localstorage regardless.
- Localstorage items aren't posted in the cleanup log yet as the log is just for cookies at this time, which was the main point of this extension.
- I presumed by disable autoclean you disabled it but then ran the manual cleanup.  Maybe it is the result of above.

Lastly, there's not much support for Brave at this time.  Only Firefox, Chrome, EdgeChromium.  If it is a bug specific to that browser then it will be a very low priority to get it fixed for that browser.

**Comment by UltimateNovaX** [comment] 2020-05-01 15:31
Thanks for not asking me to fill a proper report, I'll have no idea where to start:

- if you're talking about "LocalStorage Cleanup (Firefox 58+, Chrome 74+)?" under cookie settings, mine is unchecked
- on the other hand, my white listed sites under expression all have "Keep Localstorage" checked
- If I had ran the manual cleanup, I would've tested it one more time to verify if that was the cause. I can say for sure no manual cleanup was initiated on my end.

If it works for Chrome, it should work for Brave, as Brave uses generally the same infrastructure, but I'm a laymen at this so I don't know.

Thanks for the help

**Comment by kennethtran93** [comment] 2020-05-01 19:29
If there's no cleanup log on CAD, then it wasn't cleaned by the extension.

If you disabled autoclean, you essentially disabled the main component of this extension, thus if cookies are still deleted then it's from manual action on the CAD or the browser is doing it, then the issue is with Brave or your browser settings.

Note that even if you have whitelisted the sites, it is up to the sites themselves to set and update its cookie expiration times.  If they don't set expiration times, then it is considered a session cookie, usually deleted when session is closed unless browser restores the session on restart.  Browsers will generally automatically purge expired cookies.  This webextension cannot see expired cookies either.

**Comment by UltimateNovaX** [comment] 2020-05-02 10:03
I have no clue what happened.

But I checked the "LocalStorage Cleanup (Firefox 58+, Chrome 74+)?" under cookie settings, and now my local storage is intact.

So...problem solved I guess?

**Comment by kennethtran93** [comment] 2020-05-02 21:48
I wonder if I have a bug somewhere then...

It's a bit weird as localstorage shouldn't be touched if that setting was disabled...

**Comment by kennethtran93** [comment] 2020-05-02 21:53
also if you had just enabled localstorage cleaning, then the localstorage would be instantly emptied anyway...

**Comment by kennethtran93** [comment] 2020-05-02 21:54
If you enabled the cleanup log option in settings then the cookies that CAD cleaned would appear, otherwise no logs would show up.

**Comment by kennethtran93** [comment] 2020-05-02 21:56
I'll close it for now.  If you disable localstorage cleaning, would it still happen again?

**Closed as completed by kennethtran93** 2020-05-02 21:56 UTC
Labels: support, unofficially supported browser

**Comment by UltimateNovaX** [comment] 2020-05-07 23:32
Very sorry I'm bumping this, but after a couple of days of fiddling with the settings, I think I know the cause of this for sure this time:

The very first option, Enable Automatic Cleaning, cleans my whitelisted sites regardless. I didn't want to uncheck it, so I had to extend it to 86400 seconds (1 day), haven't had the problem since (since I don't go for 1 full day without internet-ing).

I'm not sure if this is a bug or an update that was supposed to change it but this is what I'm seeing.

So it wasn't actually about the localstorage cleaning (which I still have on).

**Comment by kennethtran93** [comment] 2020-05-08 02:52
Enable Automatic Cleaning shouldn't run triggers at all until either domain change or tab close.  Whitelisted sites should be kept UNLESS you had changed the localstorage/cookie options for that expression line (or unless the domain/regular expression failed to pick up the domain you wanted to whitelist - navigate to that domain and check the popup to see if your expressions work - the expressions should show up if you configured it properly.  Don't forget domain.com cookies may be deleted if you only whitelist sub.domain.com.

That or your domain does not set cookie expiration so they are treated as session cookies...or the cookie expiration was set too soon and wasn't being returned upon subsequent visits.

There appears to be a bug on mozilla's end whereas webextensions *can* see expired cookies.  Not that it would matter much as it probably would be cleared then.
