### ISSUE TITLE
[FEATURE REQUEST]  Blacklist

### ISSUE THREAD

**Issue by mdziczkowski** [mrdokenny/Cookie-AutoDelete#1288] opened 2021-12-25 13:43 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

There is no functionality to blacklist some cookies and clean automatically the cookies from this list's addressess as soon they appear.

The Graylist should work as a form of a "buffer" and all cookies on it's list should be threated as temporary ones.

### Describe the solution that you'd like

Add such functionality

**Comment by kennethtran93** [comment] 2021-12-25 19:33
Duplicate of #134.

**Closed as completed by kennethtran93** 2021-12-25 19:33 UTC
Labels: duplicate, Feature Request
