### ISSUE TITLE
not deleting cookies on latimes.com

### ISSUE THREAD

**Issue by GeezrRckr** [mrdokenny/Cookie-AutoDelete#540] opened 2019-06-18 03:30 UTC
Have thoroughly read the documentation and am very familiar with how cookies work.  This site is set for Auto-Clean (i.e., not whitelisted nor greylisted), but latimes.com cookie always maintained during the session.  Please respond with steps to resolve.  Thank you.

**Comment by GeezrRckr** [comment] 2019-06-18 03:33
as a f/u, it also doesn't clean when restarting the browser.  hope a solution is available.

**Comment by kennethtran93** [comment] 2019-06-18 08:58
Please ensure you're following the issue template so that we can better drill down the issue.

### Describe the Bug



### Screenshot in which the bug can be seen

### Steps for anyone to reproduce the bug



### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version: 

_Include screenshots of your settings as well as the expression(s) related to site that you are using_

**Comment by hightower5** [comment] 2019-06-18 10:26
AutoDelete and manually Delete doesn't work correctly.

There are a lot of unwanted cookies in "Manage Cookies and Site Data".

Windows 10 x641903
Mozilla Firefox 67.02 x64
Cookie AutoDelete 3.02

The problem seems [Multi-Account Containers](https://support.mozilla.org/en-US/kb/containers) and Removing Cookies and Site Data confirmation.

![Removing Cookies and Site Data confirmation dialog](https://user-images.githubusercontent.com/18751660/59678393-97581980-91cc-11e9-8686-71513036400d.png)

**Comment by chiraag-nataraj** [comment] 2019-06-18 10:39
I'm on Firefox 67.0.2 on Debian. Pristine (new) profile, default CAD settings with the exception of reducing the delay and enabling localstorage cleanup.

Before:

![2019-06-18-063540_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59675660-3d982500-91b5-11e9-8e71-b59bb6d505a7.png)

After:

![2019-06-18-063740_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59675669-4557c980-91b5-11e9-9874-52e620f35cf8.png)

I think the other storage that's being shown there is indexedDB storage or maybe bits of cache or something, but as you can see, the cookies are removed (the counter for cookies is 0).

**Comment by chiraag-nataraj** [comment] 2019-06-18 10:43
@hightower5 and @GeezrRckr, please provide screenshots of before and after you close the tab as well as your CAD settings.

**Comment by chiraag-nataraj** [comment] 2019-06-18 10:46
@GeezrRckr Do you restore the session when you restart the browser? Cookies that are being used by open tabs will not be cleared &mdash; they're only cleared after the tab is closed. So the only way to force things to be cleaned on startup if you're restoring the session is to enable "Clean Cookies from Open Tabs on Startup?".

**Comment by GeezrRckr** [comment] 2019-06-18 11:40
okay, i'll play along...but i gotta say this feels like a fools errand.

![image](https://user-images.githubusercontent.com/51939784/59678905-27fc1d00-9200-11e9-80dd-a537a2e6dc68.png)

![image](https://user-images.githubusercontent.com/51939784/59678968-4104ce00-9200-11e9-8f64-87f292a1ede4.png)

![image](https://user-images.githubusercontent.com/51939784/59679045-71e50300-9200-11e9-97bd-025cde291b60.png)

![image](https://user-images.githubusercontent.com/51939784/59679226-d99b4e00-9200-11e9-8916-111e83bffd95.png)

![image](https://user-images.githubusercontent.com/51939784/59679119-9b059380-9200-11e9-9186-74bcda4c7e58.png)

![image](https://user-images.githubusercontent.com/51939784/59679161-b2dd1780-9200-11e9-895a-0fd47714f3b5.png)

**Comment by GeezrRckr** [comment] 2019-06-18 11:41
@chiraag-nataraj
> @GeezrRckr Do you restore the session when you restart the browser? Cookies that are being used by open tabs will not be cleared — they're only cleared after the tab is closed. So the only way to force things to be cleaned on startup if you're restoring the session is to enable "Clean Cookies from Open Tabs on Startup?".

irrelevant as I always close the tabs after i read articles (latimes.com, et al).

**Comment by chiraag-nataraj** [comment] 2019-06-18 12:09
In your first screenshot, it seems to suggest the only thing stored is local storage for the site? Does it actually show cookies remaining or is it local storage or cache?

**Comment by GeezrRckr** [comment] 2019-06-18 12:16
> In your first screenshot, it seems to suggest the only thing stored is local storage for the site? Does it actually show cookies remaining or is it local storage or cache?

3rd screenshot shows the cookie remaining despite closing the tab.  

i want all latimes.com cookies to be removed asap, as they have an annoying 2 article free/month constraint.  idiotic.

**Comment by GeezrRckr** [comment] 2019-06-18 12:17
net net....if you/someone can tell me if a different setting(s) can help me achieve this, that would be great.  if not, just say so and we can close the thread.  simple.

**Comment by chiraag-nataraj** [comment] 2019-06-18 12:19
> 3rd screenshot shows the cookie remaining despite closing the tab.

Sorry, I meant that one. Hold on, I'm currently investigating (as you saw from my screenshots, I use Firefox, so I had to install Chromium...).

**Comment by chiraag-nataraj** [comment] 2019-06-18 12:26
Cookies are being cleared.

Before:

![2019-06-18-122422_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59681718-172db600-91c4-11e9-98fe-e68e80b93de1.png)

After:

![2019-06-18-122436_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59681733-1e54c400-91c4-11e9-934b-845771b00c43.png)

Only extension is CAD and the only settings I modified are enabling auto-clean and reducing the timeout for auto-clean.

NB: As with the Firefox case, there is a bit of residual storage, but those aren't cookies.

**Comment by chiraag-nataraj** [comment] 2019-06-18 12:29
@GeezrRckr I notice you have notifications enabled. Do you get notifications? Have you tried reading more than 2 articles to see if it complains?

**Comment by chiraag-nataraj** [comment] 2019-06-18 12:30
@hightower5 Please open a new issue so that we can discuss that in a dedicated space. Thanks! :)

**Comment by GeezrRckr** [comment] 2019-06-18 12:39
> Cookies are being cleared.
> 
> Before:
> 
> ![2019-06-18-122422_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59681718-172db600-91c4-11e9-98fe-e68e80b93de1.png)
> 
> After:
> 
> ![2019-06-18-122436_3840x2160_scrot](https://user-images.githubusercontent.com/14947779/59681733-1e54c400-91c4-11e9-934b-845771b00c43.png)
> 
> Only extension is CAD and the only settings I modified are enabling auto-clean and reducing the timeout for auto-clean.
> 
> NB: As with the Firefox case, there is a bit of residual storage, but those aren't cookies.

yes, it's behaving exactly the same for me.  the problem is the remnant of local storage is causing the problem with the article restriction.  once i delete this, it goes away and i can read 2 more articles. 

so how do i get this extension to TOTALLY dump anything 'latimes.com' related?

![image](https://user-images.githubusercontent.com/51939784/59682550-0bb0ae00-9209-11e9-8195-3c089898f1f8.png)

**Comment by GeezrRckr** [comment] 2019-06-18 12:39
> @GeezrRckr I notice you have notifications enabled. Do you get notifications? Have you tried reading more than 2 articles to see if it complains?

what?   'complains' ??

**Comment by chiraag-nataraj** [comment] 2019-06-18 12:47
@GeezrRckr So it _is_ deleting cookies. Okay. So the problem is with the other storage (*not* cookies).

The first step is to figure out what _kind_ of storage that is. Is it indexedDb? Is it localstorage? Is it cache?

From your screenshot above, it seems it's localstorage. CAD doesn't have the ability to clean localstorage in Chrome (it _does_ in Firefox because they added the APIs for it). They recently seem to have added the required API (see #523).

> what? 'complains' ??

Never mind, you already answered my question in your previous response (I meant the article restriction lol).

The solution here seems to be: Use Firefox or wait for #523.

[edit] I can confirm that with enabling localstorage cleaning and automatic cleaning, closing and re-opening the site works for your usecase.

Another alternative, by the way, which is a bit more advanced, is to use [uMatrix](https://github.com/gorhill/umatrix) and set the option to delete local storage for blocked hostnames. You can also block a _lot_ more (like scripts), so I almost never run into these kinds of paywalls anymore.

**Comment by GeezrRckr** [comment] 2019-06-18 13:14
> The solution here seems to be: Use Firefox or wait for #523.

okay, well that's not a surprise given Google's b.s. 'open-source' stance.   read through the link you sent, but not sure what i'm waiting for?  is there some code I need to install (like for Tampermonkey) or is a new rev of this extension on the way that will resolve this?

switching to FF is a non-starter for me. 

thanks.

**Comment by chiraag-nataraj** [comment] 2019-06-18 13:17
> okay, well that's not a surprise given Google's b.s. 'open-source' stance. read through the link you sent, but not sure what i'm waiting for? is there some code I need to install (like for Tampermonkey) or is a new rev of this extension on the way that will resolve this?

You have to wait for a new version of the extension.

> switching to FF is a non-starter for me.

May I ask why? If you care about your privacy (which you apparently do!), pretty much the ultimate combination is:

* the set of resist fingerprinting patches uplifted from Tor
* first-party isolation uplifted from Tor
* containers to segregate your browsing (isolating cookies, local storage, and all that good stuff)
* CAD, uMatrix, Decentraleyes, Temporary Containers, etc

The first three things are built-in to firefox and don't exist in other browsers (minus the Tor Browser, which is built on firefox), and some privacy extensions (such as Temporary Containers) only exist on firefox as well.

**Comment by kennethtran93** [comment] 2019-06-18 21:38
At this point I'm going to close this issue as it relies on #523 getting implemented.

Summary of this issue:
- Cookies ARE being deleted for that site.
- Localstorage cleaning for Chrome is not implemented yet (duplicate of #523).

**Closed as completed by kennethtran93** 2019-06-18 21:38 UTC
Labels: duplicate

**Comment by RyanTG** [comment] 2019-06-25 19:16
I know this is closed. But I'm experiencing this same issue, but in Firefox (67). The cookies are being deleted, but I guess localstorage isn't. Or perhaps the LA Times is just getting savvier about fingerprinting?
