### ISSUE TITLE
Are the white and grey list synchronized between firefox browser ?

### ISSUE THREAD

**Issue by chmike** [mrdokenny/Cookie-AutoDelete#224] opened 2017-11-05 14:04 UTC
I'm using firefox synchronization and I had the impression that the white list is not synchronized. It could be due to a delay in the synchronization taking place in the background.

What is the status about white list synchronization among synchronized firefox browsers ?

**Comment by chiraag-nataraj** [comment] 2017-11-08 00:10
From what I understand, the grey and white lists are currently not synced. I think there needs to be a `services.sync.extensions.<blah>` preference added? I know that's what uBlock0 does (or did). Although...I have no idea if that's possible anymore with WebExts.

**Comment by chiraag-nataraj** [comment] 2017-11-08 00:14
Okay, I know uBlock Origin (https://github.com/gorhill/uBlock) and uMatrix (https://github.com/gorhill/umatrix) both figured this out, and they're both on WebExt, so this should be doable (although I don't think it's through adding a preference at this point...).

**Comment by ghost** [comment] 2017-11-08 00:25
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync

**Comment by ke-d** [comment] 2017-11-14 00:14
Duplicate of #30

**Closed as completed by ke-d** 2017-11-14 00:14 UTC
