### ISSUE TITLE
[BUG]  - Facebook cookies are not deleted after tab is closes (Chrome, osx)

### ISSUE THREAD

**Issue by replay111** [mrdokenny/Cookie-AutoDelete#666] opened 2020-03-21 20:39 UTC
I do not have FB on whitelist, but when I am closing tab with FB and then creating new one and going to the FB site - I am still logged and cookies are still present

**To Reproduce**

1. new tab - login to fb
2. close tab with fb
3. new tab - type fb address -> already logged on :/

**Expected behavior**

Expected as with other sites - after closing tab - all cookies related with site that was justo closed, should be deleted

**Screensh
 - OS: Mac OS
 - Browser Info: Chrome 80.0.3987.149 64bit
 - CookieAutoDelete Version: 3.1.0

**Comment by kennethtran93** [comment] 2020-03-21 22:14
There was an issue for auto cleaning in 3.1.0 that should have been resolved in 3.1.1.  Please let me know if it wasn't resolved with that one.

**Comment by kennethtran93** [comment] 2020-03-21 22:33
Just checked - Version 3.1.1 in Chrome is still under review.

**Comment by kennethtran93** [comment] 2020-03-22 16:36
Closing as duplicate of #658. If this is still an issue after Google Chrome releases the 3.1.1 update please let me know.

**Closed as completed by kennethtran93** 2020-03-22 16:36 UTC
Labels: duplicate

**Comment by replay111** [comment] 2020-03-22 19:35
After using 3.1.1 cookies are deleted as expected ;) Thanks!
