### ISSUE TITLE
Feature Request : Synchronisation

### ISSUE THREAD

**Issue by TheSiliconProjects** [mrdokenny/Cookie-AutoDelete#493] opened 2019-01-28 08:46 UTC
Hello,

Thanks for your great job.

Could you add two parameters :
 - App settings synchro
- white/grey lists synchronization

Through Firefox account ?

As Mozilla has some restriction in data size backup, fro White/ Grey list one good solution could be to synchronize through a local directory on computer. So one could use Onedrive, Google drive, Dropbox... to synchronize across devices. This could be also done for apps parameters....

I am experiencing a lot of problem with Firefox account synchronization due to some limitations relatedf to server bandwitdh.
I have many time experienced loss of data, or data not saved (i.e. for Ublock Origin etc etc)

As a contrary Chrome synchronization through Google account works 1000 times far better, probably due to the exceptional relibaility of Google cloud.
So the  option to not use Firefox account (a real bullshit), but to use instead a local directory included in any cloud client synchronization could be far better.

Thanks

David

**Comment by kennethtran93** [comment] 2019-02-14 06:20
Most likely duplicate of #30.

**Comment by ke-d** [comment] 2019-02-16 04:24
Duplicate of #30

**Closed as completed by ke-d** 2019-02-16 04:24 UTC
Labels: duplicate
