### ISSUE TITLE
Where is the data stored?

### ISSUE THREAD

**Issue by ineuw** [mrdokenny/Cookie-AutoDelete#586] opened 2019-11-12 03:20 UTC
Where is the data storage of the user's changes? When creating a new profile, all the settings created by the user are lost.

- OS/version: Windows 10, Linux Mint 19.2
- Browser/version: Firefox 70.0.1
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment] 2019-11-12 03:29
Data storage of settings asked per #429; the core settings is not available for extract yet.  you'll need to take a screenshot of that.

The expressions can be exported.  However if containers are used it may not re-import properly.  It's on my list of things to do but time isn't readily available / in excess.

There is no sync function implemented yet.

**Comment by ineuw** [comment] 2019-11-12 03:33
Thanks for the speedy reply.

I am not using container tabs. Does this make a difference?If not, I will
just have to wait. :-)

ineuw

**Comment by kennethtran93** [comment] 2019-11-12 03:35
you will just have to try to export the expressions and import them to the new profile and see if it works for you.  Other settings needs to be manually matched.

**Comment by kennethtran93** [comment] 2019-11-13 03:12
Closing per duplicate of #429.

**Closed as completed by kennethtran93** 2019-11-13 03:12 UTC
Labels: duplicate, enhancement
