### ISSUE TITLE
[FEATURE REQUEST] Replace two terms with less sensitive words

### ISSUE THREAD

**Issue by Ruehrfisch** [mrdokenny/Cookie-AutoDelete#1145] opened 2021-05-17 10:34 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

I was pleased to see that it is becoming more and more popular to think about the meaning of words. Even government agencies are doing this (https://www.zdnet.com/article/uk-ncsc-to-stop-using-whitelist-and-blacklist-due-to-racial-stereotyping/).
It would be nice if the words "whitelist" and "greylist" could be renamed to get rid of the problem with stereotyping, to make the world a better and more inclusive place bit by bit.

### Describe the solution that you'd like

"Whistelist" could be rephrased as "allow-list".
"Greylist" could be rephrased as "temporary allow-list".
"Blacklist" could be rephrased as "deny-list".

**Comment by kennethtran93** [comment] 2021-05-17 12:33
Duplicate of #754

**Closed as completed by kennethtran93** 2021-05-17 12:33 UTC
Labels: duplicate, Feature Request
