### ISSUE TITLE
[FEATURE REQUEST]  Delete Download History

### ISSUE THREAD

**Issue by Wolf-lbh** [mrdokenny/Cookie-AutoDelete#1595] opened 2023-09-03 06:48 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

I don't like that I have to manually remember to clear my download history and I love that every website not on my whitelist clears its own browsing history.

### Describe the solution that you'd like

I'd like a setting to delete my download history (not the file itself, just the browser record that I downloaded it) from my browser, specifically Brave (Chromium).

### Describe alternatives you've considered

Firefox had an addon for this but Chromium browsers do not so I'm kinda sol now that I switched to Brave.

**Comment by kennethtran93** [comment] 2023-09-16 05:26
Bumping the issue will not make it implemented faster.  Technically still a duplicate of your original issue.  If you are updating the issue you can do it in your original one or just as a comment in your original request.

Duplicate of #1281.

**Closed as not planned by kennethtran93** 2023-09-16 05:26 UTC
Labels: duplicate, Feature Request
