### ISSUE TITLE
[BUG]  Harmful language

### ISSUE THREAD

**Issue by AO-LocLab** [mrdokenny/Cookie-AutoDelete#973] opened 2020-11-23 15:31 UTC
Describe the bug

**Harmful language**

Throughout Cookie Autodelete, we find the term “White List”, a term which should no longer be used and be replaced. 

**To Reproduce**

**Expected Behavior**

**Replace “white list” with an appropriate term**

An appropriate replacement term should be chosen, possibly from:
https://inclusivenaming.org/language/word-list/

**Your System Info**

- CookieAutoDelete Version: 3.5.1

**Comment by kennethtran93** [comment] 2020-11-23 17:31
Closing as Duplicate of #754.

**Closed as completed** 2020-11-23 17:31 UTC
Labels: duplicate, untested bug/issue
