### ISSUE TITLE
Delete cookies and localstorage on tab close

### ISSUE THREAD

**Issue by iinc** [mrdokenny/Cookie-AutoDelete#246] opened 2017-11-16 00:33 UTC
Self-Destructing Cookies had this feature but it is now a legacy extension and Cookie-AutoDelete was recommended as a replacement.

"Gets rid of a site's cookies and LocalStorage as soon as you close its tabs."

**Comment by chpio** [comment] 2017-11-16 13:15
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44

**Comment by ke-d** [comment] 2017-11-19 07:21
Duplicate of #44

**Closed as completed by ke-d** 2017-11-19 07:21 UTC
Labels: duplicate
