### ISSUE TITLE
search list of expression

### ISSUE THREAD

**Issue by ryker66** [mrdokenny/Cookie-AutoDelete#435] opened 2018-08-18 10:22 UTC
I have a long list of expressions--is there a way to search them,  it is really tedious to try and go through them to look at each one. on the list of expressions page. 

Thanks<!--

**Comment by ke-d** [comment] 2018-09-04 15:37
Duplicate of https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/120

Alternative is to use Control + F

**Closed as completed by ke-d** 2018-09-04 15:37 UTC
Labels: duplicate
