### ISSUE TITLE
[REQUEST] Add "Blacklist" option beside Greylist and Whitelist

### ISSUE THREAD

**Issue by Existencielle** [mrdokenny/Cookie-AutoDelete#450] opened 2018-10-17 17:53 UTC
I would find it very helpful if you could add domains to a Blacklist the same way that you currently can add them to a Greylist or Whitelist. (upon clicking on the Cookie-AutoDelete icon)

The effect of that Blacklist should be that cookies will be deleted (after the set delay) even if the tab is still open.

**Comment by ke-d** [comment] 2018-11-08 01:47
Duplicate of #134

**Closed as completed by ke-d** 2018-11-08 01:47 UTC
Labels: duplicate
