### ISSUE TITLE
Not possible to "whitelist" only some Cookies of a site / domain without protect all of them

### ISSUE THREAD

**Issue by LaurentGrenet** [mrdokenny/Cookie-AutoDelete#164] opened 2017-09-29 18:38 UTC
When you create a WhiteList, ALL cookies belonging to this site / domain are "protected", while in several cases, we'd like to protect some of them, and to have others deleted.
Eg, protect cookies allowing automatic login, but delete all other cookies used by the site to track you...

Suggestion : be able to specify in WhiteList (a/o GreyList) not only the website, but also names of cookies to preserve

**Comment by ke-d** [comment] 2017-09-29 23:30
Duplicate of #68

**Closed as completed by ke-d** 2017-09-29 23:30 UTC
Labels: duplicate
