### ISSUE TITLE
[FEATURE REQUEST]  Firefox Multi-Account Containers: 'Switching' cookies between containers

### ISSUE THREAD

**Issue by TheMuffinPony** [mrdokenny/Cookie-AutoDelete#624] opened 2020-02-16 23:58 UTC
**The request**

"Switching" cookies between containers is very hard, and can be made simple.

Example: Let's say that I've signed in to a few different Google accounts (personal, work, school, etc) in one container.  I want to move all of these into my "personal" container tab and blacklist Google on my default container (for privacy reasons).  However, that's hard: I either have to export my cookies from one container and re-import them into another, or sign back in again to the accounts all over again (which can get repetitive if passwords aren't saved and/or 2FA is enabled).

**Is your feature request related to a problem? Please describe.**

It's more of a convenience issue than a problem.

**Describe the solution you'd like**

If there are no API limitations, a simple option to "migrate rule and cookies affected to new container" next to each rule could fix this.  To use it, you click the link/button, select a new container, select whether I also want to copy cookies, and then click "transfer."  The rule is copied over to the new container, and so are all cookies for websites affected by that rule.

**Describe alternatives you've considered**

This is a problem with CAD, and can be fixed very easily.  The alternatives mentioned earlier (exporting and importing cookies or signing back in) work, but can be much more time-consuming.

**Comment by kennethtran93** [comment] 2020-02-17 03:03
While I can understand the import/export of rules into new containers as there's a previously requested issue not too long ago (#617) and possibly others beforehand, I think the copying of cookies may be slightly outside the main features of this webextension which is to **_remove_** unwanted cookies (and other site data).

I'm not saying that it won't be worked upon, but it will be slightly lowered in terms of priority (at least the cookie copying part).

**Comment by zdat** [comment] 2020-02-29 09:55
> **Describe alternatives you've considered**
> 
> This is a problem with CAD, and can be fixed very easily. The alternatives mentioned earlier (exporting and importing cookies or signing back in) work, but can be much more time-consuming.

Can you explain/link how this is done through exporting & importing? I really need this right now and I can't see a way.

**Comment by kennethtran93** [comment] 2020-04-09 01:24
Apologies for the late response.  It's been some hectic times.

If you haven't exported your original list yet, do so now as for the time being we're using Firefox's internal names and not the display name that you had set.  Also make sure that the container you want to import expressions to has at least one expression in it so you can copy over the store id and container id.

Once you exported your list, then change the container id (the parent group id) and store id of the ones you want to add to the new container to match the container id you would like to import to.  

Note that importing  will NOT remove existing expressions.  You'll need to delete those manually if you don't need them in that container anymore.

Basic Import documention is here:  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#importing-expressions

**Comment by kennethtran93** [comment] 2020-04-17 03:17
Just checking in - did the documentation help (for moving expressions) or were you wondering about moving actual cookies from one container to another?

**Comment by kennethtran93** [comment] 2020-05-06 04:56
I'm going to close is a duplicate of #617 as that was opened earlier.

**Closed as completed by kennethtran93** 2020-05-06 04:56 UTC
Labels: duplicate, Feature Request
