### ISSUE TITLE
[BUG]  ??? Not all is deleted

### ISSUE THREAD

**Issue by superpoincare** [mrdokenny/Cookie-AutoDelete#1063] opened 2021-02-25 20:30 UTC
I used a fresh install of Google Canary and this extension. 

After visiting zdnet.com, and closing the tab and waiting, I still see these:

![image](https://user-images.githubusercontent.com/13736892/109213071-30c73380-77d6-11eb-973e-3d59c9a4c596.png)

Others were cleared as the log shows, but not the above.

![image](https://user-images.githubusercontent.com/13736892/109213203-548a7980-77d6-11eb-83b9-b5f1e59ef83f.png)

**Comment by kennethtran93** [comment] 2021-02-25 20:34
What is your setting/configuration for CAD?

**Comment by superpoincare** [comment] 2021-02-25 20:51
Attaching: 

[settings.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/6045686/settings.txt)

**Comment by kennethtran93** [comment] 2021-02-25 21:42
Some notes:  I primarily develop this using Firefox browser, and majority of the APIs are compatible.  That being said, Chrome's API has additional cleanup options that firefox do not have yet, and those additional cleanups have yet to be implemented in CAD (an issue was already created for this a while back).  Cache Storage is one of them, as it is NOT the same as cache.

This is what chrome has: https://developer.chrome.com/docs/extensions/reference/browsingData/#type-DataTypeSet
This is what firefox has: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/DataTypeSet.

As for the one that says lightboxcdn, if the third party site did not set a cookie, there's no way for us to know about it.  We can only know via cookies (and that's why we set our own cookie for each site you visit).

In order to actually know all third-party domains that were accessed, I would need an additional permission to view webrequests.  I suppose this permission is justified where we would be able to look at all web requests, and set cookies for each domain accessed to remove third-party domains.

So realistically this is not a bug as cleanups for those data types aren't implemented yet.  Thus, I will be closing this as such.  Feel free to upvote the feature request about the additional chrome data types that could be cleaned.

**Closed as completed** 2021-02-25 21:46 UTC
Labels: not a bug / expected behavior, Google Chrome

**Comment by superpoincare** [comment] 2021-03-01 21:01
After reading your comments in other issues, I'd imagine that Firefox is the browser for which you have primarily developed this and you don't want code which is browser specific as it will be difficult to maintain. 

But just like we write javascript with feature detection, can't you first check the condition to see if the option to delete exists in the api and then execute the line if so. This way, your statements would be browser independent and you don't have to worry about maintenance.

**Comment by kennethtran93** [comment] 2021-03-01 21:13
I have some form of feature detection on already, primarily detecting browser types.

The blocking point of this at this time is that I would need to redesign how each expression option will look, otherwise it will be a very long line of site data options listed per expression.
