### ISSUE TITLE
[Bug]  LocalStorage will not be cleaned when cookie is empty

### ISSUE THREAD

**Issue by woyaojizhu8** [mrdokenny/Cookie-AutoDelete#1414] opened 2022-06-27 15:58 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

I have found that when cookie is empty but LocalStorage is not empty in a domain of a tab, after I click  'clean, include open tabs', LocalStorage will not be cleaned even if I have enabled the LocalStorage  Support.

### To Reproduce

1. Go to [https://www.bilibili.com/video/BV1bB4y147Yy](url) .
2. Open Development Tools , and go to the Storage Inspector tab.
3. In the left panel in Development Tools, open LocalStorage -> https://s1.hdslb.com, then add some items .
4. Click the Cookie Autodelete  button in browser toolbar, and under the "CLEAN" tab the first presented function is the "Clean, include open tabs" button. Click this button. 

### Expected Behavior

The LocalStorage in https://s1.hdslb.com is cleaned

### Screenshots

![2022-06-27 23-51-48屏幕截图](https://user-images.githubusercontent.com/16593993/175981697-81d524a3-1828-41c3-b37c-2fafaeb314e7.png)

### System Info - Operating System (OS)

Ubuntu 22.04

### System Info - Browser Info

Firefox 101.0.1

### System Info - CookieAutoDelete Version

3.8.0

### Additional Context

If I add some items in the cookie of https://s1.hdslb.com ( the left panel in Development Tools -> cookie ->  https://s1.hdslb.com ) and then click  'clean, include open tabs', the LocalStorage of https://s1.hdslb.com will be cleaned.

**Comment by kennethtran93** [comment] 2022-06-29 05:54
Closing as duplicate of #599.

This is currently expected as we can only iterate cookies to find the domain - nothing from any other browsing data types can be queried.  Due to this, we currently can only clean up items that have a least one cookie created for that domain.  We normally create our own cookie for all visited domains (first-party only).  Also at this time, we have _not_ requested the permissions to read all web requests yet, but that would be the permission we would need in order to simultaneously create a cookie for each domain found in all web requests.

**Closed as not planned by kennethtran93** 2022-06-29 05:54 UTC
Labels: duplicate, untested bug/issue
