### ISSUE TITLE
Cookies are not deleted when the tab is closed

### ISSUE THREAD

**Issue by Milaleda** [mrdokenny/Cookie-AutoDelete#284] opened 2017-12-10 21:09 UTC
### Describe the Bug/Feature

When a tab is closed the related Cookies are not deleted. Only when a next tab is closed these cookies are deleted.

1st Case: 1st tab :Google, 2nd tab: preferences, 3rd tab: empty.
Cookie of Google is not shown in toolbar icon. When 1st tab is closed, nothing happens. Only when 2nd or 3rd tab are closed the cookies of the 1st tab are deleted.

2nd Case: 1st tab :Github, 2nd tab: preferences, 3rd tab: empty.
Cookies of Github are shown in toolbar icon. When 1st tab is closed, nothing happens. Only when 2nd or 3rd tab are closed the cookies of the 1st tab are deleted.

### Screenshot in which the bug can be seen

1st case:

![bildschirmfoto vom 2017-12-11 07 03 39](https://user-images.githubusercontent.com/34424728/33817798-b9a57d42-de41-11e7-90a4-3b6b322c7371.png)

![bildschirmfoto vom 2017-12-11 06 59 38](https://user-images.githubusercontent.com/34424728/33817807-c259218c-de41-11e7-9d04-22b545cfe04f.png)

![bildschirmfoto vom 2017-12-11 07 10 41](https://user-images.githubusercontent.com/34424728/33817936-8bbf21a2-de42-11e7-92a1-3de1036ad852.png)

2d case:

![bildschirmfoto vom 2017-12-11 07 04 39](https://user-images.githubusercontent.com/34424728/33817814-cc15623a-de41-11e7-8a81-eba7771ff973.png)

![bildschirmfoto vom 2017-12-11 06 58 43](https://user-images.githubusercontent.com/34424728/33817821-d63bda78-de41-11e7-9b5a-df39b779afd7.png)

![bildschirmfoto vom 2017-12-11 07 11 32](https://user-images.githubusercontent.com/34424728/33817962-aa6e993e-de42-11e7-817f-2c10c0553e2e.png)

### Steps for anyone to reproduce the bug

This bug also occurs immediately after creating a new profile and instantly installing Cookie-Autodelete

### Your settings 

- OS/version: Linux Mint Cinnamon 17.3
- Browser/version: Firefox 57.0.1
- Cookie AutoDelete version: 2.01

In the preferences of Cookie-AutoDelete the automatic cleaning with no delay is aktivated.

**Comment by captainepoch** [comment] 2017-12-15 08:29
It also happens when the "Delay Before Cleaning" is set to 0, it doesn't delete cookies

**Comment by Milaleda** [comment] 2017-12-15 09:30
Yes, this parameter is set to "0" and cookies are not deleted immediately. When the next open tab is closed, then the cookies of the tab closed before are deleted.

**Comment by kiwiG** [comment] 2017-12-21 21:02
I get exactly the same behaviour as Milaleda and Self-Destructing Cookies is _not_ installed.

**Details**
OS/Version: 
- Mac OS/X 
- Sierra (10.12.4)
- Firefox: 57.0.1
- Cookie Autodelete: version 2.0.1

Ticked: "Enable Automatic Cleaning? Delay Before Cleaning 0 Minutes"

**Comment by ke-d** [comment] 2017-12-28 17:15
Duplicate of #223. Should be fixed in latest beta.

**Closed as completed by ke-d** 2017-12-28 17:15 UTC
Labels: duplicate
