### ISSUE TITLE
Popup shows that cookies are deleted but they are not

### ISSUE THREAD

**Issue by fw190** [mrdokenny/Cookie-AutoDelete#188] opened 2017-10-15 19:22 UTC
### Describe the Bug
After setting up the system with all of the configs as here:
https://www.privacytools.io/ and adding up uBlock,uMatrix, Decentraleys and Canvas Blocker I get a pop up that cookies were deleted but when looking up about:preferences#privacy I can observe that they are still there. Also the icon shows 0 cookies for a specific page but they are set.

### Steps for anyone to reproduce the bug
Cookies in Firefox are set to:
Accept cookies from websites; yes
accept third party: never
keep until I close firefox: yes
Clear history when firefox closes: yes

### Your settings 

- OS/version: Solus
- Browser/version: Firefox 56
- Cookie AutoDelete version: Latest

**Comment by ke-d** [comment] 2017-10-15 21:07
Duplicate of #75

**Closed as completed by ke-d** 2017-10-15 21:07 UTC
Labels: duplicate
