### ISSUE TITLE
[FEATURE REQUEST]  

### ISSUE THREAD

**Issue by koolx** [mrdokenny/Cookie-AutoDelete#819] opened 2020-08-01 19:28 UTC
Hi kenneth,

Hope youre doing well. My eyes hurt everytime I go into the settings with all white background. The same thing with the popup window when I click the CAD icon. Its blinding white. Please make them dark mode with dark background and white font. Most addons are going into dark mode as I imagine you know. 

Not sure if this helps but I did manage to use CSS to darken these elements in case you're interested I can share the CSS code with you then that way you may implement them into the next update. Let me know!

**Comment by kennethtran93** [comment] 2020-08-01 22:37
Duplicate of #806.  

Feel free to create a PR request anytime, though if this was the case an option will need to be added to allow toggle of dark mode.  

> Most addons are going into dark mode as I imagine you know.

Interesting, not that I know that yet.  NoScript doesn't appear to have dark mode yet either, in addition to the screenshot and adblocker extensions that I'm using at this time.

**Closed as completed by kennethtran93** 2020-08-01 22:37 UTC
Labels: Feature Request

**Comment by koolx** [comment] 2020-08-01 23:30
No problem. 

Theres a big push for dark mode for android, iphone and windows based applications.
