### ISSUE TITLE
Feature: seeing recently added cookies to easily add to whitelist

### ISSUE THREAD

**Issue by Narvey** [mrdokenny/Cookie-AutoDelete#227] opened 2017-11-07 21:08 UTC
I use Cookie-AutoDelete to basically say "I hate cookies, except those logins I choose to keep".  I think this is what the purpose of the whitelist is, but it is a pain to know what to put in if session cookies are not named after the site they are from, or if the site they are from does tons of other (evil) cookies as well (Google is a perfect example).

Could you make it so that we could browse to the site, login, and then immediately open Cookie AutoDelete settings and see the last few added cookies, and then click a button next to one to add it to the whitelist?

**Comment by ke-d** [comment] 2017-11-14 00:25
C-AD doesn't support individual whitelisting of cookies only domains. Duplicate of #68

**Closed as completed by ke-d** 2017-11-14 00:25 UTC
