### ISSUE TITLE
[SUPPORT] How to delete Local Storage a/o IndexedDB for all Sites NOT matching any rule

### ISSUE THREAD

**Issue by LaurentGrenet** [mrdokenny/Cookie-AutoDelete#1416] opened 2022-06-28 06:42 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Hi,

for any website for which a rule exists, it's quite easy to parameter this rule to keep only some cookie, but delete automatically all other cookies and choose to delete or to keep Local memory and/or IndexedDB and/or Cache and/or...

On the other hand, for website for which there is NO matching rule (neither White nor Grey), all cookies relative to this website are automatically cleaned by CAD when leaving the website.
But I've not been able to have Local Memory or IndexedDB or Cache cleaned for these websites without any matching rule.

But maybe I didn't catch something...
So my question : Is there a mean to ask CAD to automatically delete Cache and/or Local data and/or IndexedDB and/or ... for all websites that do not match with any rule, on the same way it deletes all cookies for these sites.

Thanks in advance for your help !
Regards
Laurent

**Comment by LaurentGrenet** [comment] 2022-06-28 18:44
Sorry, I did a mistake. 
For websites NOT matching any rule, local data and indexedDB seem to be correctly purged as well. Not only cookies.

I've been led to my mistake because it remain nevertheless (at least in some cases) A LOT of storage data for the site. But it seems to be another kind of data.
BTW if you could have a look here : https://support.mozilla.org/fr/questions/1381100 pls do not hesitate to add complementary explanations... if you have !

**Comment by kennethtran93** [comment] 2022-06-28 20:20
Closing as duplicate of #1415 - your discussion. See relevant answer there.

**Closed as completed** 2022-06-28 20:21 UTC
Labels: duplicate, support
