### ISSUE TITLE
[FEATURE REQUEST]  Option to delete greylist cookies

### ISSUE THREAD

**Issue by Mautzimann** [mrdokenny/Cookie-AutoDelete#1641] opened 2024-08-31 14:46 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

no

### Describe the solution that you'd like

Case 1: When I activate "Clean greylisted at Browser startup", cookies of greylisted domains only will be deleted at Browser startup, not at manually cleanup. 
Case 2: In other case (no clean greylisted at Browser startup) the behavior is the same as whitelisted cookies (as correctly described in documentation). 
That means, IMHO greylisting has no effect in case 2. 
For case 2 it would be nice to have an icon-/ popup-menu-option to clear all greylisted cookies manually.

**Comment by kennethtran93** [comment] 2024-11-02 02:53
Duplicate of your own feature request #1588 .

**Closed as not planned by kennethtran93** 2024-11-02 02:53 UTC
Labels: duplicate, Feature Request
