### ISSUE TITLE
Here we go again! CAD Not Remembering Cookies.. 2 Issues

### ISSUE THREAD

**Issue by koolx** [mrdokenny/Cookie-AutoDelete#608] opened 2020-01-16 04:57 UTC
Hi Kenneth.. I got 2 issues with CAD which shouldnt be an issue given the nature of the addon.

1) Why is CAD unable to refuse unwanted cookies. I whitelist (keep) cookies from 40 sites. For some crazy reason Home Depot is a cookie CAD decided to keep. Why is that and how do I fix it? 

2) Theres a few site I dont visit regularly but whose cookies I keep. When I try to log into those sites CAD doesnt remember them. How come and how do I fix this?

.

**Comment by kennethtran93** [comment] 2020-01-18 00:13
1. Gonna need some screenshots of your settings and the cleaning logs. 

2. Try using Firefox's Dev Tools to track down which cookie/url that site uses.

**Comment by koolx** [comment] 2020-01-18 05:19
Hi Kenneth. Greatly appreciate the prompt response. 

For question #1 here's my screenshot of my settings...

![2](https://user-images.githubusercontent.com/8130105/72659000-ddee3c00-3986-11ea-80b3-353c012e7309.png)

.
.

For questions #2 heres a screenshot of the cookie from the site www.onewife.com...

![3](https://user-images.githubusercontent.com/8130105/72659075-17737700-3988-11ea-994a-f396acc0ce7f.png)

**Comment by kennethtran93** [comment] 2020-01-18 06:28
1. You'll need to enable the log option and check the cleanup reasons why it wasn't deleted (that is, after redoing whatever you did).
2. Same with above and check why it was deleted, if it was done by CAD, and may need your whitelist (just screenshots relating to those whitelisted ones will do i.e. the CAD popup).

Also a note for (2), unless you have session restore enabled in Firefox which restores opened tabs before you closed it including that one above, those 'session' cookies generally expire/deleted by Firefox itself on browser restart (or when Firefox normally closes I guess).  Session cookie retaining is what we do not have control over.

**Comment by koolx** [comment] 2020-01-18 06:48
Hi Ken...

1. So youre saying I should check 'Enable Cleanup Log and Counter'? 

2. For session cookies, I visited onewife.com only once. I deleted that cookie and dont have it as an open tab when I start firefox. Yet firefox still retains it. How is that possible? 

.

**Comment by kennethtran93** [comment] 2020-01-18 08:08
1) Yes to see if CAD has parsed through that URL and to see its reason why clean/not clean.  You can disable it afterwards once at least a cleaning cycle has shown its results relating to that URL/cookie.

2) How did you delete that cookie?  I am unsure how the internal cookie cleanup mechanisms of Firefox work.  Assuming it shows up in the Firefox cookie/storage count?

**Comment by koolx** [comment] 2020-01-18 09:47
Hi ken. I deleted that cookie by going into settings > privacy and security > cookies and site data > manage permissions and looked it up the list of cookies. Then I deleted it.

But as I said, even when I did that and restarted firefox the cookie would reappear in the list again.

**Comment by kennethtran93** [comment] 2020-01-19 03:59
Cookie appears even when you don't visit that site?

**Comment by koolx** [comment] 2020-01-21 19:49
Hi kenneth.. excuse my late reply to your question. To answer your question, when I delete the cookie and restart firefox, the cookie comes back. This is happening with several other cookies from other sites. I dont get it. 

Heres a screenshot of the list of cookies CAD deleted. One of them is onewife.com which it states has been deleted. But it still comes back when check in settings. What should I do?

![2](https://user-images.githubusercontent.com/8130105/72838444-46c30600-3c5e-11ea-8030-c2ec292fd3a8.png)

**Comment by kennethtran93** [comment] 2020-01-23 07:00
Can i also get the expanded entry when you click on the onewife cookie log?

Are there other webextensions that may be causing this to happen?

By chance did you enable any sort of notifications for that site?  Firefox seems to be pushing out a different way that notifications will have to be enabled/pushed.

Also need your OS and Browser+Version.

**Comment by koolx** [comment] 2020-01-27 21:37
Hi Kenneth. Sorry for the wait for my response. Below is a pic of onewife.com cookie log expanded as you requested. 

I've disabled all addons and the issue still persists.

There are no notifications enabled. I've enabled the feature to block new requests asking to allow notifications.

I'm on Win 10 64 bit and firefox 72.0.2 64 bit. 

![1](https://user-images.githubusercontent.com/8130105/73216108-5a211600-4123-11ea-9fd6-572c94e08c22.png)

**Comment by koolx** [comment] 2020-02-01 20:59
Hi Ken.. I posted my reply days ago. Hope you get the chance to read and comment on it. Thanks, Ken!

**Comment by kennethtran93** [comment] 2020-02-01 21:50
Hi @koolx,

Clarifying the issues here:

We're currently discussing 1) which is CAD refusing to remove unwanted cookies.  You had initially mentioned Home Depot then went to onewife halfway down (though you had referred that site to your 2nd issue.

2nd issue was CAD not remembering cookies set.  I think this was resolved as 'expected' due to the fact that it is a session cookie set by that site.


> 
> 
> Hi Ken...
> 
>     2. For session cookies, I visited onewife.com only once. I deleted that cookie and dont have it as an open tab when I start firefox. Yet firefox still retains it. How is that possible?
> 
> 
> .

Can you please clarify your stance on both issues at this point in time?

Thanks,

**Comment by koolx** [comment] 2020-02-02 06:04
Hi Ken. I made a mistake. The cookies are not stored in firefox after all. I read the info wrong in the settings. As you can see from the screenshot below there are no cookies associated with onewife.com, for example. So thats no problem. But It does show storage with the site which circled in red. How do I make sure firefox doesnt store any storage from that website? 

![1](https://user-images.githubusercontent.com/8130105/73603954-b8049200-4557-11ea-9c16-85e8ddc446ee.png)

**Comment by kennethtran93** [comment] 2020-02-02 06:30
Unfortunately there's no easy way.  From your options screenshot you have localstorage cleanup enabled.  CAD should have cleaned it up when clearing up cookies which leaves the non-persistent storage which Firefox cleans up when space is needed.  While indexedDB storage is available to be cleaned, it doesn't appear (from the documentation) that it is doable by host which is what this extension goes by.

There were other issues related to this that all have similar responses at this time.

If this part of the issue is the last one then it will soon be marked as browser limitation.

**Comment by koolx** [comment] 2020-02-02 06:34
Hi Ken. So in other words what youre saying is that CAD cannot clean up the non-persistent storage since its a limitation. Is this right?

**Comment by kennethtran93** [comment] 2020-02-02 22:47
In short, yes it is a limitation.  When non-persistent storage / indexedDB is clearable by host via WebExtension API, then we'll look into it.

**Comment by koolx** [comment] 2020-02-03 00:48
Thank you for letting me know Ken!

**Comment by koolx** [comment] 2020-02-03 02:00
Hi Ken. I dont think we fully resolved the issue of CAD not remembering cookies. For example, when I haven't visited a site in a month, I have to re-enter my username and password again. CAD forgets username and password. is there a fix to this?

**Comment by kennethtran93** [comment] 2020-02-04 03:11
That may be due to the host site setting the cookie to expire after a certain amount of time, like a month after last accessed, most likely for security reasons.  If you were to log in more frequently then most likely they would update the cookie expiry so that it would expire after a month or less since your last login.  If the cookies expire, then they may be automatically purged by Firefox itself.  You'll need to look at that cookie specifically and see if there is an expiry set.  It is not CAD that forgets the cookies - rather Firefox itself.  We only process the list of cookies either on startup, tab close, or domain change.  If the cookie is deleted by us on startup, it would generate a cookie log entry.

At this time CAD doesn't check expiry or whether it is a session cookie at this time.

If the example onewife above is the cookie you wish to keep, that may be not possible as it seems it sets session cookies.

Alternately, if you really want your username and password remembered, consider using Firefox's built-in feature of storing username (and/or passwords) for that site so that it will populate those fields for you.

**Comment by koolx** [comment] 2020-02-08 02:23
Thank you ken for that info. greatly appreciate your help for everything. Thank you once again!

**Comment by kennethtran93** [comment] 2020-02-10 03:26
You're welcome.  Closing issue since both support items should be resolved now.

**Closed as completed by kennethtran93** 2020-02-10 03:26 UTC
Labels: support
