### ISSUE TITLE
[Bug]  LocalStorage gone after cleanup of expired Cookies

### ISSUE THREAD

**Issue by sans-c** [mrdokenny/Cookie-AutoDelete#1462] opened 2022-11-17 12:50 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Setup:
* site X whitelisted (e.g. keep everything)
* enabled IndexedDB Cleanup, LocalStorage Cleanup, Service Workers Cleanup
* **enabled Clean All Expired Cookies**

When visiting site X it sets a cookie and makes use of LocalStorage. If and when this cookie expires it is cleaned up. However, LocalStorage is also gone. Not quite sure if this is CADs fault or some Firefox bug, but since a setting in CAD triggers the behaviour, I thought it best to report here.

### To Reproduce

1. Choose any site that makes use of cookies and LocalStorage (e.g. lichess.org)
2. Whitelist this site
3. Visit the site and check for presence of cookies and LocalStorage entries
4. Close the site-tab and wait for the cookie to expire (in order not to wait 10 years on lichess, you can set an arbitrary expiration date with the developer tools - for example set it 30 seconds in the future and wait for CAD-logs to show up)
5. Cookie expires and will be cleaned
6. **Additionally cleanup according to your setup will be invoked (in my case IndexedDB, LocalStorage and Service Workers)**
7. LocalStorage is gone, despite the site being whitelisted.

### Expected Behavior

I expected the expired cookie to be gone but for everything else to be left untouched. I am not completely sure if I misunderstood something to be honest. The fact that CAD apparently does the cleanup itself _and_ the site in question is whitelisted seems to indicate CAD does indeed cause this and it is not FF's fault. If this is expected behaviour, I'd be glad to learn about the intuition behind it.

### System Info - Operating System (OS)

Windows 10 x64

### System Info - Browser Info

Firefox 107.0 (64-bit)

### System Info - CookieAutoDelete Version

3.8.1

### Additional Context

Thanks in advance! If any more info is needed, let me know.

**Comment by kennethtran93** [comment] 2022-11-17 20:52
Duplicate of #1427, and it has been fixed via PR #1450 and should be published in the next version.

**Closed as not planned by kennethtran93** 2022-11-17 20:52 UTC
Labels: duplicate

**Comment by kennethtran93** [comment] 2022-12-08 03:30
3.8.2 has been released (on GitHub) and will be updated on browsers when the webextension team has approved it.
