### ISSUE TITLE
Reversed polarity:  Delete only cookies on blacklist

### ISSUE THREAD

**Issue by MikeBishop** [mrdokenny/Cookie-AutoDelete#350] opened 2018-02-08 17:45 UTC
### Describe the Bug/Feature

Currently, the extension deletes all cookies except the listed domains.  I would like to designate specific domains to have their cookies deleted automatically, but leave everything else alone.

**Comment by ke-d** [comment] 2018-02-09 02:11
Duplicate of #95

**Closed as completed by ke-d** 2018-02-09 02:11 UTC
Labels: duplicate
