### ISSUE TITLE
Flash Cookies or LSO

### ISSUE THREAD

**Issue by rayman89** [mrdokenny/Cookie-AutoDelete#264] opened 2017-11-21 23:52 UTC
I was wondering if this addon supports deleting and preventing the deletion of flash cookies or LSO's. If it doesn't could you consider extending it's functionality please?

**Comment by practik** [comment] 2017-12-05 17:00
This is already being worked on; see #44

**Comment by ke-d** [comment] 2017-12-06 00:30
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/removePluginData

I think that's the related API. The problem is that it doesn't support deleting by host yet like localstorage in FF 58+

**Comment by B00ze64** [comment] 2017-12-06 03:03
If you click on https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/RemovalOptions it says RemovalOptions accepts Hostnames, but only works on Cookies and LocalStorage. Are Flash cookies considered cookies?

**Comment by rayman89** [comment] 2017-12-06 05:57
What about this? https://addons.mozilla.org/en-US/firefox/addon/clear-flash-cookies/

**Comment by chiraag-nataraj** [comment] 2018-01-16 23:09
@B00ze64 No, Flash cookies are separate - they are stored in an entirely different place and can even be used between browsers (unlike regular cookies).

**Comment by Joel889** [comment] 2018-02-17 19:39
Forget Me Not does clear everything including flash cookies. I tested it on FF 58.02, clean profile and only  with Forget Me Not extension:
https://addons.mozilla.org/en-US/firefox/addon/forget_me_not/

**Comment by kennethtran93** [comment] 2020-04-23 02:47
Per reading Forget Me Not, it clears flash cookies/indexedDB/etc on browser reboot for everything, and only the lists are for cookies and localstorage, as we have now.

To keep things concise on this addon, I'll close this as browserbug limitation on the case that it cannot be cleared by hostname yet.

**Comment by kennethtran93** [comment] 2020-07-06 06:24
revived from #792.

**Closed as completed** 2020-07-24 03:23 UTC
Labels: has:pr
