### ISSUE TITLE
Autodelete not working at all in Containers...

### ISSUE THREAD

**Issue by GSF1200S** [mrdokenny/Cookie-AutoDelete#200] opened 2017-10-18 04:15 UTC
### Describe the Bug/Feature

I'm running Firefox 56 packaged for Arch Linux and the profile is relatively new. I have Cookie Autodelete 2.0.1. Works fine in the "default" container- cookies are deleted as soon as the tab is closed. In any other container (personal, work, self-made ones) it doesnt auto delete any cookies at all. I have the option selected for enabling container tab support. I've also tried 0, .1, and 1 for the delay option.

The cookies delete when I manually tell CAD to delete cookies in the domain. A manual clean does not work even if I invoke a "clean, including open tabs." Again, everything works fine in the "default" container.

From what I read in the documentation, Cookie Autodelete should work in containers in FF56+ if using version 2.x.x, but that isnt the case for me.

I am using a user.js file and wonder if a triggered option in that could be causing it? I dont think it would, and Firefox works fine otherwise including Containers themselves. 

I'm using a slightly more relaxed version of this: https://github.com/pyllyukko/user.js/tree/relaxed

### Your settings 

- OS/version: Arch Linux up-to-date
- Browser/version: Firefox 56
- Cookie AutoDelete version: 2.0.1

**Comment by ghost** [comment] 2017-10-18 09:35
Probably duplicate of https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/197 or rather, the same underlying bug.

Can you check, and confirm what I find in comment in above issue? 
Add any whitelisting rule (may be empty) to all containers, delete it - check if deleting cookies is working.

**Comment by bbende** [comment] 2017-10-18 16:23
I've experienced the same behavior reported in this issue while using Firefox 56.01, Cookie AutoDelete 2.0.1, Container 4.0.3.

I can confirm that after creating an empty whitelist rule for each container and then deleting it (suggested in comments of #197 ), cookies appear to be deleting correctly now for all containers.

**Comment by GSF1200S** [comment] 2017-10-18 18:58
Indeed- creating empty whitelist containers and deleting them fixes the problem: it now deletes cookies in any container as it should.

Do you need anything else from me to t/s this issue? Let me know and thanks...

**Comment by ke-d** [comment] 2017-10-23 16:24
Duplicate of #197

**Closed as completed by ke-d** 2017-10-23 16:24 UTC
Labels: duplicate
