### ISSUE TITLE
[BUG]  Firefox 79.0 CAD 3.5.0 - icon always blue even when sites are not in any lists

### ISSUE THREAD

**Issue by Justsean** [mrdokenny/Cookie-AutoDelete#848] opened 2020-08-21 01:37 UTC
Since 3.5.0 upgrade CAD icon is always blue even though websites are not white or grey listed

**To Reproduce**

Keep Default Icon on all list types is disabled
Have tried removing and reinstalling CAD - same result

If I add websites to white/grey lists then remove again the icon is red until a page refresh

**Expected behavior**

With "Keep Default Icon on all list types" setting disabled, icon should be blue/yellow/red to reflect settings for websites

**Your System Info (please complete the following information):**

 - OS: Windows 10 Pro
 - Browser Info: Firefox 79.0
 - CookieAutoDelete Version 3.5.0

**Comment by kennethtran93** [comment] 2020-08-21 04:29
Duplicate of #839.

**Closed as completed by kennethtran93** 2020-08-21 04:29 UTC
Labels: duplicate
