### ISSUE TITLE
[Please Check] Cookie-Autodelet now working with First-Party Isolation in Firefox

### ISSUE THREAD

**Issue by bluegrover** [mrdokenny/Cookie-AutoDelete#309] opened 2018-01-05 18:09 UTC
In the context of the Meltdown/Spectre problems it was suggest for Firefox in the about:config settings to set privacy.firstparty.isolate to true. 
If you do so, then Cookie-AutoDelete is not working any more. You still get the notification (if enabled) that cookies were deleted, but it is not the case. If your reverse the setting (flase) then everyting is fine again. (Maybe this works as to be expected, but still I open this issue)

**Comment by sorin-davidoi** [comment] 2018-01-05 22:41
Duplicate of https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/75.

**Closed as completed** 2018-01-06 22:43 UTC
Labels: duplicate
