### ISSUE TITLE
Auto-delete more forms of information

### ISSUE THREAD

**Issue by ArmoredDragon** [mrdokenny/Cookie-AutoDelete#52] opened 2017-06-18 01:30 UTC
Automatically deleting cookies is good, and this extension is great for that, but Chrome stores things like channel IDs and other local content that websites can use to identify you. For example, Washington Post nags you to subscribe after multiple visits, even though this extension deletes its cookies.

I'd like to see a feature that can automatically wipe all local content other than the few cookies I whitelist.

Thanks!

**Comment by mrdokenny** [comment] 2017-06-18 01:34
Duplicate of #44 and #38

**Closed by mrdokenny** 2017-06-18 01:34 UTC
Labels: duplicate
