### ISSUE TITLE
Cookie will not delete

### ISSUE THREAD

**Issue by SpaceClicker** [mrdokenny/Cookie-AutoDelete#538] opened 2019-06-14 02:27 UTC
I have a strange issue that isn't necessarily related to only this addon.  If you go to https://www.kinguin.net/ you will get cookies.  If you close the tab, it will tell you that the cookies have been deleted, but not all of them have.  It leaves behind a cookie "currencies:", and I have also seen it leave behind one other cookie.  Every time you close a tab, it will pop-up telling you cookies have been deleted for this domain, but the cookie is never deleted.  I have only seen this happen on this domain.  So the addon sees the cookie is there, but it unable to delete it.

I also tried deleting these cookies with the "Cookies Quick Manager" addon, but it is also unable to delete them.  If I go in to Options -> Privacy & Security -> Cookies & Site Data -> Manage Data and select the domain, and tell it to "remove selected" for that domain, and then "Save changes" it WILL delete the cookie(s). 

- OS/version: Windows 7
- Browser/version: Firefox 67.0.2
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment] 2019-06-16 04:21
I've successfully reproduced this bug.  Unfortunately this particular cookie isn't set by the server response via its `set-cookie` headers but through the script that the site/page loads (app.7a9ed399725085ae39f9.js).  Somewhere in their minified and obfuscated code sets additional cookies (currencies) via `document.cookie`.

Unfortunately the cookie that they set isn't fully compliant with the standards.  when they were generating the cookie to set, the `Expires `directive was not capitalized, so since it was (presumed to be) placed after the `Path `directive, the browser did not parse it properly, notably the 'Path' and 'Expires' directives, as noted through 

| the retrieval of the cookie via Firefox itself |  as well as through the Cookie Manager web extension |
|---|---|
| ![Developer Tools - Cookie AutoDelete Settings - moz-extensionae736277-b915-41d7-99fa-b89b5a1db078settingssettings html#tabCleanupLo](https://user-images.githubusercontent.com/6724477/59558864-b5493280-8fb0-11e9-9c84-85b5f16a4642.png) | ![Cookie Manager - Firefox Developer Edition](https://user-images.githubusercontent.com/6724477/59558869-c134f480-8fb0-11e9-9e3e-23ffb4bfe4da.png) |

So when this web extension creates the 'url' for that specific cookie to delete via https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/7563c02f07ecc7741fd58bad9f5a14d1a0be7b69/src/services/Libs.ts#L115-L124, the url that is used for cleanup is the one shown in the URL field through the Cookie Manager addon (http://www.kinguin.net/ expires=Thu, 01 Jan 1970 00:00:01 GMT).

Obviously to us that is not a URL with a valid Path, so I presume the cookies.remove failed to remove that (probably the same result from the other web extension you tried).  As to how Firefox removes it, it's probably a separate internal function different from the exposed cookies API.

**Comment by SpaceClicker** [comment] 2019-06-16 05:06
So is the proper fix here for Firefox to not allow this cookie to be set due to an invalid path?  Is it essentially a Firefox bug?

Is this cookie served back to the domain that set it?  It appears that this was an honest mistake, but can it be used as a way for a website to create persistent cookies that can not be deleted using the Firefox API?  If so, it would seem that is something the Mozilla team would want to fix.

**Comment by kennethtran93** [comment] 2019-06-16 05:32
Hmmm... I've tested this on Chrome browser and it also sustains that cookie so it is not necessarily a browser issue.  That being said they could try to implement better checks.  You could bring it up to them but I'm not sure how they would respond since it is the site that wasn't following the specifications properly...

**Comment by chiraag-nataraj** [comment] 2019-06-19 11:06
@SpaceClicker If it helps, I've found that I don't see this problem when I use temporary containers (of course, this is only on firefox). But I agree with you that ideally the cookie would either never be set or the API would be able to handle letting extensions delete it.

**Comment by SpaceClicker** [comment] 2019-06-20 23:44
This is not a problem for me, I was just reporting a "bug".  I only visit this site incidentally through another site (when I click on a link on this site, it also pops up a new tab with the problem site, which I immediately close), so I don't really care about the cookies from this site, and I just tell Firefox to "Block" the cookies from this domain and I never get any cookies stored.

**Comment by kennethtran93** [comment] 2019-07-01 22:51
I'm going to close this external bug at this point as we're probably not going to add additional code just to deal with this particular instance. 
Your solution is pretty much what others should do in this case.

**Closed as completed by kennethtran93** 2019-07-01 22:51 UTC
Labels: bug, wontfix/cantfix, external
