### ISSUE TITLE
[Feature request] This extension should delete local storage of non-whitelisted websites

### ISSUE THREAD

**Issue by js-d-coder** [mrdokenny/Cookie-AutoDelete#280] opened 2017-12-04 07:08 UTC
Some websites put [local storage data](https://support.mozilla.org/en-US/kb/permission-store-data) to store some data offline for later use. It can also be used to track you even if you delete their cookies and _I think YouTube does that._  
It will be great if this extension can delete local storage of non-whitelisted websites along with their cookies.  
Thanks.

**Comment by practik** [comment] 2017-12-05 16:59
Already in the works; see #44

**Comment by ke-d** [comment] 2017-12-06 00:08
Duplicate of #44

**Closed as completed by ke-d** 2017-12-06 00:08 UTC
