### ISSUE TITLE
[SUPPORT]  CAD not deleting data from Default Storage

### ISSUE THREAD

**Issue by click-click** [mrdokenny/Cookie-AutoDelete#1257] opened 2021-11-01 17:07 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

CAD does not always remove data left behind in the default storage. A good example of this is the twitter website. Every time I visit the site, it drops about 5MB of data in \storage\default. I always have to use the Cookies and Site Data settings from Firefox to remove the data left behind. Other sites do this too. It seems CAD cannot always cleanup the garbage or am I missing something?

**Comment by kennethtran93** [comment] 2021-11-02 06:02
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-do-i-still-see-storage-being-used-after-cad-cleans-cookies-and-localstorage-data

This webextension currently only cleans up the following site data types, if enabled in CAD settings:
- Cookies
- Localstorage (and possibly sessionstorage)
- IndexedDB
- Plugin Data (deprecated Flash stuff)
- Service Workers
- Cache (though you may wish to keep disabled as it seems to take a while to complete at times - non extension issue)

Other data types not listed here have not been implemented for cleanup yet.

**Comment by click-click** [comment] 2021-11-02 09:42
I tried enabling cache cleanup, but for twitter.com the data dropped in **\Firefox\Data\profile\storage\default\https+++twitter.com\cache\morgue\** does not get deleted. Can CAD do this?

**Comment by ghost** [comment] 2021-11-02 12:31
This can be related https://bugzilla.mozilla.org/show_bug.cgi?id=1647017 

Firefox seems to keep old data in this "morgue" directory until there is enough disk space left. (I don't really understand this "morgue" concept and it's broken if you ask me).

**Comment by click-click** [comment] 2021-11-02 14:03
Have you considered removing  \morgue data  with CAD as an option?

I found a work-around for this problem, but it's only for websites where you do not need to keep their cookies such as in my case, twitter.com, where I only read posted links now and then. This is what I did: 

Firefox Settings > Privacy & Security > Cookies and Site Data  > Manage  Exceptions > Block twitter.com

**Comment by ghost** [comment] 2021-11-02 15:50
Outdated, see https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1257#issuecomment-1438176257

<details>
<summary>Details</summary>

If you block service workers some storage api's will not be used and nothing will be stored there. It's how I solved my problem with Slack (`||slack.com^$csp=worker-src 'none'` added to My filters in uBO). This "morgue" folder seems to be like Trash/Recycle bin - everything deleted is moved there, but there is no way to empty it manually (CAD cannot touch this folder). It's only emptied if you fill your disk with lot of files so there is not much space left, then it will be removed on next Firefox start(shutdown?)(It will probably kept there forever if you don't use Firefox often). And of course you can clean it with other data by cleaning cookies using browser settings, but this is rather overkill.

^ This is how I understand it works.

</details>

**Comment by kennethtran93** [comment] 2021-11-03 02:36
> Have you considered removing \morgue data with CAD as an option?

We do not have that functionality unfortunately.  All we can do is pass in domains and which site data type to clean, and optionally the time frame (which is, by default, all for that domain).  All we have control over to remove is documented here:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData

**Comment by kennethtran93** [comment] 2021-11-21 06:44
Closing as a browser limitation as this is not a bug that CAD can fix.  Not entirely sure if an API will get added by the Firefox webextension team to do this, but if it is a recycle bin of some sort, I doubt we would get access to this either.

**Closed as completed by kennethtran93** 2021-11-21 06:44 UTC
Labels: browserbug/limitation, Firefox

**Comment by ghost** [comment] 2023-02-21 09:52
https://bugzilla.mozilla.org/show_bug.cgi?id=1817892

>As mentioned in [bug 1817891](https://bugzilla.mozilla.org/show_bug.cgi?id=1817891) on documenting the "morgue" directory, the "morgue" directory name is actively misleading and should be changed when we next have a reason to introduce a schema change. [Bug 1593365](https://bugzilla.mozilla.org/show_bug.cgi?id=1593365) for QM v4 storage is probably the best time to do this.

>The most accurate and straightforward name would be "bodies" because the files are Response Bodies (and do not include the header data), but "responses" is probably a better term because "bodies" has a very unsettling connotation in the context of the predecessor term "morgue".


XD LOL

***

But AFAIK it still keeps these files after CAD delete the storage? Right? Or there is some other Bugzilla entry where this issue was recognized and hopefully be fixed?
