### ISSUE TITLE
FR: Also clear localStorage

### ISSUE THREAD

**Issue by waqas** [mrdokenny/Cookie-AutoDelete#165] opened 2017-10-03 09:16 UTC
### Describe the Bug/Feature
It does delete cookies as the name implies but some websites store identifying information in local/html5 Storage also. If possible, can this also delete that?
Thanks.

Firefox 57b5

**Comment by ghost** [comment] 2017-10-03 13:36
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44

**Comment by ke-d** [comment] 2017-10-03 14:34
Duplicate of #44

**Closed as completed by ke-d** 2017-10-03 14:34 UTC
Labels: duplicate
