### ISSUE TITLE
Autoclean and session cookies behaviour

### ISSUE THREAD

**Issue by SunnyMoo** [mrdokenny/Cookie-AutoDelete#605] opened 2020-01-12 15:53 UTC
Hi !

Here's a strange behaviour that I don't understand so I need your help.

I've two or three whitelisted websites using session cookies.
If I disable CAD autoclean they stay alive for a month.
If I enable CAD autoclean aforementioned session cookies are deleted after some time maybe 10 or 15 minutes after closing FF but not instantly after closing. In fact I can open FF multiple times and having those cookies alive. Or not. I really don't understand.

Note CAD don't mention those cookies deletion in its logs.
Note I tried to edit them (ctrl+shift+i) and change session to december but they end to be reset to session.
Also note CAD is the only cookie cleaning option set. All other options on FF or extensions are set to not delete cookies.

Reason I'm asking help here is because those cookies stay alive when CAD autoclean is off.
How can I enable CAD autoclean and keep those session cookies for months ?

Thanks !

**Comment by kennethtran93** [comment] 2020-01-16 00:19
You'll need to provide screenshots, CAD&Firefox Cookie Settings, any logs and cookies/websites that does this to assist in your case.

**Comment by SunnyMoo** [comment] 2020-01-16 01:01
There's no log and screenies won't help at all but nvm:
![Capture1](https://user-images.githubusercontent.com/50081326/72484205-68a23000-37fb-11ea-9364-865ac25a6406.PNG)
![Capture](https://user-images.githubusercontent.com/50081326/72484454-2fb68b00-37fc-11ea-8208-6dd195a1211f.PNG)
![Capture2](https://user-images.githubusercontent.com/50081326/72484206-693ac680-37fb-11ea-8e03-2309a09f1de5.PNG)
![Capture3](https://user-images.githubusercontent.com/50081326/72484207-693ac680-37fb-11ea-80fc-89ab1fefc2ac.PNG)

**Comment by kennethtran93** [comment] 2020-01-16 04:07
You're right in a sense that screenshots don't help after re-reading your issue again.

It is your site that sets the cookies themselves.  They probably made it that way for better security.  It's ultimately up to them to set how long those cookies will last.

'**Session**' cookies are technically supposed to be erased after each browser session.  It becomes a more '_permanent_' cookie if an expiry was set (though the site can change the cookies again as you had experienced).  Do you set your browser to reload the tabs/session again after closing it?  That may extend the 'session' for a bit according to this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

![Untitled](https://user-images.githubusercontent.com/6724477/72492119-f61c5a80-37d0-11ea-9cd5-9b932a9c1a98.png)


Since there weren't any logs on the CAD side, then it is not the CAD side that is cleaning it up.  When Firefox cleans up session cookies is in their area.

There's a webextension called cookie manager that may help you edit the cookies in a more user-friendly way.  The Expiry is probably done in a specific format. (see screenshot above)

**Comment by kennethtran93** [comment] 2020-01-16 04:08
I'll keep this issue open for a bit just in case you need further clarification.  However at this point it is not a bug in Firefox or CAD.

**Comment by SunnyMoo** [comment] 2020-01-16 15:47
Transforming session to permanent cookies is another issue I shouldn't have mentionned because it makes things unclear.
My apologies.

The real problem is (simplified):
- autoclean disabled = whitelisted session cookies lives for a month.
- autoclean enabled = whitelisted session cookies lives for an hour

As the only change I make is enabling/disabling autoclean it seems obvious to me that CAD is the cause.
Considering CAD log don't mention cleaning it I guess enabling autoclean might trigger something that forces FF to dump session cookies even if FF is set not to delete any cookie.

So, trying a different approach, what happens under the hood when I  enable/disable autoclean ? (changed settings etc...)

Thanks !

**Comment by kennethtran93** [comment] 2020-01-18 00:16
Session cookies are supposed to be removed by Firefox itself after the browser closes.  Session restores, however, may keep those session cookies on for longer.  I'm not sure exactly how Firefox internal cookie cleanup gets triggered at this time.

**Comment by SunnyMoo** [comment] 2020-01-18 01:24
I've enabled session restore as you told hope it won't interfere with CAD. Thanks.

**Comment by kennethtran93** [comment] 2020-01-18 03:12
As long as you close Firefox while you still have those tabs open.

Closing this as it isn't a bug on our end nor Firefox's end.

**Closed as completed by kennethtran93** 2020-01-18 03:12 UTC
Labels: not a bug / expected behavior
