### ISSUE TITLE
Weird UI when put into drop down list

### ISSUE THREAD

**Issue by waqas** [mrdokenny/Cookie-AutoDelete#178] opened 2017-10-13 05:56 UTC
right-click on toolbar -> Customise...
Like this...
![ ](https://user-images.githubusercontent.com/407/31532137-e02b0204-b004-11e7-858c-1e5b53a4c6be.png)

**Comment by ke-d** [comment] 2017-10-13 05:58
It looks like the overflow menu doesn't like a min-width for the popup?

**Comment by waqas** [comment] 2017-10-13 05:59
Apprently, yes. Previous popup UI was also behaving like this.

**Comment by ke-d** [comment] 2017-10-13 06:04
I'm not sure if I have to do anything or if Mozilla has to fix anything on their end?

I also noticed a couple of UI problems in the overflow menu with other extensions as well.

@jonathanKingston Do you know if there's a Bugzilla bug for this?

**Comment by grenzor** [comment] 2017-10-13 10:51
I believe this is the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1373490

**Comment by uniquePWD** [comment] 2017-10-13 17:24
It feels like the new UI was designed in a desktop bubble. It seems to stretch horizontally when both on desktop and mobile, it makes more sense to design it vertically. I hope that @seansfkelley can resubmit a better and more useful design. Also it was far more useful (to me at least) to show the list of cleared cookies than just show the rules for the current domain in the popup.

Anyway, here's another screenshot to show how broken it looks on desktop
![cad-newui-sucks](https://user-images.githubusercontent.com/203217/31557994-164cfd2c-b043-11e7-9fbe-fd40f88c3864.png)

**Comment by seansfkelley** [comment] 2017-10-13 19:07
@pwd-github just submitted #180 to fix the most egregious problems with the layout. I plan to take a deeper look at it over the next few days now that the design has had some time to bake/be in the wild.

The replacing of the "most recently cleared cookies" note on the bottom with the table was prior to my work, though I personally always found that note to be misleading and noisy and was happy to see it gone.

**Comment by ke-d** [comment] 2017-10-13 19:14
Note that I added a `min-width` property in 8d3726bc9562876389e14547cebf8568152158b6 to fix the popup size in Chrome. What I could do (if it's still needed after @seansfkelley's PR), is apply it only on Chrome.

**Comment by uniquePWD** [comment] 2017-10-13 19:14
@seansfkelley I'm sure that everyone has different use cases for the extension, but for me. If I have had to open a few links, I often use CAD to clear the cookies from known trackers such as instagram. However I seldom ever open an instagram tab and only ever in fact use CAD at the end of a session. It's at that point, I'll want to confirm that CAD is doing its job and has gotten any cookies that may have infected me. However the current user experience doesn't allow that.

Also to check the mobile popup from a desktop, just open up the WEID/popup.html on your desktop browser. The first thing you'll need to do is not hardcode text sizes instead use relative textsizes and you'll also need to remove the useless margins.

**Comment by ke-d** [comment] 2017-10-13 19:25
@pwd-github The "most recently cleared cookie list" caused weird popup stretching issues in Firefox Desktop. I think maybe a log tab in the options page might be better?

**Comment by seansfkelley** [comment] 2017-10-13 19:34
@mrdokenny ah, I was wondering why that was there. The commit message was a bit vague. Applying it only in Chrome seems like the right way to go, though as I mentioned on the PR (https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/180#issuecomment-336544993) I'm tooling around on changing some parts of the design closer to how they used to be to be more flexible w/r/t different widths and flows.

As for the "deleted cookies" message, the reason I found is misleading is because I use the time-based autodeletion behavior, so every time I saw it, it was just naming whichever sites I happened to close most recently (and therefore have the cookies cleaned from), which wasn't terribly useful and, in the cases where I had already forgotten the name of the site, confusing (as in, "where did this cookie come from in the first place that it claimed it deleted?").

A log tab seems like a good thing to have in general (opt-in, probably, since it'll effectively be tracking what sites you've been to). Then you could just link from the popup (and perhaps the optional system notification behavior?) to the Log section of the settings page. This would both (1) avoid crowding the popup with potentially a ton of domain names, making it difficult to read/use, (2) make the log discoverable, (3) give long domain lists space to breathe, and (4) not confuse users in my situation where we don't care and aren't auditing the deletions (I have also turned off notifications). How does that sound @pwd-github?

**Comment by uniquePWD** [comment] 2017-10-13 19:48
@mrdokenny I always kept it in the overflow menu on desktop, so I wouldn't know. It seemed to act properly for me, it was aesthetically pleasing and was an enjoyable user experience. It would be preferable if, for both desktop and mobile, I wouldn't have to leave the popup to confirm which cookies have just been cleared. But ultimately, as long as it can be checked, it's better than the current implementation.

@seansfkelley  I never used the auto clean feature and so it was only ever cleaning on demand, at which point it was incredibly useful to me. I think the problem was that the assumption was that people used the auto clean function, that people never put it in the overflow menu and that mobile is a second-class citizen despite the issue being raised of the mobile UX long ago in issues such as that of #140 . Hopefully going forward these things can be taken into consideration when design decisions are being made.

Personally I feel that the new design is just really confusing and introduces a lot of complexity for reasons beyond my comprehension.

**Comment by jonathanKingston** [comment] 2017-10-17 13:00
> I believe this is the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1373490

Yeah I think this is a central bug, I'm not sure there is much to fix from your side. I think the hope is to uplift this to 57.

**Comment by ke-d** [comment] 2017-10-27 23:40
Fixed as of 2.0.1

**Closed as completed by ke-d** 2017-10-27 23:40 UTC
Labels: bug
