### ISSUE TITLE
“Clear local storage” doesn't seem to work

### ISSUE THREAD

**Issue by alex23897456** [mrdokenny/Cookie-AutoDelete#373] opened 2018-03-24 09:49 UTC
Hello. When I open Cookie Autodelete settings (browser - firefox) and set "clear local storage (firefox 58+)" and then restart firefox, the browser has all the local storage data in it, hasn't been deleted. I can see it in firefox settings where is says how much space this data has taken and all domains that store this data. So the function simply doesn't work. Can yo fix it or explain if I'm doing something wrong.

**Comment by ke-d** [comment] 2018-03-24 22:31
Hi, this is a duplicate of #171. As site data includes both IndexedDB and Localstorage.

**Closed as completed by ke-d** 2018-03-24 22:31 UTC
Labels: duplicate
