### ISSUE TITLE
Restore Default Settings clears Expression List

### ISSUE THREAD

**Issue by sedlund** [mrdokenny/Cookie-AutoDelete#330] opened 2018-01-20 11:51 UTC
### Describe the Bug/Feature

Clicking 'restore default settings' clears my expressions.  I thought this would just reset the check boxes above it.   I'm not sure that it should clear the expressions.  Or it should be made clear that is going to happen.

### Your settings 

- OS/version: chromeos
- Browser/version: chrome 63
- Cookie AutoDelete version: 2.1.0

**Comment by ke-d** [comment] 2018-01-22 05:25
Duplicate of #217

**Closed as completed by ke-d** 2018-01-22 05:25 UTC
Labels: duplicate
