### ISSUE TITLE
issue with pop-up message

### ISSUE THREAD

**Issue by asheenlevrai** [mrdokenny/Cookie-AutoDelete#709] opened 2020-05-02 09:15 UTC
Hi :)

The following error message keeps popping up all the time (every time I close a tab at least):
![Annotation 2020-05-02 110952](https://user-images.githubusercontent.com/5127613/80860132-0b28d680-8c66-11ea-9cb7-5d1e7715452d.jpeg)

I believe this started following an update of the add-on.

Please let me know what to do.
Best,
-a-

### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by kennethtran93** [comment] 2020-05-02 21:42
A) Please search issues before making a new one.  This is a duplicate of #699 and others.
B) Please fill in the issue template accordingly.

**Closed as completed by kennethtran93** 2020-05-02 21:42 UTC
Labels: duplicate

**Comment by asheenlevrai** [comment] 2020-05-03 08:49
Thank you so much for your rapid answer :)
Please pardon me for not doing my homework properly.
I'm sorry.

I now read issue #699 (I failed at detecting other threads related to the same bug) but didn't understand all of the replies since many are technically beyond what I can understand.
AFAIU, you are currently actively trying to fix this bug and the problem should be solved in a future update of CAD. Please let me know if I didn't understand correctly.

I am a little bit puzzled by the fact that some of my computers don't show this error while they are all supposed to run the latest version of FF, CAD, Win10.

Thank you once again for your great work and the quality of your support.

Sincerely,
-a-

**Comment by kennethtran93** [comment] 2020-05-04 17:23
It is most likely a cookie set by local file (not by us) or a domain that somehow didn't parse properly.  I'm trying to add debug message into the extension so that we can see the flow of things.

In the meantime, you can check your firefox preferences -> privacy -> cookies and site data, and if there is any `(local file)` mentioned then you will need to remove them yourself.
