### ISSUE TITLE
[BUG] Cookies are not being deleted

### ISSUE THREAD

**Issue by bkaradzic** [mrdokenny/Cookie-AutoDelete#678] opened 2020-04-05 02:53 UTC
**Describe the bug**

Cookies are not being deleted, and none of suggestion from FAQ help.

Even clicking on "Clean" leaves cookies lingering.

**To Reproduce**

Nothing special.

**Expected behavior**

All cookies deleted.

**Screenshots**

N/A

**Your System Info (please complete the following information):**

 - OS: Linux (but seen this issue on Windows and OSX)
 - Browser Info: Firefox 74.
 - CookieAutoDelete Version: 3.1.1

**Additional context**

N/A

**Comment by snowbound** [comment] 2020-04-07 04:00
I need it to delete sid@*.google.com on browser restart. So I greylist that in the expression. Yet when I restart the browser I am still logged into my Gmail accounts. Does not seem to be deleting that cookie.

**Comment by kennethtran93** [comment] 2020-04-07 18:08
@bkaradzic Could you screenshot your CAD settings here?  Also which area did you see the leftover cookie results?

@snowbound Could you start a new support issue please?

**Comment by bkaradzic** [comment] 2020-04-07 21:26
Everything is checked except:

    [ ] Show Notification After Cookie Cleanup 3 second(s)?
    [ ] Enable Support for Firefox's Container Tabs?

**Comment by kennethtran93** [comment] 2020-04-21 16:57
What's is your delay seconds set to?

I'm still missing the response to my previous question: 
> which area did you see the leftover cookie results?

**Comment by bkaradzic** [comment] 2020-04-21 17:02
> What's is your delay seconds set to?

15 seconds

> which area did you see the leftover cookie results?

Don't quite understand the question. When I go to Preferences -> Privacy & Security -> Manage Cookies and Site Data, I see bunch of cookies that are not on white list. Even sites I accessed 13 days ago. It would be nice to have some force clean options that would nuke everything that's not on white list.

**Comment by kennethtran93** [comment] 2020-04-21 18:20
It may help if you post a screenshot of that area, even though I know what you are talking about.  It shows your urls and cookie count as well as storage.

While you are on that area you can manually remove unwanted domains as well, but do screenshot it and upload it here before doing so.

As the next step:
Try accessing this:  `about:devtools-toolbox?type=extension&id=CookieAutoDelete%40kennydo.com`.  If that doesn't work, go to `about:debugging` and click on `Inspect` next to CookieAutoDelete's item.

You'll then be shown a console.  Keep it open, and try manually running either `clean` or `clean include open tabs` and see if any errors show up and screenshot it as well.

Thanks!

**Comment by bkaradzic** [comment] 2020-04-21 19:55
```
Could not map contract ID '@mozilla.org/sharepicker;1' to CID {1201d357-8417-4926-a694-e6408fbedcf8} because no implementation of the CID is registered.
Content Security Policy: Couldn’t parse invalid host 'wasm-eval'
Error: Invalid tab ID: 19 3 undefined
Content Security Policy: Couldn’t parse invalid host 'wasm-eval' 2
Error: Invalid tab ID: 50 3 undefined
Error: Invalid tab ID: 85 2 undefined
Content Security Policy: Couldn’t parse invalid host 'wasm-eval'
stateManager.tabs[tabIdentifier] is undefined 2 state-manager.js:155
Error: Invalid tab ID: 108 2 undefined
Error: Invalid tab ID: 127 3 undefined
Content Security Policy: Couldn’t parse invalid host 'wasm-eval'
Error: Invalid tab ID: 137 2 undefined
Error: Invalid tab ID: 126 3 undefined
Error: Invalid tab ID: 1 3 undefined
Error: Invalid tab ID: 154 5 undefined
Error: Invalid tab ID: 175 3 undefined
Error: Invalid tab ID: 187 3 undefined
Content Security Policy: Couldn’t parse invalid host 'wasm-eval'
Error: Invalid tab ID: 197 3 undefined
Error: Invalid tab ID: 209 3 undefined
```

**Comment by bkaradzic** [comment] 2020-04-21 20:02
> If that doesn't work, go to about:debugging and click on Inspect next to CookieAutoDelete's item.

There is no CookieAutoDelete in there...

**Comment by kennethtran93** [comment] 2020-04-22 03:12
Pasting it as a code doesn't help as the console includes filenames to the right and whatnot - a screenshot would have sufficed.

What other extensions have you installed?  

Are you using the extension in a Private Browsing mode or Permanent Private Browsing?  This extension does not work properly in any Private Browsing mode.

My bad - I meant `about:debugging` then `This Firefox`, then `Inspect` on CookieAutoDelete.  This would essentially bring up the same console as the url from my last post.

Trying to decipher the console log you provided (unfortunately these console logs can include lines from other extensions...).  I should have asked you to clear the console log before attempting the manual cleanup.

First line about the `sharepicker`:  https://bugzilla.mozilla.org/show_bug.cgi?id=1615109 which may be an unrelated issue but will apparently be fixed in Firefox 76 (They have a 'wontfix' for 74 and 75).

This line `stateManager.tabs[tabIdentifier] is undefined 2 state-manager.js:155`, upon search, appears to be something relating to the extensions of decentraleyes and/or temporary-containers.

I'm not sure where the CSP is coming from as our extension doesn't make any external web requests or modify the tab contents (with the exception of manual `clean localStorage for this domain` which only executes `window.localStorage.clear();window.sessionStorage.clear()` on the tab the CAD popup is currently shown for.

Unfortunately there seems to be nothing related to CAD on there that I can see of.

I'll try and fix the cleanup logs to show more details as soon as I can, but in the meantime this is the best support I can give at this time.

**Comment by kennethtran93** [comment] 2020-04-22 03:51
Seeing as you may be actually using containers on another extension, try enabling CAD's container support and see if it makes any difference on clean?

My apologies as I don't know half of how this web extension works so I can't debug it properly or give you a better answer/solution at this time.  I was only given developer/maintainer status a couple months ago after contacting the repo owner.

**Comment by bkaradzic** [comment] 2020-04-22 06:12
Removing all extensions doesn't do it either... It logs it removed cookie, and nothing.

**Comment by kennethtran93** [comment] 2020-04-23 16:45
It's a long shot, but did the console log show anything after all other extensions were disabled?

With not much details to run on, it is hard to debug this.  I'll try and get a debug version out to you with more console logs soon.

**Comment by kennethtran93** [comment] 2020-05-02 21:58
Quick question  - from the cookie and site data panel in the browser, is the cookie count set to 0 and there's other site data remaining or is it actual cookies lingering...?

**Comment by bkaradzic** [comment] 2020-05-03 03:17
Yeah cookie count is 0. Do you know what other data might be lingering?

**Comment by kennethtran93** [comment] 2020-05-04 17:43
So the cleaning functions are working as intended.  The remaining data (if you have localstorage cleaning enabled), are most likely from indexedDB, to which extensions cannot clean that by hostname yet (I believe it is being implemented in a near future major release).

Firefox combines storage from both localStorage and indexedDB.

I'll close this now and reference the indexedDB issue that I reopened for tracking #171.  There's other closed issues relating to this as well.

**Closed as completed by kennethtran93** 2020-05-04 17:43 UTC
Labels: support, browserbug/limitation
