### ISSUE TITLE
Not Work on Kiwi (android)

### ISSUE THREAD

**Issue by nkaplan1** [mrdokenny/Cookie-AutoDelete#533] opened 2019-06-02 12:10 UTC
### Describe the Bug/Feature

The extension does not appear to work with kiwi browser on android.

### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by kennethtran93** [comment] 2019-06-07 23:18
Duplicate of #528

**Comment by kennethtran93** [comment] 2019-06-11 00:07
Duplicate of #528

**Closed as completed by kennethtran93** 2019-06-11 00:07 UTC
Labels: duplicate
