### ISSUE TITLE
Cookies are not cleared while closing browser

### ISSUE THREAD

**Issue by myfrndjk** [mrdokenny/Cookie-AutoDelete#465] opened 2018-11-20 10:45 UTC
### Describe the Bug/Feature
Not sure it is a bug/expected behavior but felt like this is kind of edge case.
If it is false alarm kindly close it

If you close the browser with last tab(only one tab) with some website (ex: www.gmail.com) then cookies are not cleared for that website.  if I reopen browser next time cookies of last website  while closing the browser (www.gmail.com)  is not cleaned automatically.

### Steps for anyone to reproduce the bug

1.Open a browser
2.Open 3 different website in 3 different tabs (especially : www.gmail.com )
3.Close remaining 2 tabs and keep only gmail tab as last tab
4.Close the whole browser
5.Reopen the browser
6.This time you will still see google cookie even though auto clean is enabled.

Expected : 

Add on should be clearing cookie while closing browser

Current : 
Cookies are not cleared if browser itself is closed

### Your settings 

- OS/version: Mac mac sierra
- Browser/version: 62-FF
- Cookie AutoDelete version: 2.2.0

**Comment by sm4rk0** [comment] 2018-11-21 08:03
Maybe this is related to this statement from https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/14#issuecomment-301370315

> Also, currently there's no way to set an extension to do something on exit with current WebExtension APIs, so it would have to be on browser start up.

**Comment by sm4rk0** [comment] 2018-11-21 08:07
Duplicate of https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/268?

**Comment by ke-d** [comment] 2018-12-30 02:04
Enable `Clean Cookies from Open Tabs on Startup`

**Closed as completed by ke-d** 2018-12-30 02:04 UTC
Labels: not a bug / expected behavior
